### ISSUE TITLE
what's the purpose of options.reverse ?

### ISSUE THREAD

**Issue by kktos** [igorescobar/jQuery-Mask-Plugin#1]
Igor,

in your documentation, you aren't explaining the purpose of the option reverse.

And very nice and efficient plugin. Thanks a lot.

Cheers.

**Comment by joaomelont** [comment]
Hi Igor, I just saw you've made adjustements to the plugin so now user can explicitly inform caret characters, ',' or '.'.

I didn't figure out how to use it. On my demo the caret characters are still ignored.

Is there any documentation enlightening how to allow users to input '.' or ','?

Thank you very much, it's an awesome component.
