### ISSUE TITLE
Difference between recursive and reverse.

### ISSUE THREAD

**Issue by satyaprakash8** [igorescobar/jQuery-Mask-Plugin#106]
The reason i am asking that question is. When i give the following mask.

$('#Income').mask('00,000,000',{reverse: true}) 

When i press some number first and then press some other key and hold it for some time and release it, then the digits that i entered first are gone. Below is the link to fiddle

http://jsfiddle.net/Wj53Z/2/

What is the difference of using 

$('#Income').mask('00,000,000',{reverse: true}) 

and 

$('#Income').mask('##,###,###',{reverse: true}) . When i use this it is allowing me to enter more than 8 digits.

**Comment by neverfox** [comment]
This wasn't at all clear from the github.io page, where the example (without maxLength) implies the continued recursion:

> With jQuery Mask Plugin you can also define recursive patterns inside your mask: 
>
> `$('.money_example').mask('#.##0,00', {reverse: true});`
>
> With example above the mask will be placed from the right to the left (that's why reverse:true is defined). As soon as you start typing, a "0,00" will be applied followed by repeating recursively the following pattern "#.##". The result could be something like: 1.234.567,890.
