### ISSUE TITLE
Bug com tags contenteditable="true"

### ISSUE THREAD

**Issue by Roriz** [igorescobar/jQuery-Mask-Plugin#109]
Ao colocar a mascara em um conteúdo contenteditable="true" ele fica sempre reverse=true

**Comment by philgruneich** [comment]
Mesmo do issue #304 

https://github.com/igorescobar/jQuery-Mask-Plugin/issues/304

**Comment by lucasumberto** [comment]
Olá,
Estou tendo um problema com um campo de tabela editável (o problema acontece em qualquer tag editavel, div, span etc...)

Eu quero usar a máscara para dinheiro "#.00" porém acontece algo diferente de quando digito em um input:

No caso quando eu coloco no input **12345** o resultado é **123.45**
Agora quando eu tento colocar na tag com contenteditable='true' **12345** o resultado é **451.23**

O fluxo de digitação se perde quando chega na primeira casa após o ponto e pula do lado direito para o lado direito, mas continua com o comportamento reverse, só que depois do 1.

Segue exemplo:
https://jsfiddle.net/lucasumberto/o3rjaLf0/1/

Agradeço desde já!
