### ISSUE TITLE
Negative Numbers

### ISSUE THREAD

**Issue by ingodjango** [igorescobar/jQuery-Mask-Plugin#125]
Hi,
is there a way to use the mask plugin with negative input values?

e.G. pressing minus would apply the minus sign pressing plus remove it?

Thanks,
BR
Ingo

**Comment by dodonut** [comment]
I've managed to do it. Here follows the link: http://jsfiddle.net/dodonut/LnFR8/400/

**Comment by igorescobar** [comment]
@dodonut have you tested the number -100,00?

**Comment by dodonut** [comment]
@igorescobar I think now its ok. Please, give it a try!! http://jsfiddle.net/dodonut/LnFR8/429/

**Comment by Eclipse-Computing** [comment]
I have found another bug. If you load up the form with pre-existing data, such as a -100, the comma will still be between the - and the 100.

This occurs on the 429 JSFiddle directly above.

**Comment by DSBRBrasil** [comment]
> @igorescobar I think now its ok. Please, give it a try!! http://jsfiddle.net/dodonut/LnFR8/429/

It's works very well ! thks @dodonut
