### ISSUE TITLE
How can i limit the ip mask?

### ISSUE THREAD

**Issue by aHyunjaePark** [igorescobar/jQuery-Mask-Plugin#142]
Hi,

I truly appreciate that your team is providing an awesome plugin like this.

Tiny little thing i'm curious about is about the ip address masking.

like in the example.

$('.ip_address').mask('099.099.099.099/00',options);

the ip address can be inserted over 255, which is invalid.

Can i get some advise how to control, if the digits are over 255, set the number to 255?
(ex> 800 -> 255)

Thank you.

**Comment by MurkBRA** [comment]
Vi que você mostrou como faz mas não dei conta to aprendendo ainda.
Não teria como você fazer essa translation limitando ip em um range de 255? Por favor.
