### ISSUE TITLE
Back button clearing input values in Android latest versions

### ISSUE THREAD

**Issue by sreeyashu** [igorescobar/jQuery-Mask-Plugin#158]
On Android latest versions(S3 Mini) when ever you input something like this 123 456 789 where mask(000 000 000) is applied and try to remove the input one by one the first character remains there not able to remove it, on debug I got to know that it is because of I am using input type as "tel", But for me having a Numeric keypad is extremely important, Is there any way That it can be solved.

**Comment by conceito** [comment]
Anything new about it? It's happening only with a phone mask. Weird.
