### ISSUE TITLE
Input mask for just text

### ISSUE THREAD

**Issue by karlhadwen** [igorescobar/jQuery-Mask-Plugin#166]
I've been searching for the past hour in regards to see if the plugin can work with just text, at any length, and with any amount of words. Is this possible?

An example would be:

Company Name: jQuery Mask Plugin Company

The mask being: Company Name:

**Comment by dr-martin** [comment]
This can be a future feature? (maybe?)

**Comment by igorescobar** [comment]
@karlhadwen I'm sorry. I have noticed that I gave you a retarded answer 😆 . You can achieve that by using recursive the pattern (also explained on docs).
