### ISSUE TITLE
Using any key + tab lets you put anything inside a field

### ISSUE THREAD

**Issue by jonasflesch** [igorescobar/jQuery-Mask-Plugin#177]
Hello friends!

We are experiencing a bug here. It can even be simulated in the example page.

Here is a the step-by-step to simulate it:
- Put the focus in the field (CPF by example)
- Press "a" and keep it pressed
- Press Tab

It will let the "a" inside the field.

I would be very glad if someone can fix this.

Thank you!

**Comment by igorescobar** [comment]
Already fixed.
