### ISSUE TITLE
Invalid characters are showing in inputs ...

### ISSUE THREAD

**Issue by mdmoura** [igorescobar/jQuery-Mask-Plugin#191]
Hello,

When I type an invalid character on an input the character is displayed and erased just after.

Wouldn't be possible to not even allow the character to be written, e.g., to not display it?

Something like http://digitalbush.com/projects/masked-input-plugin/ uses ... Try the demo.

You will see that when typing an invalid character it does not show ...

Thank You,
Miguel

**Comment by igorescobar** [comment]
upgrade to v1.13.0
