### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by ray73864** [igorescobar/jQuery-Mask-Plugin#198]
Is there anyway to have the placeholder always visible? 

Currently the placeholder shows when the input box in question doesn't have the focus, but as soon as it has the focus and you start typing, the placeholder disappears.

**Comment by wototech** [comment]
@ray73864 what is the plugin you are using to show the placeholder while the user typing?

**Comment by ray73864** [comment]
> @ray73864 what is the plugin you are using to show the placeholder while the user typing?

This one here: https://github.com/digitalBush/jquery.maskedinput
It isn't maintained anymore, but I found it a bit more powerful.

These days though I use Cleave.JS, it doesn't support the fine-grain that others have, but it does what I want and has support for libphonenumber.
