### ISSUE TITLE
Doesn't erase letters on html5 number inputs

### ISSUE THREAD

**Issue by salase** [igorescobar/jQuery-Mask-Plugin#201]
On html5 i'm using a number type input but the mask doesn't erase the letters I type.
On the same page a text type input works fine.

**Comment by Hacktivista** [comment]
I agree, if the idea is to make your software for everybody you would be able to make it the most bullet proof (as in difficult to get wrong) possible.

**Comment by igorescobar** [comment]
Only the DEVICE controls type="number" fields. There is nothing I can do about it...

**Comment by Hacktivista** [comment]
I did add it as a bug on bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1194812
