### ISSUE TITLE
set mask in html attribute data-mask="" is not working

### ISSUE THREAD

**Issue by sergeymakoveev** [igorescobar/jQuery-Mask-Plugin#230]

**Comment by Hamlet-Tamaz** [comment]
hey @igorescobar !
first off, thanks for the great plugin. I'm also currently facing this issue. I am able to fully use the JS notation as intended. I believe what you confirmed in this thread is that the HTML notation should work without any JS; just importing the 'jquery.mask.min' file is enough. That doesn't work for me. I have my file loaded at the end as you've suggested.
However, when using the HTML notation, nothing happens. I'm unable to set a mask on any kind of element. To clarify, does this feature work on any element? I've tried on input, div, label. Currently, the html (actually .cfm file for ColdFusion) looks like this (note that I've switched the 0 and 9 in the translation option):

<input data-mask="999-999-9999" type="text" value='#rc.clientInfo.getArrayOfOrganizationBranch()[1].getPhoneNumber()#'>

**Comment by ruicaramalho** [comment]
Solution to work is calling this script after document is loaded:

    $('[data-mask]').each(function() {
        $(this).mask($(this).attr("data-mask"));
    });

**Comment by luancardosolc** [comment]
Tks ruicaramalho, works fine this way.

**Comment by igorescobar** [comment]
@Hamlet-Tamaz I provided a working jsfiddle at the beginning of the thread (https://github.com/igorescobar/jQuery-Mask-Plugin/issues/230#issuecomment-61345468). As I said. You need to load jQuery Mask AFTER your HTML definitions. Even after doing that it still doesn't work?

**Comment by JoshuaNovak919** [comment]
You can just run `$(function(){ $.applyDataMask(); });` instead. It's cleaner.

**Comment by AAGJKPRT** [comment]
Hi @igorescobar 

I am using the same plugin with a bit older version, I am stuck with two partial views and masking.
Tried to explain my issue on the link: 

_https://stackoverflow.com/questions/56965428/mask-not-working-in-jquery-with-two-partial-views-in-mvc_ 
Please get back to me on this, thanks
