### ISSUE TITLE
Implemet ability to show mask on focus

### ISSUE THREAD

**Issue by Areks** [igorescobar/jQuery-Mask-Plugin#238]
Will be perfect if you can add ability to show mask when i set focus on field. See example  http://digitalbush.com/projects/masked-input-plugin/#demo  set focus in any field and see result, plugin set mask in input value and i can see what i should type.

**Comment by vbarinov** [comment]
@Areks you can use this snippet:
```html
<input class="phonemask" placeholder="Enter your phone number" data-placeholder="+7 (xxx) xxx-xx-xx"/>
```

```js
$('.phonemask')
        .mask('+7 (000) 000-00-00')
        .on('focus', function(e) {
            var p = $(this);
            p.data('orig-placeholder', p.attr('placeholder'));
            p.attr('placeholder', p.data('placeholder'));
        })
        .on('blur', function(e) {
            var p = $(this);
            p.attr('placeholder', p.data('orig-placeholder'));
        });
```

**Comment by JulianoSch** [comment]
@Areks try modify the source like this.

At line 124, after .on("focusout.mask"
Add this:

![image](https://cloud.githubusercontent.com/assets/20827822/17386922/579cca1c-59c5-11e6-88ae-00b07b1b362a.png)
> .on("focus", function () {
                    if (options.placeholderOnFocus && options.placeholder) {
                        el.attr('placeholder', options.placeholder);
                    }
                })
                .on("blur", function () {
                    if (options.placeholderOnFocus && options.placeholder) {
                        el.attr('placeholder', '');
                    }
                });

At line 355
![image](https://cloud.githubusercontent.com/assets/20827822/17386943/7c764d4a-59c5-11e6-8f75-281cded94713.png)

> if (!options.placeholderOnFocus && options.placeholder) {
                    el.attr('placeholder' , options.placeholder);
                }

To use:

> $('.time').mask('99:99', { placeholder: '__:__', placeholderOnFocus: true });

Hope this help.

**Comment by martea** [comment]
@JulianoSch you should make this a merge requesst, thou dont forget to trigger blur on init, other wise nice implementation =)
