### ISSUE TITLE
Call mask without an element

### ISSUE THREAD

**Issue by dmregister** [igorescobar/jQuery-Mask-Plugin#241]
I am using your plugin within an angular filter. I would like to use it directly and just get the output without binding it to an element e.g. 

`var formattedTest = jQuery.fn.mask('(000) 000-0000', inputText);`

I am not sure this is possible or if I am missing something.

Thanks.

**Comment by settysreekanth** [comment]
This is just for information, I happened to do it in the following way.. 
element.val(some_numbers).mask('AAA-AAA');

PS: In this case element was input type.
