### ISSUE TITLE
back button and autocomplete

### ISSUE THREAD

**Issue by arnaldocan** [igorescobar/jQuery-Mask-Plugin#244]
When I press the brower back buttom to return to a page with masked inputs, all the mask inputs loose their changed values.

Analyzing the code, the problem seems to occur on line 352 ("el.attr('autocomplete', 'off');").

Is it possible to preserve inputs values when the user returns to a page with masked inputs?

Alternativally, can I comment the line 352 in the code? Would that lead to severe side effects on the plugin behaviour?

**Comment by igorescobar** [comment]
To those who wants to turn the auto complete on, please read:
https://github.com/igorescobar/jQuery-Mask-Plugin/blob/master/src/jquery.mask.js#L360

To activate just:
```javascript
$.jMaskGlobals.autocomplete = 'on';
```

**Comment by arnaldocan** [comment]
Thanks!

2015-07-07 11:31 GMT-03:00 Igor Escobar <notifications@github.com>:

**Comment by igorescobar** [comment]
I've subbmited another version that features a new approach:
- the user decides, autocomplete or not.
- if ON, jquery mask only will disable it of the browser doesn't support on input event.

autocomplete global option isn't supported it's up to the developer what to do.

**Comment by kovalwaffe** [comment]
How I can change globally value of atribute 'autocomplete' ?
I don't want to change original library jquery.mask.js

> * the user decides, autocomplete or not.
