### ISSUE TITLE
Select issue when copying

### ISSUE THREAD

**Issue by BernardoLima** [igorescobar/jQuery-Mask-Plugin#246]
Igor, I've talked about this before, but I think I didn't explain it well.
Here's what's happening with selection:
http://i.gyazo.com/0b0a9aedf8d928ea0df85e1a51f41a3b.gif

When I press control+A, it selects all the text fine.
When I press control+C, it copies the text fine, but removes the selection.

I'm using Windows 7, have tested on 32bits and 64bits, and my browser is Chrome latest version.

Would that be a uncommon behavior?

**Comment by igorescobar** [comment]
@BernardoLima sorry but I just couldn't reproduce what you're experiencing.

**Comment by BernardoLima** [comment]
O texto deseleciona depois que a cópia é realizada, aí não acontece isso?
Quando copio com o botão direito fica normal, só no control+c que acontece mesmo, mas isso não gera problema.

**Comment by igorescobar** [comment]
Não acontece :/
