### ISSUE TITLE
Number mask doesn't work as expected with input type = "number"

### ISSUE THREAD

**Issue by leebrooks0** [igorescobar/jQuery-Mask-Plugin#25]
I have a field for a South African postal code (4 digits), and my mask looks like 
this $('.postal-code').mask('0000');

If the type of the input is text, it works as expected, if the type is "number" then any text entered removes all the text in the textbox (including the valid parts) i.e 333 and then 'f' will clear the textbox out. 

I want to use type = "number" because I am making a mobile web app, and want the on screen keyboard to display numbers.

**Comment by lijo007** [comment]
@bludream : Great Your Suggetion works for me.. What i need to impliment  was masking field for Phone No & Date and to show number keypad.It works fine .. Thanks again

**Comment by AmaliDeveloper** [comment]
Hey you can get the solution for this problem here Good Work [Link](https://youtu.be/dV3s7s_8fnE)
