### ISSUE TITLE
Reaplicando a mascará anterior sozinho

### ISSUE THREAD

**Issue by dunebuddy** [igorescobar/jQuery-Mask-Plugin#250]
Eu estou tentando aplicar uma máscara condicional, mas quando insiro o ultimo dígito ele aplica a máscara do cnpj e então volta a máscara do cpf.

http://jsfiddle.net/znuph72f/1/

Estou fazendo algo errado?

**Comment by gabrielverao** [comment]
Bom dia,

estou com problemas em colar um CNPJ sem formatação. Ele fica com a mascara de CPF, mesmo sendo um numero CNPJ

no exemplo > http://jsfiddle.net/znuph72f/3/

desculpe se o problema ja foi resolvido.

**Comment by kafeltz** [comment]
@gabrielverao tu colocou 000.000.000-000 ao invés de 000.000.000-009

**Comment by pedromcorreia** [comment]
Ola, alguma atualizacao da funcionalidade para copy and paste?
