### ISSUE TITLE
Manullay entering comma in number mask

### ISSUE THREAD

**Issue by afattahi54** [igorescobar/jQuery-Mask-Plugin#252]
In the sample page http://igorescobar.github.io/jQuery-Mask-Plugin/ consider the money mask.

1-User wants to have enter "12,34" value
2-He click on input and hit these keys: "1"-"2"-","-"3"-"4"
When pressing the "," the mask removes the "," and when pressing "3" the mask automatically add the "," before it.
This may confuse the user !
Is it possible that we configure the plugin so that is allow user to manually enter "," in "#.##0,00"  mask ?!

Regards

**Comment by afattahi54** [comment]
This seems to be what I am looking for, I tried but it did not worked:
http://jsfiddle.net/o1mdjmdv/

**Comment by igorescobar** [comment]
Have you consider disabling the "reverse" option?

**Comment by afattahi54** [comment]
I have tested that see http://jsfiddle.net/o1mdjmdv/9/
You can not enter "12.35" in the input

**Comment by igorescobar** [comment]
Can you achieve what you want in any other plugin? Can you show me?

**Comment by afattahi54** [comment]
Sorry for late reply !
Please see http://robinherbots.github.io/jquery.inputmask/ 
Please examine the Decimal input, you can manually enter '.' (as RadixPoint)  but not the ','( as Group separator) 
This seems a logical behavior for user. Consider a user who wants to enter '1234.56' he press
'1'   '2'  '3'  '4' (The input adds a ',' ) now he enters '.' (system accept it) user enters '5' and finally '6'

**Comment by igorescobar** [comment]
@afattahi54 sorry but we don't support this kind of functionality. I recommend you to use a plugin to solve specific currency problems.

**Comment by vinicius83** [comment]
Use "optional" like this

$('.mask-taxa2-2').mask('ZZ,00', { translation: { 'Z': { pattern: /[0-9]/, optional: true }}});


I add to my mask a blur function to fix zeros to the right ;)  

$('.mask-taxa2-2').mask('ZZ,00', { selectOnFocus: true, translation: { 'Z': { pattern: /[0-9]/, optional: true }}}).blur(function() { this.value = (parseFloat(this.value.replace(',', '.')).toFixed(2)).replace('.', ',');});
