### ISSUE TITLE
Error on IE7

### ISSUE THREAD

**Issue by leandrocervelin** [igorescobar/jQuery-Mask-Plugin#253]
Good morning, all right?

First I want to congratulate to all involved in this project for the excellent job done!

It's happening a bug when using the plugin with IE 7.

The error occurs on line 151:
     maskChunks.push (mask [i] .replace (/ [- \ / \\ * ^ $ ?. + () | [\] {}] / g '\\ $ &'));

     example: mask [0] is undefined.

Maybe something like the code below solve the problem
     maskChunks.push(mask.charAt(i).replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&'));

I did a screen shot and I have attached here.

![error ie7](https://cloud.githubusercontent.com/assets/229497/5613680/6035d004-94cf-11e4-88bb-5526299fcccb.JPG)

thank you!

**Comment by igorescobar** [comment]
This was fixed in our master branch... can you test it?

**Comment by leandrocervelin** [comment]
Yes, it has been tested. The fix is ok!
