### ISSUE TITLE
Changing mask on the fly

### ISSUE THREAD

**Issue by cezarcruz** [igorescobar/jQuery-Mask-Plugin#255]
Hello Igor, 
Here is my problem: http://jsfiddle.net/cezarcruz/3qpLxyxa/3/

En: My mask needs to be replaced in typing time, however, when this occurs, the field loses some digits. That's a problem in my code? or plugin? Thank U.

Br: Minha mascara precisa ser trocada em tempo de digitação, porem, quando isso ocorre, o campo perde alguns digitos. Isso é um problema no meu código? ou no plugin? Obrigado.

**Comment by igorescobar** [comment]
I think you lost something in our docs... The digit 9 means that this digit is optional... All digits of your mask is optional?

Replace those 9's by 0.

Use jquery mask's callbacks instead of using your own. Read our docs and you should be fine.
