### ISSUE TITLE
Get the current validity status of a input mask

### ISSUE THREAD

**Issue by ccortezia** [igorescobar/jQuery-Mask-Plugin#257]
Is there a way to achieve this ? I mean, outside the 'onComplete' callback I would like to find out if the masked input has a valid value. 

Just to let you know, my intention here is to make a really simple integration on angularjs, using a directive. Please, let me know if any good quality angular integration have been done already.

Thanks, and keep up the good work.

**Comment by igorescobar** [comment]
May this pull request help you?
https://github.com/igorescobar/jQuery-Mask-Plugin/pull/243

**Comment by ccortezia** [comment]
I am not really sure. What I really need is a way to query the validity status of the masked input. The mentioned PR did not add such a public method. Instead it added another public callback (at least as far as I could understand from reading the changed source files).

**Comment by igorescobar** [comment]
I see... well... in that case... you have to understand that "validation features" is not our main goal here so if you need more advanced features around that subject you should use a validation plugin like formvalidation.io along with jQuery Mask Plugin.

The best we can offer right now is a public callback to notify about invalid typing inside a specific field.
