### ISSUE TITLE
Masking does not work properly on Samsung Devices with stock keyboard

### ISSUE THREAD

**Issue by kashban** [igorescobar/jQuery-Mask-Plugin#258]
We just came across this issue where masked input fields act weird with the Samsung Stock Keyboard.

By using currency masking ($('.waehrung').mask("#.##0 €", {reverse: true});) we want to format currency amounts. This works great on all devices but Samsung with stock keyboard. Here when adding more than four digits the whole string is doubled. When adding more digits it goes back to normal.

We found that disabling the "Predictive Text" functionality in the keyboard's settings fixes the issue. Using a third party keyboard like SwiftKey does too.

If that can be fixed without user interaction that would help a great deal.

**Comment by igorescobar** [comment]
I appreciate your report @kashban but here is the problem... I don't have a Samsung Stock Keyboard to reproduce what you're facing so I can't do much for you at this point.

We have two options here:
1 - Can you tell me how to reproduce it without Samsung Stock Keyboard?
2 - By submitting a PR with the fix.

Can you thought in any other solution?

**Comment by kashban** [comment]
Thanks for the quick reply, Igor. 

I reported this issue mainly to let others know the cause of this problem and possible workarounds. 

You cannot reproduce this without a Samsung device and it's stock keyboard. However, others will stumble across this for sure, so I think it's a good idea to have it mentioned here. 

I have no idea how to fix this with Javascript. Perhaps it cannot be fixed. So if you feel more confident with this issue closed you could close it as "won't fix". But the information will be still here for others to find.

**Comment by igorescobar** [comment]
Sure @kashban !

Thank you for your time!
