### ISSUE TITLE
Irregular spacing on digit-only masks

### ISSUE THREAD

**Issue by pm47** [igorescobar/jQuery-Mask-Plugin#260]
Hello,
I noticed that when using a simple digit-only mask, digits display with an irregular spacing.

Eg with: 
```javascript
$('#id').mask('00000');
```
44444 will display 4444 4 (this is exaggerated)

I am using version 1.11.2

**Comment by igorescobar** [comment]
@pm47 a jsfiddle please?

**Comment by pm47** [comment]
Hi igor,

Apologies, this is in fact related to my using of letter-spacing css attribute.

Keep up the good work !

**Comment by igorescobar** [comment]
Glad to hear it ;-)
