### ISSUE TITLE
Setting values programmaticly after initiating the mask

### ISSUE THREAD

**Issue by toddaa** [igorescobar/jQuery-Mask-Plugin#261]
So I have the mask working when the text box is being typed into.  I need to set the initial value of the box.  Link to example is below:

http://jsfiddle.net/6pco4om7/32/

The results are that the value is set, but the mask is no longer applied until the boxes is typed into.  Is there a good way to refresh the box with the mask after a value has been set?

Thanks!

**Comment by igorescobar** [comment]
Have you looked into our global options?

[]'s
Igor

**Comment by toddaa** [comment]
Yes, I attempt to use them, but it didn't seem to make a difference for me.
I'll give it a go again just to be sure as I did see the watchInterval in
there. Should I be able to apply them to the code in the JSFIDDLE and see
it work?

**Comment by toddaa** [comment]
Igor,

Just attempted with global options and cant seem to make it work.  Can you provide an example for me?  

Thanks!

**Comment by igorescobar** [comment]
@toddaa Everytime you change the value pragmatically you need to call an event like:

```javascript
$('#phone-field').val("5555555555").trigger('keyup');
```

**Comment by toddaa** [comment]
That did the trick.  I apologize...I totally forgot about the trigger function.

Thanks again!

**Comment by kaleucaminha** [comment]
Hello, I checked that "keyup()" not working in larger versions to 1.13.4.

In this jsfiddle, I show that keyup() is not working in the last version
http://jsfiddle.net/kaleu/o6botgm1/1/

In this jsfiddle, I put 1.13.4 version and the same code works:
http://jsfiddle.net/kaleu/pwvtfhuk/1/

And, at last, in this jsfiddle, I put 1.13.5 version code and the keyup function stoped of working
http://jsfiddle.net/kaleu/sa3hn8jh/1/

I couldn't fixed it, sorry

**Comment by kaleucaminha** [comment]
@igorescobar we should reopen this issue?

**Comment by luisfmsouza** [comment]
I agree with @kaleucaminha ! Can we reopen it @igorescobar ?

**Comment by mikila85** [comment]
RE OPEN PLZZZZZ

**Comment by mikila85** [comment]
so how to refresh now?

**Comment by F1nZeR** [comment]
@mikila85 you can use `.trigger('input');`

**Comment by mikila85** [comment]
Thx :)

**Comment by kafeltz** [comment]
Solução estilo `jeitinho brasileiro`.

**Comment by gilbarbara** [comment]
The only to update the mask after changing its value being `.trigger('input')` is a bit weird.
¯\_(ツ)_/¯

**Comment by igorescobar** [comment]
Guys,

It's pretty simple. The reason why you need to trigger the event yourself is because:

1 -  sometimes you use this plugin along with others and this can lead to unexpected behaviors. 

2 - when you decide to change the value of the field yourself no event is fired is there is no way practical way for the plugin to know that the value has changed so I would basically need to monitor the field all the time which sucks.

So it's simple as that. If you managed to change the value yourself you need to do the dirty work for the browser because NO EVENT is triggered.

But hey, for those who think that we are playing around and this is just a "jeitinho brasileiro"

**Comment by mikila85** [comment]
I think a simple reloadOptions() function would solve this elegantly.

**Comment by gilbarbara** [comment]
Hey @igorescobar 
But why not transform the value with `change` or `keypress` events instead of just `input`?
After all there are listeners for those events..

**Comment by crincones** [comment]
I'm a newbie but managed to do this:

$('#whatever').val($('#whatever').masked('123456789'));

no need to trigger anything.

Thanks for the plugin btw.

**Comment by Atmiya735** [comment]
https://jsfiddle.net/atmiya/uy85fnt8/1/

**Comment by mikila85** [comment]
@Atmiya735 , the title say: "Setting values programmaticly after initiating the mask"
this is your jsfiddle preinitialized: [https://jsfiddle.net/uy85fnt8/3/](https://jsfiddle.net/uy85fnt8/3/)

**Comment by eddyoliveiram** [comment]
I used to have the same problem, this worked for me:  **$("#field_ID").val('any_value').mask('000.000.000-00');**

**Comment by thetanriverdi** [comment]
Hi

functions such as keyup and trigger do not work.
but, you can use it this way.

Running sample:
```
$('#account_gsm').val('5351234567);
$('#account_gsm').mask('Z(500) 000 0000')
```
