### ISSUE TITLE
 data-mask attribute don't work

### ISSUE THREAD

**Issue by maksir** [igorescobar/jQuery-Mask-Plugin#262]
data-mask attribute don't work.

filter(globals.dataMaskAttr) in function raise error
 $.applyDataMask = function() {
 	$(document).find($.jMaskGlobals.maskElements).filter(globals.dataMaskAttr).each(HTMLAttributes);
    }

i replace that to  filter($.jMaskGlobals.dataMaskAttr)

    $.applyDataMask = function() {
    	$(document).find($.jMaskGlobals.maskElements).filter($.jMaskGlobals.dataMaskAttr).each(HTMLAttributes);
    }

but does not work anyway

**Comment by igorescobar** [comment]
@maksir I'm waiting for your jsfiddle :)

**Comment by igorescobar** [comment]
You can see data-mask in action right here:
http://jsfiddle.net/igorescobar/x2mhx0Ld/

**Comment by igorescobar** [comment]
Also in our home page.
