### ISSUE TITLE
Mozilla firefox for android

### ISSUE THREAD

**Issue by devjoseluis** [igorescobar/jQuery-Mask-Plugin#263]
Hello, this is my jsfiddle http://jsfiddle.net/3t6t5p44/1/

**Comment by igorescobar** [comment]
What is your issue?

**Comment by iudelsmann** [comment]
There seems to be an issue with Firefox for android. When adding a caracter for the mask, like "-" on a phone, the cursor moves back. The jsfiddle provided originally shows the error, if you type from 1 to 8 (in order) you'll end up having 1234-6785 as the cursor moves back after you type the "5".

**Comment by Jokerwolf** [comment]
Issue is still there. Firefox(42.0.1) on Samsung Galaxy S5 Android (5.0).
