### ISSUE TITLE
selectOnFocus

### ISSUE THREAD

**Issue by feliperamone** [igorescobar/jQuery-Mask-Plugin#266]
Primeiramente gostaria de agradecer por este excelente plug-in, você realmente fez um trabalho genial.

No selectOnFocus acontece o seguinte problema, quando o campo ganha o foco a primeira vez ele seleciona tudo corretamente, porem ao perder o foco e dar foco novamente a seleção não pega.

Caso tenha como corrigir ficaria bacana.

**Comment by igorescobar** [comment]
@feliperamone obrigado pelos elogios ;)

Qual browser você está usando e sistema operacional?

**Comment by igorescobar** [comment]
Fiz alguns testes e está tudo funcionando normal... Me envie mais informações para que eu possa investigar.

**Comment by feliperamone** [comment]
Firefox, sistema Windows 7. O problema ocorre quando saio do campo para outro, e voltou para ele (com o clique do mouse). No primeiro focus vai ok já no segundo acontece isso de não selecionar o campo. Att.

**Comment by igorescobar** [comment]
Bem estranho, aqui isso não acontece. 
Eu não tenho um Windows para testar isso, se você conseguir descobrir qual é o problema, me envia um PR. Vou tentar arrumar um Windows.

**Comment by igorescobar** [comment]
Hum... parece que é alguma coisa no Firefox. No Chrome não acontece... Vou tentar descobrir o que pode ser.

**Comment by feliperamone** [comment]
combinado, caso ache o erro aviso sim. No chrome funciona 100% e algo que dá no firefox msm.

Att.

**Comment by gunnx** [comment]
@igorescobar I've noticed this on Chrome (v44) too. First time you click the input it highlights, if you then blur then re-focus it won't select the contents but repeat again and it will.
