### ISSUE TITLE
Support for data-mask-placeholder

### ISSUE THREAD

**Issue by zener05** [igorescobar/jQuery-Mask-Plugin#267]
It would be great to support placeholder via HTML5 data attribute. I tried something like
```html
<input type="text" name="foo" data-mask="09.09.0000" data-mask-placeholder="__.__.____">
```
But it doesn't work...

**Comment by igorescobar** [comment]
That is because you can do this with html5 placeholder attribute. It would be redundant.

[]'s
Igor
