### ISSUE TITLE
On DOM change / onClearIfNotMatch

### ISSUE THREAD

**Issue by khayr** [igorescobar/jQuery-Mask-Plugin#269]
I would like a slightly different behavior of callbacks. Now onChange triggered after each keystroke as onKeyPress. Need to do so that it works only after losing focus. Otherwise, if clearIfNotMatch: true and the field is not completely filled, if we lose focus, the field is cleared, but standard DOM change (jquery-onchange) handler does not fire. And I have to check whether the field is not empty, to close the form to fill if empty. Alternatively, you can add a callback such as onClearIfNotMatch.

**Comment by igorescobar** [comment]
If the onChange plugin callback doesn't fit your needs, can you fallback to the "original" change event?
