### ISSUE TITLE
Optional Digits with "reverse:true" don`t work

### ISSUE THREAD

**Issue by pedroAquino** [igorescobar/jQuery-Mask-Plugin#270]
my code:

$('#Value').mask('Z 000.000.000.000.000,00',  { reverse:true, 
translation:  {'Z': {pattern: '[a-zA-Z._^%$#!~@,-]+', optional: true}}});

I`m trying to make a money textbox that accepts negative numbers.
Obs: Regex could be better, sorry...

**Comment by igorescobar** [comment]
Use a currency plugin. That is my advice for you ;)

[]'s
Igor
