### ISSUE TITLE
Support for JQuery 1.9 or greater and JQuery 2.x

### ISSUE THREAD

**Issue by salemanager** [igorescobar/jQuery-Mask-Plugin#271]
JQuery-Mask-Plugin is using deprecated API calls. Deprecated API calls introduced in JQuery version 1.9 or greater.  JQuery-Mask-Plugin should be tested with the latest JQuery versions: 1.11.2 and 2.1.3

Generates compile errors when using PhoneGap.

**Comment by igorescobar** [comment]
@salemanager what about a PR?
