### ISSUE TITLE
Callback on notmatch

### ISSUE THREAD

**Issue by jwbaart** [igorescobar/jQuery-Mask-Plugin#276]
Is it possible to have a callback if input doesn't match the pattern? This functionality is used in clearifnotmatch. This would be used with an error class to indicate an error to the user

**Comment by igorescobar** [comment]
There is the onInvalid callback. Did you read the docs?

**Comment by jwbaart** [comment]
onInvalid reacts on each incorrect keypress. When the user moves out of focus on the input field I would like to check if the whole pattern matches.
Example: $('#date-field').mask("00/00/0000") (from the docs ;) )
                '22/0' vs '22/02/2222'

'22/0' doesn't trigger onInvalid but isn't a correct date.

**Comment by igorescobar** [comment]
Currently, this is not possible, sorry.

**Comment by igorescobar** [comment]
By the way... if you want a more "precise" onInvalid Callback you need you specify you "translation" object in order to get a more accurate validation.

**Comment by igorescobar** [comment]
Also... if you want to "transform" jquery mask into a validation plugin, I really don't recommend that.... This is not our main goal so we are never going to fulfill all the features and possibilities of the "validation" concern.

**Comment by jwbaart** [comment]
K, thanks!
