### ISSUE TITLE
Máscara no padrão protocolo

### ISSUE THREAD

**Issue by tuliodemelo** [igorescobar/jQuery-Mask-Plugin#277]
Olá, preciso de uma máscara no padrão de um número de protocolo, por exemplo, 02455789-9 porém o número de caracteres à esquerda não é fixo e o traço opcional. Ou seja, eu queria uma máscara somente números com a possibilidade de um - apenas

Da seguinte forma funcionou mas não é bem o que preciso. Se eu coloco uma expressão regular válida como essa [0-9]*\-{1}[0-9]{1} no plugin ele não aceita. Enfim...como posso fazer?

$('#protocol').mask('0#', {maxlength:false, translation : { '0' : { pattern: [0-9\-] } } });

**Comment by igorescobar** [comment]
E se você usar a mascara: ```099999999999999999999-0```.

Na sua expressão regular você não está falando que - é opcional, você está dizendo que ele vai acontecer em algum momento após um [0-9]. Será seguido de outro númeral no final.

Segue o mesmo exemplo de uma mascara de números de IP:
```javascript
$('.ip_address').mask('099.099.099.099');
```

O primeiro zero é obrigatório, porém o 2 seguintes são opcionais, então, se eu digitar um ponto a qualquer momento ele aceite, desde que o numero seguinte seja um numeral.

Acredito que a primeira mascara funciona, a que te passei, porém, você precisa ajustar a quantidade de digitos opcionais após o zero até o traço ```-```.

Sempre que tiver dúvidas, mande um jsfiddle exemplificando seu caso de uso, fica mais fácil para eu te ajudar.

**Comment by igorescobar** [comment]
@tuliodemelo does it helped you or not?
