### ISSUE TITLE
Correção do key + tab

### ISSUE THREAD

**Issue by danilomagalhaes** [igorescobar/jQuery-Mask-Plugin#279]
Olá,

Recentemente precisei usar esta api e me deparei com um bug, ao pressionar qualquer tecla + tab a Mascara não é aplicada no campo, dando uma olhada no código consegui resolver apenas alterando a linha .on('keyup.mask', p.behaviour) para .on('keyup.mask blur.mask', p.behaviour) em **"p.events"**.
Não sei se esta alteração terá efeitos negativos em algum momento da api, mas resolveu meu problema e não detectei nenhum comportamento inesperado.

Obrigado pela api e espero ter ajudado.

**Comment by igorescobar** [comment]
Danilo,
Manda um PR para gente, pode ser?

[]'s
Igor

**Comment by igorescobar** [comment]
@danilomagalhaes ?
