### ISSUE TITLE
Erro jquery.mask.js com AngularJS

### ISSUE THREAD

**Issue by fhmoralles** [igorescobar/jQuery-Mask-Plugin#280]
Segue trace do console:

Uncaught TypeError: undefined is not a function
gb.attr jquery.min.js:2
gb.selectors.filter.ATTR jquery.min.js:2
d  jquery.min.js:2
f  jquery.min.js:2
gb.select jquery.min.js:2
gb  jquery.min.js:2
n.event.handlers jquery.min.js:3
n.event.dispatch  jquery.min.js:3
n.event.add.r.handle jquery.min.js:3
replaceWith angular.js:8171

**Comment by igorescobar** [comment]
Fico no aguardo do seu jsfiddle.

[]'s
Igor

**Comment by igorescobar** [comment]
Hello?

**Comment by fhmoralles** [comment]
Estou meio ocupado.

Vou gerar o jsfiddle e compartilho.

[]'s,
Fernando H. Moralles


*- Procure ser uma pessoa de valor, em vez de uma pessoa de sucesso. -**[
P  E  N  S  E  ]*


2015-03-19 10:23 GMT-03:00 Igor Escobar <notifications@github.com>:

**Comment by brunowego** [comment]
+1

**Comment by igorescobar** [comment]
Still waiting a jsfiddle...
