### ISSUE TITLE
bug android 

### ISSUE THREAD

**Issue by clezeraragon** [igorescobar/jQuery-Mask-Plugin#283]
percebi que o problema era na hora de corrigir o texto ele o android 4.2 utilizava o mecânismo de autocomplete ai dava erro e embaralhava tudo, a solução foi utilizar  nos inputs ( autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" )
ai deu certo.

**Comment by igorescobar** [comment]
@clezeraragon mantenha a discussão na mesma thread, a casa mensagem sua você está criando uma issue nova. Já existe uma issue sobre esse assunto: #135 

Você consegue validar isso em uma versão mais antiga do Android?
