### ISSUE TITLE
Action/events on invalid input?

### ISSUE THREAD

**Issue by gdalam** [igorescobar/jQuery-Mask-Plugin#287]
I'm pretty new to Javascript, so I couldn't quite figure this out just by looking at the code myself. Could you point me in the direction of where I would add actions that are triggered by invalid input? I'd like to add a red flash whenever an invalid key is pressed in the input.

**Comment by igorescobar** [comment]
You don't need to change the source code for that. Just use those callbacks as you wish:

```javascript
var options =  { 
  onComplete: function(cep) {
    alert('CEP Completed!:' + cep);
  },
  onKeyPress: function(cep, event, currentField, options){
    console.log('An key was pressed!:', cep, ' event: ', event, 
                'currentField: ', currentField, ' options: ', options);
  },
  onChange: function(cep){
    console.log('cep changed! ', cep);
  },
  onInvalid: function(val, e, f, invalid, options){
    var error = invalid[0];
    console.log ("Digit: ", error.v, " is invalid for the position: ", error.p, ". We expect something like: ", error.e);
  }
};

$('.cep_with_callback').mask('00000-000', options);
```

More info, read the docs: http://igorescobar.github.io/jQuery-Mask-Plugin/
