### ISSUE TITLE
For Fractions of second not allowed character are displayed.

### ISSUE THREAD

**Issue by AshishkumarBhatt** [igorescobar/jQuery-Mask-Plugin#289]
I have implemented following mask,

$('#InvoiceNumber').mask('0#', { maxlength: false });

But here when we type alpha character in that field, for fraction of seconds it can be seen. So we actually want to restrict that.

So can you please look into this?

**Comment by igorescobar** [comment]
Where is your jsfiddle?

**Comment by AshishkumarBhatt** [comment]
Here it is
http://jsfiddle.net/AJBhatt/L9v70skj/4/

**Comment by igorescobar** [comment]
I couldn't reproduce what you're experiencing... Only digits accepted here... (Google Chrome, Mac)

**Comment by AshishkumarBhatt** [comment]
1. Open http://jsfiddle.net/AJBhatt/L9v70skj/4/ this in IE, Firefox
2. In this example there is one textbox - which suppose to take digit
3. Now type "abc" inside that, you will see like "abc" is getting typed and then it is removed in fraction.

So it seems like mask validation is working on "KeyRelease" so can you please restrict that to "KeyPress".

**Comment by igorescobar** [comment]
@AshishkumarBhatt Now I understood what you meant... Unfortunately this is how jQuery Mark Plugin works, you can't change that, sorry.
