### ISSUE TITLE
Is there a way to always display the watermark if the input text is empty

### ISSUE THREAD

**Issue by rkodur2** [igorescobar/jQuery-Mask-Plugin#293]
I'm trying to apply date mask on asp.net text field. mask works fine but we would like to always display the watermark mm/dd/yyyy if the text field is empty.Is there a way to enable watermark or clear mask on lost focus

jQuery(function($){
            $("#txtPB1DtFormed").mask("99/99/9999", { placeholder: "mm/dd/yyyy" }  });

**Comment by igorescobar** [comment]
Sorry but no. This is just the original HTML5 placeholder so you can't change that.
