### ISSUE TITLE
Problema com jquery mask no windows phone

### ISSUE THREAD

**Issue by JonathasRodrigues** [igorescobar/jQuery-Mask-Plugin#297]
Olá,

estou usando jquery, jquery-mobile  e quando estou usando o plugin jquery-mask estou tendo problemas no windows phone em telas com o component popup do jquery mobile.

jquery-2.1.1.min.js
jquery.mask-1.7.7.js
jquery.mobile-1.4.4.min.js

Erro: Object doesn't support property or method 'getAttribute'

Analisando o que poderia ser, realizei alguns testes e percebi que retirando o jquery-mask a tela é carregada normalmente, e que quando estou utilizando o mask não posso ter nenhum comentário no html, e no jquery-mobile ao construir uma popup é gerado da seguinte maneira.

    <div style="display: none;" id="popup-placeholder"></div>

Analisando a função do jquery chamada Sizzle.attr que esta gerando o erro, percebi que é passado para ela um objeto do tipo comment DOM onde não contém a função getAttribute (mas somente no windows phone e algumas versões do I.E.).

Segue jssfidle 
http://jsfiddle.net/ddztrehg/4/

OBS: não conseguir reproduzir no jssfidle, para simulação terá que ser criado um arquivo html com as referencias das bibliotecas e abrir no o I.E. 
![2015-05-06_15h04_18](https://cloud.githubusercontent.com/assets/8070431/7499979/39548318-f401-11e4-87c4-7ffeabe77c3e.png)

Alguem poderia me ajudar?

Qualquer dúvida estou a disposição.

Obrigado.

**Comment by igorescobar** [comment]
@JonathasRodrigues Me parece um problema do jQuery, não? Eu nem uso esse método no plugin.

**Comment by igorescobar** [comment]
Talvez se você voltar para a versão 1.11.x do jQuery e não a 2.x resolva. a 2.x ela é focada em browsers novos, talvez este seja o problema.

**Comment by JonathasRodrigues** [comment]
@igorescobar fiz o teste com o jquery 1.11.X e funcionou normalmente.

Obrigado.
