### ISSUE TITLE
Ao enviar as informações via post alguns dados dos campos com a mask não são enviados

### ISSUE THREAD

**Issue by dougjuliao** [igorescobar/jQuery-Mask-Plugin#298]
Ola!
Função mask para telefone com o nono digito.

Eu estou com um pequeno problema com o plugin e gostaria de saber se você ja se deparou com esse problema.
Qunao eu adiciono o telefone com o nono digito na ordem correta as informações são enviadas normalmente, mas quando eu uso tab para trsansição entre os campos ou digito e apago o conteúdo do input, os dados não são enviado quando clico no botão de post, no meu network do google chrome mostra que os dados estão vindo vazios, a função que estou usando é essa:

function maskFoneRequired(container, options){     
    var SPMaskBehavior = function (val) {
      return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
    },
    spOptions = {
      onKeyPress: function(val, e, field, options) {
          field.mask(SPMaskBehavior.apply({}, arguments), options);
        }
    };

    var ifone = $('<input required class="k-input k-textbox fone" data-bind="value:' + options.field + '" />').appendTo(container);
    ifone.mask(SPMaskBehavior, spOptions);

    container.find('input').attr("maxlength", 15);
}

///////
A e eu estou usando o kendoui, será que vocÊ poderia me ajudar com isso?
Att.

**Comment by igorescobar** [comment]
@dougjuliao leia o readme. fico no aguardo do seu jsfiddle.

**Comment by dougjuliao** [comment]
Ok como está correria aqui, irei fazendo outras atividades, mas tentarei postr la no jsfiddle essa noite, obrigado!
