### ISSUE TITLE
allow hexadecimal masks

### ISSUE THREAD

**Issue by hoeni** [igorescobar/jQuery-Mask-Plugin#30]
It would be great to have a placeholder for hexadecimal input, enabling input for mac addresses for example:

FF:FF:FF:FF:FF:FF

It would be helpful to normalize this to either caps (F) or normal letters (f), depending on the placeholder.

**Comment by brunowego** [comment]
My solution for hex color:

```js
$('.hexcolor').mask('SAAAAAA', {
	'translation': {
		S: {
			pattern: /[#]/
		},
		A: {
			pattern: /[A-Fa-f0-9]/
		}
	}
});
```

**Comment by igorescobar** [comment]
:+1:
