### ISSUE TITLE
Issue with Alphanumeric Pattern Masking

### ISSUE THREAD

**Issue by raghunathsanam** [igorescobar/jQuery-Mask-Plugin#300]
I am using something like .mask("aa99999").  Entered gk12345.

Issue 1: Delete 'g' and tabout.  I see only k in the input field.

Issue 2: Start deleting the value starting from 'g'.  Will be able to delete only 'gk' after that i am not able to delete.

**Comment by igorescobar** [comment]
```
Problems & Bugs?

Did you read our docs? Yes? Cool! So now... make sure that you have a functional jsfiddle exemplifying your problem and open an issue for us. Don't know how to do it? Use this fiddle example.
```

**Comment by igorescobar** [comment]
Also... share information about SO and Browser.

**Comment by raghunathsanam** [comment]
http://jsfiddle.net/Raghunadh/7de4cLow/
Chrome Version 40.0.2214.111 m

**Comment by igorescobar** [comment]
What OS?

**Comment by raghunathsanam** [comment]
Windows 7

**Comment by igorescobar** [comment]
You're using MASKED INPUT... I think you're at the wrong repository my friend ;)

**Comment by igorescobar** [comment]
https://github.com/digitalBush/jquery.maskedinput

**Comment by raghunathsanam** [comment]
ahh...sorry for the trouble.  thank you.
