### ISSUE TITLE
Campo de Email

### ISSUE THREAD

**Issue by evertramos** [igorescobar/jQuery-Mask-Plugin#301]
Olá Igor,

Excelente trabalho! Espero poder ajudar em breve.

Estou usando o plugin para limitar o tamanho dos campos e fiz para o e-mail, ex. limit de 45 caracteres alfa numéricos $('.email').mask('AAAAA...'); porém não está permitindo digitar o '@', não sei se isso seria um 'issue' ainda novo no desenvolvimento, mas segue o fiddle:

https://jsfiddle.net/evertramos/ag9p2tvj/11/

Abs,

**Comment by igorescobar** [comment]
@evertramos veja que na documentação diz que ```A``` quer dizer:

```javascript
translation: {
        '0': {pattern: /\d/},
        '9': {pattern: /\d/, optional: true},
        '#': {pattern: /\d/, recursive: true},
        'A': {pattern: /[a-zA-Z0-9]/},
        'S': {pattern: /[a-zA-Z]/}
    }
```

Você só precisa adicionar o caracter que você precisa no objeto de translation. Na documentação você vai achar como fazer isso.

**Comment by evertramos** [comment]
Olá @igorescobar desculpe-me não havia encontrado, mas vou rever a documentação e tentar adicionar o '@'. 
Grato!
