### ISSUE TITLE
Fails to integrate with JVFloat

### ISSUE THREAD

**Issue by doublejosh** [igorescobar/jQuery-Mask-Plugin#302]
Float labels are another great input refinement, and should/can be used with an input mask. JVFloat is a popular library.  https://github.com/maman/JVFloat.js

The jQuery-MaskPlugin inserts `undefined` into the text field when combined with the JVFloat.

**Comment by doublejosh** [comment]
Able to hack around the issue but only adding the mask once input is present.

```javascript
$.each($('.form-input__text'), function() {
  $(this).on('focus blur change input', function touchedInput() {
    if ($(this).val() !== '') {

      // Masks.
      if ($(this).attr('name') === 'card_num') {
        $(this).mask('0000-0000-0000-0000');
      }
      if ($(this).attr('name') === 'exp_date') {
        $(this).mask('00/00');
      }
    }

  });
});
```

Not great.

**Comment by igorescobar** [comment]
If you were able to submit a PR identifying and fixing the problem I would more than happy to merge it.
