### ISSUE TITLE
Value is modified after change event when it was saved

### ISSUE THREAD

**Issue by laszlogmenyhart** [igorescobar/jQuery-Mask-Plugin#303]
We use backbone.stickit (v0.9.2) and jQuery-Mask-Plugin (v1.11.4) together on a field.
We found, that the value was saved to the model before the modification because of jquery.mask.
I think it is not an error because of stickit. It occurs every time when change event is used.
It seems that stickit runs first and save the value, second jQuery plugin modifys the value (for example I wrote an extra character into the field).
I modified the source, but maybe it is not the best soultion. Please check it and correct it! Could you please solve this problem in the next version?

            val: function(v) {
                var isInput = el.is('input'),
                    method = isInput ? 'val' : 'text',
                    r;
                if (arguments.length > 0) {
                    if (el[method]() !== v) {
                        el[method](v);
                        // NEXT LINE WAS ADDED  src/jquery.plugin.js line 180.
                        el.trigger('change');
                    }
                    r = el;
                } else {
                    r = el[method]();
                }
                return r;
            },

Unfortunately the value could be the same .on('blur.mask', function(){ so change event is not triggered.

Thanks,
LAci

**Comment by igorescobar** [comment]
@laszlogmenyhart I'm not sure if I understood your problem... but I'm pretty sure that doing what you just didn't isn't the best solution for the project itself, but it probably works for you... we need to think about a solution that could be used in a generic way. What you just did isn't the right behaviour for the most of the users.

**Comment by laszlogmenyhart** [comment]
I tried to give you an example here: http://jsfiddle.net/6pco4om7/74/ (based on http://jsfiddle.net/igorescobar/6pco4om7/) and found that "input" event is tricky.

Thanks

**Comment by igorescobar** [comment]
@laszlogmenyhart No idea how to fix this without breaking another things.
