### ISSUE TITLE
contenteditable elements improperly move text caret/cursor to the start

### ISSUE THREAD

**Issue by natguy** [igorescobar/jQuery-Mask-Plugin#304]
Hi, Igor, I am seeing a possible issue: I am unable to properly use masks on contenteditable spans, divs etc. As you type, it seem to move the text caret/cursor to the start of the text (instead of at the end) whenever the js refreshes the element's text with a new text character like a comma, colon etc.

Add the following via Chrome dev tools to your homepage http://igorescobar.github.io/jQuery-Mask-Plugin/ and then try editing the fields:

The time is &lt;span class=&quot;time&quot; contenteditable=&quot;true&quot;&gt;123456&lt;/span&gt; and it costs 
&lt;span class=&quot;money&quot; contenteditable=&quot;true&quot;&gt;12345678&lt;/span&gt;.

Thoughts? Maybe I'm missing something? Thank you.

**Comment by igorescobar** [comment]
A JSFiddle? Nothing to help?

**Comment by igorescobar** [comment]
closed due inactivity.

**Comment by jesusangelm** [comment]
I'm trying to use this plugin in a td element with property contenteditable = "true" and I get a weird behavior.

http://codepen.io/jesusangelm/pen/OVeByW

**Comment by Razum** [comment]
Hi, Igor. First,  I want to thank you for this marvelous plugin. 
Here is the example that illustrates the problem.

http://jsfiddle.net/Razum/L5ch3qrt/


Just remove everything and start typing.
When you start typing and reach comma it will move cursor to the beginning of the text field.
