### ISSUE TITLE
Show placeholder immediately after entering the previous symbols

### ISSUE THREAD

**Issue by tracklog** [igorescobar/jQuery-Mask-Plugin#305]
I want to show an input field for a code like this: "ASDF3-687E2-TE656-0KP2S", the mask is "AAAAA-AAAAA-AAAAA-AAAAA".
I don't want to show a placeholder because the input thex is align middle.

If the user enters the first 5 code digits "ASDF3", the Symbol "-" is not shown. The symbol is only shown if the user enters the 6. digit: "ASDF3-6".

So the user doesnt see that he must not enter the "-".

How can I customize the plugin that the "-" Symbol appears directly after the user enters the 5. digit "ASDF3-"?

https://jsfiddle.net/aw26m37b/1/

**Comment by igorescobar** [comment]
@tracklog you can change your mask pattern as your user types so all you need to do is changing the mask using the onKeyPress callback (check out the docs).
