### ISSUE TITLE
Feature request: mask texts without an selector (AngularJS)

### ISSUE THREAD

**Issue by sergiomichels** [igorescobar/jQuery-Mask-Plugin#306]
It would be nice to be able to mask not only inputs but also texts. This is a good feature to use when this plugin is integrated with AngularJS filters, for example:

`2023490090 | mask: '000.000.000-00'` 

This can be accomplished by adapting the `getMasked` method to accept text values. The jQuery usage could be

`$.masked(2023490090, '000.000.000-00')` 

I will try to reserve some time this week to make a pull request :-)

**Comment by igorescobar** [comment]
JQuery Mask works with text elements too. There is some examples at our home page. 

[]'s
Igor

**Comment by sergiomichels** [comment]
Right, but it works without an element like my example?

**Comment by igorescobar** [comment]
Essentially, nothing will work without an selector. Everything depends upon it. 

[]'s
Igor

**Comment by sergiomichels** [comment]
The function that I mentioned can be easily treated to work without selectors...

**Comment by igorescobar** [comment]
@sergiomichels I know that :-) I'm just explaining why it will not work without an selector. This should be implemented because it's not ready to work without an selector. This feature should be well designed so don't need to hurry ;-)

**Comment by sergiomichels** [comment]
Ok, got it! My hurry is to not duplicate code or customize it in the project without  really needing. Nothing great comes with some hidden customized code that a few knows

**Comment by igorescobar** [comment]
Sure, what we need to have in mind is that it should be generic, relying only on jQuery and vanilla javascript behaviours...never specifically related or dependent on a angular or any other framework. You should probably know that I'm just being as much clear as possible :+1:

**Comment by sergiomichels** [comment]
Yes, Angular is just an example of use case and the mask plugin should not depend on it. My final suggestion ($.masked) could be used by anyone.

**Comment by rodolfojnn** [comment]
+1 for this feature

**Comment by schleumer** [comment]
I have the same problem too, it's not only about Angular. I need to do this workarround:

```
$(element.find('input')[0]).mask(`#.##0,00`, {reverse: true})
```

To mask only bind to the element inside `element` variable, which is an template compiled on the fly and not available on document.

`element.find('input')[0]` will bring the first DOMElement(which is a native element) from the jQuery's elements array. And $(...) will create another jQuery array with that element and will unbind from the `input` selector, which will make the plugin work "as expected".

And this exemple:

```
element.find('input').mask(...)
```

will bind to __all__ `input` elements on the entire document. 

-------------

Also, Angular's core works on jQuery, so, all elements on Angular if jQuery is available are also a jQuery element and supports jQuery plugins too.

**Comment by settysreekanth** [comment]
FYI -I happened to do it in the following way in my angular application.. 
element.val(<some_value>).mask('AAA-AAA')

PS: In my case, element was input type.

**Comment by igorescobar** [comment]
Guys:
https://github.com/igorescobar/jQuery-Mask-Plugin/issues/499

Also... the method `.masked` is already available.

Any other example on alternatives on how to integrate it would be appreciated.

**Comment by sergiomichels** [comment]
@igorescobar Your example is just for directives, and with this type of component it plays nice. 

My request was for [filters](https://scotch.io/tutorials/building-custom-angularjs-filters), when I do not have an instance of an element.
