### ISSUE TITLE
Only numbers is not working for me.

### ISSUE THREAD

**Issue by johnflaster** [igorescobar/jQuery-Mask-Plugin#307]
When i set this mask the field allow letters and more than 8 characters: 

    $("selector").mask("00000000")

I don't need to limit field to 8 characters, I only need to allow only number in my field.

See in fiddle: http://jsfiddle.net/Lt5y5jme/

**Comment by kerstvo** [comment]
.mask("#")

**Comment by 2madera** [comment]
You are used **input[type=number]**, just use **input[type=text]** and your script will be run.

**Comment by johnflaster** [comment]
That's It. But I guess that is a bug.
