### ISSUE TITLE
how can i put , in mask input

### ISSUE THREAD

**Issue by narendrakothule** [igorescobar/jQuery-Mask-Plugin#309]
i am using mask of   $('.simple-field').mask('000.0000', {placeholder: ".0000"});how can i put number 3.4 in this. 

i have to to enter like 003.4

is there any way i can input (.)manually?  so i should be able to enter 3.4

**Comment by 2madera** [comment]
You can try fill up with zeros until the field be correct. In your case I will not use mask in that field, only a validation.

**Comment by igorescobar** [comment]
I recommend you to use a currency plugin instead of a "mask" plugin otherwise your code is going to look ugly as hell.
