### ISSUE TITLE
Change Event ignored under certain conditions.

### ISSUE THREAD

**Issue by rodrigokalt** [igorescobar/jQuery-Mask-Plugin#310]
Basically if i use jquery in the header, and a masked input, the mask will be working but change event is not fired.

If i use Jquery wrapped in the "OnLoad" event then everything works properly.

http://jsfiddle.net/898rmtre/

My requirements force Jquery to be in the header, as needed by other graphic libraries, does someone know a workaround for this ?

thanks.

**Comment by igorescobar** [comment]
@rodrigokalt so... all your digits in your mask are optional? That is what ```9```  means.

But you're problem is obvious. At the time you're loading your definitions the field #input1 doesn't exist so there no element to attach the event.

.ready of jQuery did the trick:
http://jsfiddle.net/898rmtre/1/
