### ISSUE TITLE
Mascara não é aplicada após validação de formulário em JSF

### ISSUE THREAD

**Issue by cassioliveira** [igorescobar/jQuery-Mask-Plugin#311]
Estou usando JSF com Primefaces e mascara de telefone funciona corretamente, mas quando faço uma submissão e algum valor que era obrigatório deixa de ser preenchido, a mascara do campo deixa de funcionar. Exemplo: O campo nome do formulário não pode ser nulo e ser for deixado em branco e pressionar o botao de salvar, a pagina é submetida e uma mensagem de erro retorna para que eu preencha o nome mas a máscara de telefone deixa de funcionar caso eu tente colocar o telefone.

**Comment by igorescobar** [comment]
```
##Problems & Bugs?
Did you read our docs? Yes? Cool! So now... make sure that you have a functional jsfiddle exemplifying your problem and open an issue for us. Don't know how to do it? Use this fiddle example.
```
