### ISSUE TITLE
Force mask on change event

### ISSUE THREAD

**Issue by iurisilvio** [igorescobar/jQuery-Mask-Plugin#312]
When I programatically fill the input, I have to force the initial mask.

I triggered a fake `keyup` event and it worked, but I expected it to work with the `change`, like most jQuery components.

**Comment by igorescobar** [comment]
![screen shot 2015-06-25 at 9 44 53 am](https://cloud.githubusercontent.com/assets/24032/8354393/29367394-1b1e-11e5-8eab-71a274dafa33.png)

**Comment by iurisilvio** [comment]
Sorry, I forgot to make this jsfiddle.

http://jsfiddle.net/dj505oxp/5/

I created several buttons to show what I have to do to change my input data dynamically.
