### ISSUE TITLE
Fallback não removendo o caractere não validado

### ISSUE THREAD

**Issue by LinkForce** [igorescobar/jQuery-Mask-Plugin#313]
Encontrei um erro com o fallback na minha máscara.

Meu código esta assim:

$('._txtTempoResp').mask("50:50", {
                    translation: {
                        '5': { pattern: /[\0-5]/, fallback: '5' }, 
                        '0': { pattern: /[\0-9]/ }
                    }, placeholder: "00:00"
                });

O caso é o seguinte:

Quando o usuário insere um valor na primeira casa que não valida no padrão '5', a propriedade do fallback é ativada, e é inserido o caractere 5 no input.
Se, por exemplo, o usuário insere o valor '7' na primeiro casa, o fallback é ativado e o valor 5 é inserido na primeira casa, mas o valor 7 ainda não foi removido, ele é jogado para a próxima casa.
Acontece que o valor 7 é valido para a segunda casa, então em vez de ser removido, ele é mantido nesta casa.

Acredito que o fallback deveria trocar esse digito 7 pelo digito 5, sem aplicá-lo à próxima casa.

jsFiddle exemplificando: https://jsfiddle.net/joh2udsj/

**Comment by igorescobar** [comment]
O que acontece é o seguinte:
O número 7 não é valido na posição 1, mas é valido na posição 2. O plugin joga o caracter para a próxima posição valida e joga o caracter de fallback na posição 1.

Veja que se você digitar ç na primeira posição, o fallback funciona como você espera por que ç não é valido na posição seguinte.

Não é um bug, este é o comportamento esperado, basicamente por que geralmente o usuário copia e cola muita coisa e muitas vezes o dado vem com caracteres inválidos. Não consigo arrumar isso sem comprometer o funcionamento de outras coisas em outros cenários.

**Comment by LinkForce** [comment]
Não poderia ser implementada uma propriedade que alterasse o behavior do fallback, jogando o caractere para a próxima casa ou somente dando replace nele?
