### ISSUE TITLE
Mask doesn't work on disabled inputs when changing value from javascript

### ISSUE THREAD

**Issue by r3wt** [igorescobar/jQuery-Mask-Plugin#314]
When change input value with javascript, mask doesnt work
```js
if(zdiv.hasClass('phone-mask')){
	zdiv.trigger('keyup');
}
```

**Comment by igorescobar** [comment]
![screen shot 2015-06-25 at 9 44 53 am](https://cloud.githubusercontent.com/assets/24032/8363364/c3a2f5de-1b54-11e5-8ced-a326708ff41e.png)

**Comment by igorescobar** [comment]
Help me to help you :+1:

**Comment by r3wt** [comment]
@igorescobar i was going to post a screen but http://puush.me was down

**Comment by igorescobar** [comment]
So..?
