### ISSUE TITLE
Add 'main' property to package.json

### ISSUE THREAD

**Issue by gsantiago** [igorescobar/jQuery-Mask-Plugin#318]
It would be nice to add the `main` property to package.json, then browserify could import the module just with `require('jquery-mask-plugin')`.

It could be something like this:

`"main": "./dist/jquery.mask.js"`

**Comment by igorescobar** [comment]
Hey, could you test it and propose a pull request with your change?
Thanks!

**Comment by igorescobar** [comment]
@gsantiago  could you test it? (v1.13.3)

**Comment by gsantiago** [comment]
@igorescobar I have tested here and now it works fine with Browserify.
Thanks!
