### ISSUE TITLE
Want to validate the user on input for ipaddress

### ISSUE THREAD

**Issue by usamamashkoor** [igorescobar/jQuery-Mask-Plugin#327]
i want to validate the field ipaddress if the user enter 192.3.4. and forgot to put value after . then i want to validate for example by adding 2px solid red border by using a addClass of jquery the user how can i do that
here is my htmll
<input type="text" class="form-control ip_address" id="" placeholder="*IP Address">
and here is my jqyuery
	$('.ip_address').mask('0ZZ.0ZZ.0ZZ.0ZZ', {
			   translation: {
			     'Z': {
			       pattern: /[0-9]/, optional: true
			     }
			   }
			 });
I am a begginer in jquery so kindly help me

**Comment by igorescobar** [comment]
formvalidation.io
