### ISSUE TITLE
Available on Nuget?

### ISSUE THREAD

**Issue by reverence12389** [igorescobar/jQuery-Mask-Plugin#328]
Is this plugin available via Nuget?

**Comment by igorescobar** [comment]
No idea.

**Comment by tiesont** [comment]
It's listed as a pre-release, but at least one package exists: https://www.nuget.org/packages/JQuery-Mask-Plugin/1.5.3-r2

**Comment by igorescobar** [comment]
@omniscient ?

**Comment by omniscient** [comment]
We are not using this component anymore so we are not maintaining the nuget package. Feel free to use the pre-release package or re-release the new version as you see fit.

**Comment by tiesont** [comment]
@igorescobar If you want, I can publish a new package, or @omniscient can hand off ownership of their package.

**Comment by igorescobar** [comment]
Is there anyway to automatically upgrade/manage this package? Like I do with npm and so on? Seems very confusing how nuget works and how to manage my libs...

**Comment by tiesont** [comment]
I'm not sure. I just use the Package Explorer to create packages manually. Does this help? http://chriskirby.net/automate-nuget-pack-and-push-using-grunt-and-node-js/

**Comment by igorescobar** [comment]
@tiesont would you be interested in submit a PR automating this task so I can add it to ```deploy.rb```

**Comment by tiesont** [comment]
@igorescobar I suppose I could take a crack at it, although I'm not really all that familiar with npm and whatnot. If there's no urgency to get an official NuGet package out, it would be an interesting learning experience for me.

**Comment by igorescobar** [comment]
Are you in or out?! ;-)

[]'s
Igor

**Comment by tiesont** [comment]
@igorescobar Sure, why not? Can you PM me your NuGet user name (or create an account and let me know what it is)? You can find my email on my profile.

**Comment by tiesont** [comment]
@igorescobar I'm afraid I have to admit I'm not going to have time to work on this. My workload at work has increased enough that I don't have much time to work on this. 

If you want, I can manually create packages as you release updates, as it doesn't take much effort/time to generate packages with the Package Manager.
