### ISSUE TITLE
Input with Maxlength and Mask

### ISSUE THREAD

**Issue by Valkhan** [igorescobar/jQuery-Mask-Plugin#331]
Hi, I was updating my JS libraries and this library was one of them.

I was using version 1.5.3 and it worked just fine for a long time, but a solution to a problem made me update it to the latest version 1.13.3.

I have the following situation:
I've a field with maxlength defined as '8' and a mask like: '00000-000', with the version 1.5.3 it was working just fine.

JSfiddle on version 1.5.3 WORKING: https://jsfiddle.net/PVdL/6rfbL5pr/

Now with the new version the masked value '-' is inputted as a character which occupies a position of my input maxlength, I've tried passing: maxlength: true and maxlength: false with no success.

JSfiddle on version 1.13.3 NOT WORKING: https://jsfiddle.net/PVdL/y01Lg2th/

Is there a reason why this resource was deprecated or am I doing something wrong?

I've searched related topics but found none similar to this.

Thanks in advance.

**Comment by skantipudi19** [comment]
I am using jquery 1.11.3 where my element has max length and .mask() function is working fine. 

But i am having issue with jquery 1.11.3 and mask is not applying with data-mask attribute inside the element. but working fine with .mask() function

**Comment by igorescobar** [comment]
@Valkhan now it works?
https://jsfiddle.net/y01Lg2th/3/

Didn't change a thing. Just fixed the URL of the jquery mask.
