### ISSUE TITLE
Bower: Package `jquery-mask-plugin` not found

### ISSUE THREAD

**Issue by renatorib** [igorescobar/jQuery-Mask-Plugin#335]
ENOTFOUND Package `jquery-mask-plugin` not found
Please add to bower <3

**Comment by igorescobar** [comment]
![screen shot 2015-08-14 at 7 27 01 pm](https://cloud.githubusercontent.com/assets/24032/9285264/7f694714-42ba-11e5-8bc4-a0954154d17e.png)

**Comment by renatorib** [comment]
Ué
