### ISSUE TITLE
IE7 JSON.stringify support

### ISSUE THREAD

**Issue by gunnx** [igorescobar/jQuery-Mask-Plugin#336]
Plugin doesn't run on IE7 due to use of JSON.stringify. 
I could polyfill JSON with conditional comment/modernizr

**Comment by igorescobar** [comment]
Sounds like a good alternative. I'm not going to add JSON implementation inside of our plugin because of  IE7 LOL.

**Comment by gunnx** [comment]
Yes of course more wondering if json was needed at all. Happy to polyfill though, unfortunately still supporting IE7 :(

**Comment by igorescobar** [comment]
They deserve to die anyway... ;D
