### ISSUE TITLE
Problem when using data attributes

### ISSUE THREAD

**Issue by caiquecastro** [igorescobar/jQuery-Mask-Plugin#337]
I found a bug, but I still had no time to check the code for a solution. But it also may be related with jQuery. I was using data-mask="phone" in the fields that i wanted to mask. While I was typing, there was no problem, but when I loaded the value (with mask) in the value attribute of the input, the mask didn't work properly and neither when I was masking a static div element. In both cases, it was changing the value to be masked by a opening parentheses. I'm not sure if i was clear, but when i changed from data-mask=phone to class=phone, the bug was solved and it's working now!

**Comment by igorescobar** [comment]
I can't help you if you didn't provide a functional jsfiddle. You shouldn't be using data-mask attribute like that. Check out our docs.

http://igorescobar.github.io/jQuery-Mask-Plugin/
![screen shot 2015-08-14 at 7 13 03 pm](https://cloud.githubusercontent.com/assets/24032/9285086/851dd1b8-42b8-11e5-91ce-464f101db905.png)

**Comment by caiquecastro** [comment]
I had forgotten this part of the api, so the problem was the conflict between my data attribute and the attribute from the plugin. I was using the same data attribute: data-mask.
