### ISSUE TITLE
Textarea Support?

### ISSUE THREAD

**Issue by tommykent1210** [igorescobar/jQuery-Mask-Plugin#339]
Hi,

I saw an issue from November 2014 that said textareas are not supported.Has support been added? If not, what are some alternatives?

Thanks
Tom

**Comment by igorescobar** [comment]
Sorry @tommykent1210 .

I don't think that this is going to be part of our core.

**Comment by tommykent1210** [comment]
Hi, sure thing.

Can I ask why? Why mask text boxes but not text areas?

**Comment by igorescobar** [comment]
@tommykent1210 try to implement via PR it and you will know why :laughing:

**Comment by tommykent1210** [comment]
aha! I see xD Oh well, time to find an alternative :P

**Comment by igorescobar** [comment]
@tommykent1210 good luck! :+1:
