### ISSUE TITLE
bug with ctrl + A

### ISSUE THREAD

**Issue by p30help** [igorescobar/jQuery-Mask-Plugin#341]
hi 
sometimes when select all character in textbox with press Ctrl + A key , the all characters does not  selected.
for example see and test date box:
http://jsfiddle.net/igorescobar/6pco4om7/
------------
also 
I removed under codes from jquery.mask.js and this problem has solved:

                    if (el.is(':focus')) {
                        var range, ctrl = el.get(0);
                        if (ctrl.setSelectionRange) {
                            ctrl.setSelectionRange(pos,pos);
                        } else if (ctrl.createTextRange) {
                            range = ctrl.createTextRange();
                            range.collapse(true);
                            range.moveEnd('character', pos);
                            range.moveStart('character', pos);
                            range.select();
                        }
                    }

**Comment by igorescobar** [comment]
Interesting because the method ```setCaret``` is not even called when you hit CTRL + A:
```javascript

                    // change caret but avoid CTRL+A
                    if (changeCaret && !(keyCode === 65 && e.ctrlKey)) {
                        // Avoid adjusting caret on backspace or delete
                        if (!(keyCode === 8 || keyCode === 46)) {
                            caretPos = p.caretPos(caretPos, currValL, newValL, maskDif);
                        }
                        p.setCaret(caretPos);
                    }

```

**Comment by jmclean** [comment]
This bug happens only if the user lets go of CTRL before letting go of A. In that case, ctrlKey is 0 so it sneaks past that test.

**Comment by DGuidi** [comment]
@igorescobar I think also SHIFT + END should be handled as special case, like CTRL + A.
