### ISSUE TITLE
Conflito Validador HTML 5 fire Fox

### ISSUE THREAD

**Issue by lelopes** [igorescobar/jQuery-Mask-Plugin#342]
Congratulations on the Plugin .
I'm using validators fields with HTML 5. Only in FireFox fields are left with red edges .
Any solution?
Thank you.

**Comment by igorescobar** [comment]
@lelopes jQuery Mask Plugin não altera borda de campos de formulário. Tenho certeza que este problema não está relacionado com este projeto.

**Comment by lelopes** [comment]
realmente não tem problema no projeto.
O Problema acontece apenas no FireFox.
<label>Telefone: <input type="text" id="telefone" required name="telefone"
class="telefonee" /></label>

se o atributo required estiver setado, o validados do HTML 5 coloca borda
vermelha no input.



Em 28 de agosto de 2015 11:15, Igor Escobar <notifications@github.com>
escreveu:
