### ISSUE TITLE
Added the property clearMaskOnSubmit 

### ISSUE THREAD

**Issue by raphaelm22** [igorescobar/jQuery-Mask-Plugin#343]
Implemented a new option "clearMaskOnSubmit"
You can check in: https://github.com/raphaelm22/jQuery-Mask-Plugin/commit/956c737fbe12ec790870d9627038e347fe69b594

You can not send the desired value with mascara to the server.

The option also predicts that som error may occur in sending the form
and the field is in the mask, so mask is reapplies after 500ms.

**Comment by igorescobar** [comment]
@raphaelm22 I appreciate your suggestion but I don't belieave that your decision matches with what I hope in terms of future of jQuery Mask.

**Comment by Chealer** [comment]
igorescobar, what decision are you referring to?

**Comment by raphaelm22** [comment]
I believe this option would be very useful for project decided to add mascara plugin after the construction of much of the project. So the only concern would be to implement the use of client-side plugin, and would not need to implement a code that masks cleared the server side.

Example: a case by zip code address query, the query does not expect a zip with filter mask, with the option marked as true, it is not necessary any server implementation to continue working.

**Comment by igorescobar** [comment]
As a developer I believe that you should `aways` sanitize your input, no matter what. 

Adding a feature like this would only encourage developers to not do it. This is the only reason why some developer would need something like that, because they don't want do care about sanitizing your input.

With that in mind... a feature like this would only decrease your app's security and add a bunch of code in this plugin for the laziness.

Trust me. You don't want this feature.

**Comment by Chealer** [comment]
igorescobar, jQuery-Mask-Plugin is used client-side. Sanitization is a server-side process. I fail to see how this would encourage developers to not sanitize input. If you really think it does, show us a concrete example.

Trust me. We do want this feature. Unless there is a flaw in the implementation, this will not decrease our security.

**Comment by igorescobar** [comment]
@Chealer You need to convince me that this worth implementing, not me :+1: 

At this point I can't any value on this feature besides the fact do you wouldn't need care about sanitization on server side. If you just need the unmaskedvalue for some input you might have do deal with ajax requests or something like that just you `$('.date').cleanVal();`

**Comment by Chealer** [comment]
igorescobar, I do not need to convince anyone that this is worth implementing to keep this ticket open. It is whoever wants to close this who needs to explain why this would be invalid.

Please read my previous comment; **sanitization is a server-side process**. Sanitization is not achieved by clearing the mask, and is certainly not this feature's value (normalization).

Without this feature, the server can send the browser an unformatted string. Even if the user does not change the value, the server will get back a different (formatted) string.

I cannot believe we are arguing over whether such a feature should be available or not. What should be decided is whether unmasking should be default or not.

**Comment by igorescobar** [comment]
clearMaskOnSubmit event will not be implemented. Sorry.

Enviado do meu iPhone

**Comment by Chealer** [comment]
I reported the issue underlying this request in ticket #371.
