### ISSUE TITLE
Mask function on div,span,td evaluates empty string as value

### ISSUE THREAD

**Issue by lucianjp** [igorescobar/jQuery-Mask-Plugin#345]
The Mask function uses el.Val() to pass to function if the mask was set to a function. el.Val() return something only if it's an input. Instead the el.text() should be use for other type of elements.

**Comment by igorescobar** [comment]
Thanks bro! Going to fix it ASAP.

**Comment by igorescobar** [comment]
Fixed in coming up new version.
