### ISSUE TITLE
Unexpected behavior in Firefox for Android

### ISSUE THREAD

**Issue by iudelsmann** [igorescobar/jQuery-Mask-Plugin#346]
There seems to be an issue with Firefox for android. When adding a character for the mask, like a "-" on a phone, the cursor moves backwards. 

I'm borrowing this fiddle created by another user that had the same problem: http://jsfiddle.net/3t6t5p44/1/ 

If you type from 1 to 8 (in order) you'll end up having 1234-6785 as the cursor moves back after you type the "5".

**Comment by njburkard** [comment]
This is happening for me too, Firefox on Nexus 10 (android 5.1.1), in a date field. Once you type two digits, then upon typing the third, the slash is inserted an the cursor then is placed after the slash, so typing 08132000, gives 08/32/0001. If you do type the slashes yourself, no problems.

**Comment by igorescobar** [comment]
I really hope that some android developer fix the problem. I don't even have an android to test it.

**Comment by rherring** [comment]
I am currently having this issue as well on the Android device that I'm using to test on (My bosses personal phone). He's running Android v.4.4.2

Just as described in the fiddle attached above, when you start typing into the field on the Android device, the cursor gets moved around and the numbers become out of order. Then, if you try to place the cursor and correct the mistake by using the backspace key, the cursor is immediately placed at the end of the line.

My observation is, (using the US Phone Mask) when you type the first character, the script them places a character before, and the phone then moves the cursor to position 2 which now happens to be in front of the character you just typed.
