### ISSUE TITLE
Typing at the begining of a filled input

### ISSUE THREAD

**Issue by yann-eugone** [igorescobar/jQuery-Mask-Plugin#347]
Hi, we've discovered a strange behavior of the component.

## Reproducing the issue

- initialize a date input with some data (fill it with your keyboard)
- put the cursor at the beginning of the input
- try to replace the value by typing again

## Noticed behavior 

The input is replaced, but the cursor is kept at the begining of the input, which is a very odd behavior, as the user do not know where his cursor is.

Any help whould be appreciated.

**Comment by parissge** [comment]
I confirm.

The cursor is kept at the beginning of the input. 
Actually the cursor is kept where ever inside the string you place it and start typing.

Is there a fix for this?

**Comment by gregaubert** [comment]
Same problem here! It seems that the curser position should be recalculated after each key press...

**Comment by igorescobar** [comment]
Already fixed on new version.
