### ISSUE TITLE
Package for MeteorJS

### ISSUE THREAD

**Issue by ccortezia** [igorescobar/jQuery-Mask-Plugin#350]
Hi @igorescobar. Thanks for sharing this useful project.  
Have you considered publishing it under Atmosphere (meteorjs central repository) ?

**Comment by igorescobar** [comment]
Should I? :smile:

**Comment by ccortezia** [comment]
Lots of people would benefit. I could lend a hand, just ask. Feel free to close this issue otherwise.

**Comment by igorescobar** [comment]
It's painless? If it is... Why not ;-)

Enviado do meu iPhone

**Comment by ccortezia** [comment]
Ok. I can help create the package, but the publication itself should be done by you since you will be the package owner on Atmosphere.  For this, you must create a meteor account (which will be your namespace for package publication). Then I can provide a PR with a proper package.js. You will need to rerun the publication process on every future release. This "should" be painless (I created several private packages but never used the publication mechanism).

Let me know if you want to proceed.

**Comment by ccortezia** [comment]
Getting started on meteor is really straightforward.
Regarding atmosphere, you can take a look here: https://atmospherejs.com/i/publishing

**Comment by igorescobar** [comment]
Im only concern is about... "too many publishers". Take a look: https://github.com/igorescobar/jQuery-Mask-Plugin/blob/master/deploy.rb

Currently I'm already publishing to jQuery Mask to NPM and Bower and every now and then someone comes up with a new one seems like an endless work.

How big it's the MeteorJS community do you have any insight about it?

**Comment by ccortezia** [comment]
I don't have a clue on the size of meteor community as whole, but here is the result of the search for "mask" in atmosphere: https://atmospherejs.com/?q=mask. 

Real numbers tend to be higher than presented there since not every download accounts, only those from apps published into meteor's own hosting provider (as far as I know).

**Comment by igorescobar** [comment]
Done: https://atmospherejs.com/igorescobar/jquery-mask-plugin

**Comment by igorescobar** [comment]
https://twitter.com/igorescobar/status/706622585895821312
