### ISSUE TITLE
How to create a valid mask for dd/mm/YYYY

### ISSUE THREAD

**Issue by kouts** [igorescobar/jQuery-Mask-Plugin#354]
The example ```$('.date').mask('00/00/0000');``` works great, but it allows the input of dates such as:
57/94/6345
Is there any way to make it conform to a date standard such as dd/mm/YYYY?

**Comment by awarrenlove** [comment]
This is not meant to be a validation library, just a way to automatically insert characters like punctuation. Validation would have to be done separately.

**Comment by kellerkichel** [comment]
sei que não tem nada a ver com o plugin, mas talvez ajude:

    function checkDate(val){
        var er = /^(((0[1-9]|[12][0-9]|3[01])([-.\/])(0[13578]|10|12)([-.\/])(\d{4}))|(([0][1-9]|[12][0-9]|30)([-.\/])(0[469]|11)([-.\/])(\d{4}))|((0[1-9]|1[0-9]|2[0-8])([-.\/])(02)([-.\/])(\d{4}))|((29)(\.|-|\/)(02)([-.\/])([02468][048]00))|((29)([-.\/])(02)([-.\/])([13579][26]00))|((29)([-.\/])(02)([-.\/])([0-9][0-9][0][48]))|((29)([-.\/])(02)([-.\/])([0-9][0-9][2468][048]))|((29)([-.\/])(02)([-.\/])([0-9][0-9][13579][26])))$/;

        if (!er.test(val))
            return false;
        else
            return true;
    }

**Comment by kevinchevallier** [comment]
Here's an example that confirms both @awarrenlove and @kellerkichel statements (and because i just needed this as well):

```javascript
$dateofbirth.mask("00/00/0000",{
	placeholder:"MM/DD/YYYY",
	clearIfNotMatch: false,
	onComplete:function(){
		var v = $dateofbirth.val();
		if( isValidDate(v) ){
			// do stuff
		} else {
			// do other stuff
		}
	}
});
```
This basically says to use the mask with a placeholder, to not clear the mask if it's wrong and execute the function on `onComplete` callback.
`isValidDate()` is a simple function to check via regex if the date is valid like `checkDate()`.

Hope that helps.

**Comment by kellerkichel** [comment]
nice one thz :+1:

**Comment by lucasoneves** [comment]
Thank you @kevinchevallier. Nice solution!
