### ISSUE TITLE
phone mask - cursor jumps when editing

### ISSUE THREAD

**Issue by MaaikeB** [igorescobar/jQuery-Mask-Plugin#356]
put a value in the US Telephone number field, like (123) 456-7890
now try to change the 4 to another digit:
put the cursor after the 4 and delete it.
(what happens is that the 4 is deleted but the cursor jumps to after the 5)
now enter another digit, like 1
the 1 is added after the 5 and not instead of the 4 (before the 5) as it should
note: this happens only with digits after the spacial characters (brackets, space, hyphen)

**Comment by wambaloo** [comment]
It's happen after any character delimiter in placeholder (non numeric characters).

**Comment by wambaloo** [comment]
To resolve this, replace this line (221) :
if (!(keyCode === 8 || keyCode === 46)) {
by :
if (!keyCode === 8) {

In fact, the position must be recalculate every time, except for the "Delete" key. The "Backspace" key must recompute the caret position.

But there still a bug (with or without this modification) : if you place you cursor anywhere in the string (not at the end of course), and if you type something, the rest of the string change (I think the original goal is to replace characters with the new characters typed) and it's truncated. The behavior is not what it's supposed to be.

**Comment by dortonway** [comment]
+1

**Comment by igorescobar** [comment]
New version will fix it.

**Comment by rherring** [comment]
I'm using the absolute latest version of your script, and I've tried the proposed fix above, but I am still having this issue. Do you have any suggestions?

**Comment by archwyrm** [comment]
@rherring: I ran into this problem myself and was able to fix it with #403.

**Comment by igorescobar** [comment]
Could you please test the latest version and see if its fixed?

**Comment by igorescobar** [comment]
After you approval I will release right away.
