### ISSUE TITLE
onChange is not fired when delete last characters

### ISSUE THREAD

**Issue by wambaloo** [igorescobar/jQuery-Mask-Plugin#358]
When you delete character by character your string, the last character does not fire the "onChange" event. It's because of this line : "changed = val !== oldValue" in "callbacks" and because the variable "oldValue" is only updated on "blur" event. So when you don't leave the focus on the field, and you type something then you delete this, the last character deleted not fire the "onChange" event. I'm trying to find a fix and I will purpose it to you later.

**Comment by wambaloo** [comment]
Something like this could solve the problem : 
changed = val !== oldValue || val === oldValue === ''
if you considered that the old value is the original value of the field before you focus on the field.

**Comment by igorescobar** [comment]
Check it out:
```javascript

$.jMaskGlobals = {
    maskElements: 'input,td,span,div',
    dataMaskAttr: '*[data-mask]',
    dataMask: true,
    watchInterval: 300,
    watchInputs: true,
    watchDataMask: false,
    byPassKeys: [9, 16, 17, 18, 36, 37, 38, 39, 40, 91],
    translation: {
        '0': {pattern: /\d/},
        '9': {pattern: /\d/, optional: true},
        '#': {pattern: /\d/, recursive: true},
        'A': {pattern: /[a-zA-Z0-9]/},
        'S': {pattern: /[a-zA-Z]/}
    }
  };
```

Just remove the keys you don't want to be ignored on `byPassKeys` option
