### ISSUE TITLE
Currency mask with currency symbol

### ISSUE THREAD

**Issue by KevinBurton** [igorescobar/jQuery-Mask-Plugin#360]
May this is my lack of understanding. But, I cannot seem to come up with a mask that will automatically show the currency symbol ($). For example I want to enter 1234567.45 but I want to display $1,234,567.45. Where do I start looking?

Thank you.

Kevin

**Comment by igorescobar** [comment]
In this case, use a currency plugin.

**Comment by foglabs** [comment]
no chance of support for this? I like how light your plugin is

**Comment by foglabs** [comment]
nevermind, I'm just adding a $ if its not there on keyup, then removing any $ on submit
