### ISSUE TITLE
Any length of letters?

### ISSUE THREAD

**Issue by lookfortheroot** [igorescobar/jQuery-Mask-Plugin#361]
How to just filter anything except letters and set ANY length?

$('.name').mask('S'); //Only one letter
$('.name').mask('SSSSSSSSSS'); //Only ten letters etc

But this is very inconvenient, is it possible to set any length of letters?
Thank you!

**Comment by igorescobar** [comment]
Use a recursive pattern. Like `$('.name').mask('#'); `

**Comment by wal-asad** [comment]
@igorescobar `$('.name').mask('#');` is working only for numbers not for letters.

I am trying to allow only letters but its not working
  `$('.name').mask('S#');`

referencing [https://igorescobar.github.io/jQuery-Mask-Plugin/](url)

> You can also use that kind of feature to define what kind of data could be typed inside of a field:
> $('.example').mask('0#');
> Now only numbers will be allowed inside your form field.

**Comment by waghcwb** [comment]
Can't figure out jow to do it too.

**Comment by nickwalla** [comment]
$('.name').mask('Z',{translation:  {'Z': {pattern: /[a-zA-Z ]/, recursive: true}}});

take out the space after Z if you don't want spaces

**Comment by PunkHaz4rd** [comment]
The recursive option no longer works, if it ever has.

**Comment by thiagok** [comment]
> $('.name').mask('Z',{translation: {'Z': {pattern: /[a-zA-Z ]/, recursive: true}}});
> 
> take out the space after Z if you don't want spaces

Unfortunately this options does not accept accented chars.

**Comment by waghcwb** [comment]
Code from @nickwalla was not working for me (`v1.14.16`). I've handled with this code, hope is helps someone

```js
$('[data-mask="username"]').mask('A', {
  translation: {
    A: { pattern: /^[A-Za-záàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ'\s]+$/g, recursive: true },
  },
});
```
