### ISSUE TITLE
Cursor moves behind last inputted character on mobile after second "mask" character

### ISSUE THREAD

**Issue by TheRealMrCrowley** [igorescobar/jQuery-Mask-Plugin#362]
e.g. 
input: 7023758059 
mask: $('.phone').mask('(000) 000-0000');

if typed without clicking back to the end after every letter/number will turn out as: 
(709) 508-5732

this is only an issue on mobile devices that I've noticed

**Comment by igorescobar** [comment]
Duplicated

**Comment by kbleabres** [comment]
Was there any fix for this? I'm encountering this too.

**Comment by TheRealMrCrowley** [comment]
Change to type "tel"

Samps 
Web Master 
Cottage Skis 
702-375-8059 




-------- Original Message --------

**Comment by kbleabres** [comment]
Thank you @TheRealMrCrowley
