### ISSUE TITLE
Validação de campos com máscara

### ISSUE THREAD

**Issue by periscuelo** [igorescobar/jQuery-Mask-Plugin#363]
Boa Tarde. Primeiramente parabéns pelo trabalho. Notei que a máscara do telefone mostra um parêntese "(" caso a pessoa digite uma letra. E isso tem causado problemas pois na hora de validar o campo ele diz que está preenchido. Algo que resolveria isso seria verificar quando a máscara só permite números e se for o caso de só permitir números, fazer uma verificação ASCII permitindo somente que as teclas de 0 a 9 (ou seja as numéricas) sejam retornadas. Isso ajudaria muito pois resolveria outro problema por tabela. Quando se usa AngularJs os valores são atualizados assim que pressionamos o botão no input. Então se você digitar a, mesmo quando a mascará apaga a letra a, ou não mostra a mesma, ainda assim o angular entende que o valor do input foi a letra a. Se ajudar, as teclas ASCII numéricas vão do 48 ao 57.  Vi algo na documentação como byPassKeys, mas não achei nenhuma explicação sobre e nem consegui entender. Obrigado.

**Comment by igorescobar** [comment]
@periscuelo o função deste plugin é aplicar as mascaras. Não é do nosso interesse agregar a complexidade das validações. You got to work you way out ;)

**Comment by periscuelo** [comment]
Obrigado por avisar. :)
