### ISSUE TITLE
setInterval() slow down mocha test

### ISSUE THREAD

**Issue by Daniel1989** [igorescobar/jQuery-Mask-Plugin#366]
In source code, jquery.mask.js, will check if watchDataMask is true in every 300ms. But since use setIntervale(), it make this js do more work, and slow down in mocha test. For example, in my case, if we comment out setInterval(), test case cost 350ms, if not, it will take 5000ms! Do anyone have good idea to deal with this issue?

**Comment by igorescobar** [comment]
@Daniel1989 disable it. Check out the docs ;)
