### ISSUE TITLE
Add dollar sign to field

### ISSUE THREAD

**Issue by Bambicruz** [igorescobar/jQuery-Mask-Plugin#367]
I used the following, but it only seems to show the dollar sign at the end of the field:
$('.money').mask('$0,000,000', {reverse: true});

Any advice? If I remove the reverse true, then the thousand separator doesnt show correclty (that's why I need both the dollar sign and thousand delimiter to work)....

Thanks!

**Comment by igorescobar** [comment]
My advice is: Put the dollar sign outside of the field or use a money plugin.

**Comment by gkatsanos** [comment]
hey @igorescobar . thanks for the library! do you still stand by your answer that if we want currency formatting dollars or Euros we need to use a different library? something you would suggest?
