### ISSUE TITLE
How configure mask to edit number with optional decimal and thousand separator

### ISSUE THREAD

**Issue by nicolasroux** [igorescobar/jQuery-Mask-Plugin#368]
Hi,

I am trying to configure the mask to edit a number, with 2 optional decimals, and thousand separator.

I have tried so far the following mask: #.##0,99

But it does not work as I expect.

here is my fiddle: http://jsfiddle.net/6pco4om7/196/ 

thanks for your help

**Comment by igorescobar** [comment]
In this case, use a money mask.

**Comment by nicolasroux** [comment]
Hi Igor,

Thanks for your response, but it does not work as I expect; the decimals are not optional with the money mask.

**Comment by igorescobar** [comment]
Use another plugin, specific for monetary issues. That's what I meant.

Enviado do meu iPhone

**Comment by anvarulugov** [comment]
@igorescobar thank you for such awesome plugin. But this feature would very useful.

**Comment by bodtx** [comment]
I've used https://github.com/customd/jquery-number#number-formatting-as-you-type for optional decimal
