### ISSUE TITLE
Pressing Ctrl+C to copy text clears selection

### ISSUE THREAD

**Issue by jonsquared** [igorescobar/jQuery-Mask-Plugin#372]
When copying text on Windows browsers by pressing ctrl-c key combo, the text is copied, but the selection is cleared and the cursor position is moved.

I noticed this issue was reported once before but was closed because it could not be reproduced.  I have successfully reproduced this issue consistently while testing out a phone number mask "(000) 000-0000".  This issue only occurs on Windows machines and I have confirmed it occurs in both Chrome and IE (I have not bothered testing other browsers).

After looking at the source code, it doesn't appear to be checking the event.ctrlKey modifier along with the keyCode 67 (the letter 'c'). There may be other combinations that need to be ignored, but for maximum flexibility, perhaps the byPassKeys config could be expanded to support keycode + modifier key combos (including event.ctrlKey, event.altKey, event.metaKey, and event.shiftKey).

**Comment by kaljak** [comment]
For me this is also reproducable on Windows 10 in a current Chrome version.

Is there any reason to do special stuff if event.ctrlKey is set?

**Comment by igorescobar** [comment]
Can you test it again?

**Comment by igorescobar** [comment]
Will re open it in case of activity.

**Comment by jonsquared** [comment]
We will be testing this in our application soon. I will let you know if it
works out.
