### ISSUE TITLE
Fire Mask event on mouse click!

### ISSUE THREAD

**Issue by rrmotta** [igorescobar/jQuery-Mask-Plugin#374]
I'm trying to add jQuery-Mask-Plugin to a input form field that is filled with a html screen keypad. Is that possible with a .click function?!

**Comment by kafeltz** [comment]
I would do something like this, to simplify things:

$(field).mask(myMask);

Instead receiving input via keyboard, you can simulate as it's being used one.

$(button).on('click', function(event) { $(field).trigger(some_valid_key); });

Of course there will be some IFs to handle if the input is valid.
I used jQuery here in the example.

**Comment by igorescobar** [comment]
Cant help you without a jsfiddle.
