### ISSUE TITLE
Not work if input type is number

### ISSUE THREAD

**Issue by mumairali** [igorescobar/jQuery-Mask-Plugin#375]
I am working in hybrid app. Usually IP address contains numbers and dot. So I need only numbers keyboard to show to user. 

This is happened when input type is number. 

it clear the field after 099.099 (now press other number input field will be cleared).

Is this issue or am I doing wrong in settings. Kindly help me in this regards

**Comment by c01nd01r** [comment]
+1.

**Comment by tiesont** [comment]
If you're using

`<input type="number" />`

that's wrong. The number input if for "A control for entering a floating point number." Might help to [review the spec](https://www.w3.org/TR/html5/forms.html#number-state-%28type=number%29).

**Comment by igorescobar** [comment]
Guys, doesn't make any sense a need for mask for a number field. Its behaviour is mainly controled by the device.

**Comment by tiesont** [comment]
The only reason I can think of to mask it is for fallback purposes; if the user is using browser that doesn't support `type="number"`, you could polyfill the mask in to at least prevent the textbox from accepting anything but a number.

Of course, *this* specific issue seems to be more along the lines of misunderstanding what a number input is for.
