### ISSUE TITLE
Backspace not working properly for masked input textbox

### ISSUE THREAD

**Issue by sdkumar25** [igorescobar/jQuery-Mask-Plugin#376]
I am using jquery.mask.js for masking the textbox for mobile

Masking for canada zipcode 'A1A 1A1' was applied to textbox and it was working as expected, except the backspace or delete functionality.

After entering the input and trying to delete the specific letter was not working.

Trying to delete the character 'a'

![image](https://cloud.githubusercontent.com/assets/11739436/12509810/3a7d928c-c12b-11e5-9ef4-3c5032a754a6.png)

When i delete 'a' it also deletes the number '1'

Its working fine in all mobiles except backspace functionality.

JS fiddle : https://jsfiddle.net/qjtLbw44/1/

**Comment by igorescobar** [comment]
This happens because the number 1 is invalid on its new position so it get cleared.

**Comment by sdkumar25** [comment]
How to resolve this issue?

**Comment by igorescobar** [comment]
Upgrade your version, then, the last one it its supposed to be erased and not the fist one.

Enviado do meu iPhone
