### ISSUE TITLE
Utilizando reverse e tamanho fixo

### ISSUE THREAD

**Issue by mprandot** [igorescobar/jQuery-Mask-Plugin#380]
Eai pessoal!

Primeiramente, muito obrigado pelo plugin, ele é demais!!

Agora, estou com um problema aqui, preciso usar o `reverse : true` mas o campo tem que ter um limite fixo. ex:

`$(".input-money").mask("000.000,00", {reverse: true});`

Preciso que o usuário possa digitar só a quantidade que eu coloquei na máscara, comportamento que é igual ao `reverse : false`, como posso fazer isso? O plugin tem algo pronto? Não consegui encontrar na documentação, valeu! :D

**Comment by igorescobar** [comment]
Apenas coloque o maxlength no campo.
