### ISSUE TITLE
jQuery on('change') still does not work in Chrome

### ISSUE THREAD

**Issue by ba1dr** [igorescobar/jQuery-Mask-Plugin#381]
See also #3, #325, #310 and probably others.

Here is a fiddle: https://jsfiddle.net/eLw4xmee/
I type "234" and then press "Tab". No events raised.

Chromium: 48.0.2564.82 Ubuntu 15.10 (64-bit)
jQuery-Mask-Plugin 1.13.4

**Comment by igorescobar** [comment]
Still not working?

**Comment by ba1dr** [comment]
Unfortunately no :(

**Comment by igorescobar** [comment]
And now? :dancer:

**Comment by ba1dr** [comment]
Now it seems working!! Thanks! (dancing smile)
