### ISSUE TITLE
getCleanVal() returns undefined error

### ISSUE THREAD

**Issue by wainetam** [igorescobar/jQuery-Mask-Plugin#382]
> Uncaught TypeError: 
> Cannot read property 'getCleanVal' of undefined b.fn.cleanVal @ jquery.mask.min.js:13
> (anonymous function) @ custom.js:76
> n.event.dispatch @ jquery.js:4435
> r.handle @ jquery.js:4121

Using the cleanVal() method to return an unmasked value returns the error above. The id selector is a phone number input field.
$('#sender-phone-number').cleanVal()

As a workaround, I called unmask() first and then calling .val(). For example,
$('#sender-phone-number').unmask().val()

Hope this helps someone else.

**Comment by igorescobar** [comment]
Please, provide a functional jsfiddle. Seems to be working fine.
![screen shot 2016-02-14 at 2 09 33 pm](https://cloud.githubusercontent.com/assets/24032/13034115/7d97c21c-d324-11e5-8bd8-ab8f7d9c1040.png)

**Comment by wainetam** [comment]
https://jsfiddle.net/mje3v4jd/

On submit, cleanVal() returns the aforementioned error, while unmask().val() parses and submits the clean value.

**Comment by igorescobar** [comment]
I couldn't see when you define a mask to your field in your fiddlejs. The cleanVal method is defined when you define  .mask options.

**Comment by Chealer** [comment]
I confirm this on 1.3.4, except the summary should read "cleanVal() fails when applied to unmasked elements".

This can be worked around by replacing
`			jQuery(this).val(jQuery(this).cleanVal());`
with
```

			if (jQuery(this).data('mask') != undefined) {
				jQuery(this).val(jQuery(this).cleanVal());
			}
```

Note that the specifications of unmask() and cleanVal() are broken regarding the description of the selector argument.

**Comment by JuanMoralesMinor** [comment]
$('#inputNumeroSubcuenta').mask('AA-00000', {
        translation: {
            'A': {
                pattern: /[a-zA-Z]/, optional: false
            }
        }
});

$('#botonNumeroSubcuenta').click(function (e) { 
        e.preventDefault();
        let = numeroSubcuenta = $('#inputNumeroSubcuenta').cleanVal();
        console.log(numeroSubcuenta);
        
});

¡Funciona de manera correcta en @version: v1.14.16!
