### ISSUE TITLE
clearIfNotMatch in $.jMaskGlobals 

### ISSUE THREAD

**Issue by stccorp** [igorescobar/jQuery-Mask-Plugin#383]
Hello,  I need to replace my mask input library. During my initial test I noticed a feature that I need that this library does not seem to have.  For example if I have a zipcode mask like 00000-0000,  and I type 567 and leave the text field, my current mask library will delete the whole thing.  The good thing about it is that is it like a little data validator that does not let people leave invalid data.  I am willing to pay for this feature if it can be incorporated. Thank you

**Comment by igorescobar** [comment]
Take a look into the docs. That feature already exists.

Enviado do meu iPhone

**Comment by stccorp** [comment]
Hello, Thank you for your quick response.  I imagine you are talking about this
$('.clear-if-not-match').mask("00/00/0000", {clearIfNotMatch: true});

Is there any way to do this so that it applies to every mask without having to do it one at time(some kind of global definition? Since I am trying to use this library as a drop in replacement, having to declare this for each individual mask could make it troublesome.  I am talking about hundreds of files.
Thank you

**Comment by stccorp** [comment]
BTW,  Could you please tell me what is the difference between using 0s and 9s in the mask?  The only documentation I can find is this https://igorescobar.github.io/jQuery-Mask-Plugin/  and it does not mention why.  I see the examples with both numbers.  
Thank you

**Comment by stccorp** [comment]
Wait I found this $.jMaskGlobals , let me try it

**Comment by stccorp** [comment]
This does not seem to work
  $.jMaskGlobals = {
                        clearIfNotMatch: true
                };

**Comment by igorescobar** [comment]
@stccorp unfortunately, at this point  `clearIfNotMatch` option isn't inherited by `jMaskGlobals`.

Here is the meaning of each default mask digit:
![screen shot 2016-02-14 at 2 06 23 pm](https://cloud.githubusercontent.com/assets/24032/13034103/11e79c0e-d324-11e5-9e89-ff3f6fd2d0b9.png)

**Comment by stccorp** [comment]
I have modified the library to make it a parameter in the global.  It was a very simple fix.  Do you want me to give it to you?

**Comment by stccorp** [comment]
I uploaded my change to a branch.  Sorry If i did not do it correctly.  Is the first time ever I contribute here

**Comment by igorescobar** [comment]
Will be added in the next release
