### ISSUE TITLE
how to write us-zipode

### ISSUE THREAD

**Issue by stccorp** [igorescobar/jQuery-Mask-Plugin#384]
I want to do a us zipcode with clearIfNotMatch = true. My mask is 00000-9999
The problem is that if I type 12345, the text is cleared.  I am guessing I need to make the character - also optional.

So I try  00000r9999, but it does not work.  Is the translation wrong?
 $.jMaskGlobals = {
                        translation: {
                                'r': {pattern: /[-]/,optional: true}
                        }
                };

**Comment by igorescobar** [comment]
jsFiddle, please!
