### ISSUE TITLE
Mask money não salva como float e não faz matemática

### ISSUE THREAD

**Issue by thamayron** [igorescobar/jQuery-Mask-Plugin#385]
Igor boa noite, cara sou novo no desenvolvimento, to querendo fazer operação matemática com campo money do seu jquery, porém ele não permite quando utilizo a máscara.

Ele não funciona por causa da ',' na mask.
Teria alguma dica ou sugestão de como fazer?

Obrigado!

**Comment by igorescobar** [comment]
@thamayron o `parseFloat` do javascript só funciona se voce converter a sua string no formato americano. O objetivo do plugin é apenas fazer as mascaras, se você precisa fazer operações matemáticas usando o valor dos campos voce precisa converter os valores corretamente antes de fazer as operações.
