### ISSUE TITLE
mm/yy mask

### ISSUE THREAD

**Issue by clevrweb** [igorescobar/jQuery-Mask-Plugin#387]
How to mask cc exp mm/yy = only month/2 dig year? The pattern takes regex?

Thanks

**Comment by kafeltz** [comment]
"99/99"?

**Comment by clevrweb** [comment]
Ok, this I know but if I want to lock mm from 01 to 12 and yy from 16 to 26? It
takes regex?

Thanks






EmailSignature [cid:cm_1440613436002_1]

CONFIDENTIALITY STATEMENT

The information contained in this transmission may contain privileged and
confidential information. It is intended only for the use of the person(s) named
above.

If you are not the intended recipient, you are hereby notified that any review,
dissemination, distribution or duplication of this communication is strictly
prohibited.

If you are not the intended recipient, please contact the sender by reply e-mail
and destroy all copies of the original message.


Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.1.32&pv=5.1.1&source=email_footer_2] On Wed, Mar 02, 2016 at 1:39 PM, Ismael Santos Kafeltz < notifications@github.com [notifications@github.com] > wrote:
"99/99"?

—
Reply to this email directly or view it on GitHub
[https://github.com/igorescobar/jQuery-Mask-Plugin/issues/387#issuecomment-191391514] .[https://github.com/notifications/beacon/AKUoSH_HJOI4oTdPp9OhxIc3dQw9Nwcuks5ppedbgaJpZM4HnnEe.gif]

**Comment by igorescobar** [comment]
I recommend you to use a validation plugin instead of doing this but if you still want to do it.. here is an example:
https://gist.github.com/igorescobar/6450250
