### ISSUE TITLE
Caps no spaces

### ISSUE THREAD

**Issue by jasonwmatteson** [igorescobar/jQuery-Mask-Plugin#388]
I want to mask everything for that it accepts everything but spaces and is all caps.  There does not seem to be a way to do this.

Ideas?

**Comment by kafeltz** [comment]
All caps you suggest the person will use capslock or hold shift? Isn't a matter of CSS uppercased?
 And spaces, just use letters and not spaces.

it seems this question is better addressed in stackoverflow or similar.

**Comment by igorescobar** [comment]
Take a look into the docs... there is a bunch of examples using the `translation` option.
