### ISSUE TITLE
Shift of masking with Dragon Naturally Speaking

### ISSUE THREAD

**Issue by arpanchakarvarty** [igorescobar/jQuery-Mask-Plugin#390]
I am using jQuery Masked Input Plugin version 1.4.1 with "Dragon Naturally Speaking" tool. With keyboard the plugin is working fine but with DNS tool its shift masking to right side.

I have checked the plugin and below are my findings:

**function keydownEvent(e) {
                     if (!input.prop("readonly")) {
                         var pos, begin, end, k = e.which || e.keyCode;
                         oldVal = input.val(), 8 === k || 46 === k || iPhone && 127 === k ? (pos = input.caret(), 
                         begin = pos.begin, end = pos.end, end - begin === 0 && (begin = 46 !== k ? seekPrev(begin) : end = seekNext(begin - 1), 
                         end = 46 === k ? seekNext(end) : end), clearBuffer(begin, end), shiftL(begin, end - 1), 
                         e.preventDefault()) : 13 === k ? blurEvent.call(this, e) : 27 === k && (input.val(focusText), 
                         input.caret(0, checkVal()), e.preventDefault());
                     }
                 }**

In the above method **e.keycode** and **e.which** always coming undefined

Please help!

**Comment by igorescobar** [comment]
You are on the wrong place my friend. This is jQuery Mask Plugin and not jQuery MaskedInput.

Enviado do meu iPhone
