### ISSUE TITLE
Mask with set/varying number of characters

### ISSUE THREAD

**Issue by OClement** [igorescobar/jQuery-Mask-Plugin#392]
I need to be able to set a mask that will be valid for something like this:
`/^\d{5-9}|\d{12}|\d{16}$/`

In other words, that will accept either: 5 to 9 digits OR 12 digits OR 16 digits
Is this kind of pattern supported?

**Comment by igorescobar** [comment]
Hi @OClement 
This seems to be validation and not an mask.
