### ISSUE TITLE
Older safari browsers: mask placeholder option

### ISSUE THREAD

**Issue by Wendtly** [igorescobar/jQuery-Mask-Plugin#393]
This looks related to issue #135.

Using a mask with placeholders like
`$('#date_of_birth').mask('00/00/0000');`
I expect that if I type 12041963 that I should get "12/04/1963".
However, in older Safari on IOS, I get the following instead: "12/41/6390".

Any version of mobile Safari prior to 7.0 exhibits this behavior, so any stock iPhone <= 5, and any iPad that's not an Air or Mini model. [Recent market data here: https://david-smith.org/iosversionstats/, but the percentage is not insignificant]

(thanks to crossbrowsertesting.com)

**Comment by Wendtly** [comment]
So that it's clear what the issue is, here's an example of typing in a date (12/04/1963) where ^ indicates cursor position:

- 1^
- 12^
- 12/^0 (cursor moves left one character after 3rd character typed (first '/' position)
- 12/4^0
- 12/41/^0
- 12/41/^90 (cursor moves left another character after 6th character typed (second '/' position)
- 12/41/6^90
- 12/41/63^90

Hope this helps.

**Comment by igorescobar** [comment]
Please, provide an jsiddle.

**Comment by Wendtly** [comment]
I just loaded up your website (http://igorescobar.github.io/jQuery-Mask-Plugin/) in an older iPad, then tried the "Mask placeholder option" field. I then ran further tests through crossbrowsertesting.com, but always against your website

**Comment by Wendtly** [comment]
https://jsfiddle.net/1vz40o6v/1/
