### ISSUE TITLE
Mask translation not working

### ISSUE THREAD

**Issue by jasonwmatteson** [igorescobar/jQuery-Mask-Plugin#397]
I have this code:

```
$('#aFormField').mask('Z', {
					translation: {
						'Z': {
							pattern: '^[0-9A-Z]+$'
						}
					} 
				 });
```

The intent is to only allow uppercase letters and numbers.  It is not working.  Is the pattern incorrect?

**Comment by igorescobar** [comment]
Your regex is not supposed to be an string. Take a look into the docs, please: 
http://igorescobar.github.io/jQuery-Mask-Plugin/

`/[0-9A-Z]/` is enough. And you have to add more Z's to your mask otherwise it will only permit ONE digit.
