### ISSUE TITLE
Hard to use correctly with angular.

### ISSUE THREAD

**Issue by fdeslandes-wk** [igorescobar/jQuery-Mask-Plugin#400]
The library is hard to use with angular, because the mask behavior is not triggered when angular set a value in an input/element with ng-model.  An easy way to bypass this is giving access to a programmatic API to get the masked value without having to read or write the values in the DOM to do so.

This method can then be used in a formatter for ng-model.  I added simple code for this API in the following pull request, with one associated unit test :

https://github.com/igorescobar/jQuery-Mask-Plugin/pull/399

I also added related documentation in https://github.com/igorescobar/jQuery-Mask-Plugin/pull/402

I didn't build the project, assuming you will do so on feature release if you choose to integrate my changes.

**Comment by igorescobar** [comment]
#399

**Comment by igorescobar** [comment]
@fdeslandes-wk I've created one example on how to integrate (maybe its not the best). But would be great if you could fork my example and share yours with us:
https://github.com/igorescobar/jQuery-Mask-Plugin/issues/499
