### ISSUE TITLE
signle and double digits dates

### ISSUE THREAD

**Issue by maaking** [igorescobar/jQuery-Mask-Plugin#405]
hello,

how can i use masked date for
1/1/2015
and
1/11/2015
and
10/2/2015

if months is from 1 to 12 accept it .

i don't want to force user to use: 01 , 02 , 03 , 04 , 05 , 06 , 07 , 08 , 09

regards

**Comment by igorescobar** [comment]
Use this mask: `09/90/0000`. 9 means optional.
