### ISSUE TITLE
Avoid automatic mask characters when typing

### ISSUE THREAD

**Issue by smerinoh** [igorescobar/jQuery-Mask-Plugin#410]
Is there any way I can avoid mask characters to be written dinamically?

For example, if the mask is set to "9999.9" a dot will be displayed automatically when the fifth number is entered. Can I avoid it and force the user to enter the dot character?

**Comment by igorescobar** [comment]
Nope :(

**Comment by odahcam** [comment]
There's no reason to force the user to type it if you can enter it automatically for him/her. By the way, you can detect the keyCode by the keydown event and block unwanted entries.

**Comment by smerinoh** [comment]
There is no reason for it until your customer thinks that writting the separator character automatically when you type the fifth number is not what he considers functional.

I know there are other workarounds, but using as less customize code as posible would had been great.
