### ISSUE TITLE
Trigger mask programatically?

### ISSUE THREAD

**Issue by Jordan4jc** [igorescobar/jQuery-Mask-Plugin#411]
I have an issue where I need to set an input with `.val()` but it's not updating the mask. I have tried firing a `.change()` or `trigger('change')` but nothing seems to be working. I don't suppose it would be easy to have a method to tell the input to recalculate the value in the input with the mask supplied without having to unmask and remask?

**Comment by Jordan4jc** [comment]
Actually it looks like `keyup` does it. Though a native method would be cool

**Comment by arkRedM** [comment]
Keyup doesn't work as of now
