### ISSUE TITLE
Caracteres fixos em máscaras

### ISSUE THREAD

**Issue by odahcam** [igorescobar/jQuery-Mask-Plugin#412]
Seria interessante se fosse possível definir que os dígitos disponíveis ficassem visíveis na máscara. Por exemplo:
``` javascript
 $('.date').mask('00/00/0000');
```
Resulta em um input com os seguintes valores:

1. 0 dígitos `__/__/____`
2. 3 dígitos `12/0_/____`
3. 6 dígitos `12/04/20__`

ou:

1. 0 dígitos `mm/dd/yyyy`
2. 3 dígitos `12/0d/yyyy`
3. 6 dígitos `12/04/20yy`

Um plugin que faz isso: http://digitalbush.com/projects/masked-input-plugin/

<hr>

A título de comparação, neste exemplo o modelo atual seria:

1. 0 dígitos `         `
2. 3 dígitos `12/0       `
3. 6 dígitos `12/04/20  `
4. 8 dígitos `12/04/2016`

**Comment by igorescobar** [comment]
@odahcam but Its not going to happen anytime soon. :(

**Comment by odahcam** [comment]
Eu não estou a par do código fonte do projeto, mas eu posso ajudar. Há algum empecilho quanto à implementação dessa funcionalidade ou é simplesmente por falta de tempo?

**Comment by igorescobar** [comment]
@odahcam O problema é o peso que esta feature iria agregar ao core do projeto vs. o real valor que ela iria agregar. O uso do `placeholder` é mais que o suficiente.

**Comment by odahcam** [comment]
@igorescobar esse plugin exemplo que "linkei" tem apenas 4,22KB enquanto a versão mais minimizada que consegui fazer deste aqui foi 6,13KB. O tamanho do plugin não seria talvez uma questão de optimização do código? Mantendo em mente que o plugin exemplo não possui a funcionalidade "reverse".

Digo isto pois não só eu, mas vários usuários têm dificuldade para identificar a máscara e até mesmo utilizar, pois é como se caracteres fossem adicionados do nada na string.

Espero que não interprete como uma crítica negativa, mas sim construtiva.

Trago um exemplo, baseado na função **substr_replace** do **PHP** que alguém traduziu para JS. Utilizando o `placeholder` assim como sugerido, mas seguindo a minha ideia, podemos mesclar algo setado pelo usuário do plugin com as estradas do usuário final, olha só:

``` javascript
function substr_replace (str, replace, start, length) { 
  if (start < 0) {
    // start position in str
    start = start + str.length
  }
  length = length !== undefined ? length : str.length
  if (length < 0) {
    length = length + str.length - start
  }

  return [
    str.slice(0, start),
    replace.substr(0, length),
    replace.slice(length),
    str.slice(start + length)
  ].join('')
}


var placeholder = '__/__/____';
var entry = '11/0';

substr_replace(placeholder, entry, 0, entry.length);
```

O código acima dá a saída `"11/0_/____"`, assim como sugerido e possui **~**506 bytes, se o plugin for estruturado de forma bacana, não vai muito mais que isto para integrar a função.


Obrigado pela atenção Igor ;)

<hr>
JS `substr_replace` source: http://locutus.io/php/strings/substr_replace/

**Comment by igorescobar** [comment]
@odahcam você está analisando a coisa de forma muito rasa. jQuery Mask tem N features que o maskedInput não tem de forma que comparar apenas o source code de um do outro é uma metodologia um tanto quanto estranha.

**Comment by odahcam** [comment]
A questão é bem essa, eu não tenho conhecimento do src do plugin, gostaria de estudar, mas só se eu puder contribuir em algo, caso contrário seria tempo perdido.

De qualquer forma, se achar interessante, podemos ir adiante e é algo fácil para adicionar como método da classe e chamar baseado em um `if (options.force_placeholder === true)`. Como eu mencionei antes, se o plugin estiver bem estruturado, é fácil adicionar mais métodos sem causar grande impacto no tamanho final.

Se tu não achar a implementação algo realmente útil, vamos desconsiderar. Essa feature foi o que me fez demorar para migrar para o seu plugin, porém o que me fez chegar aqui foi o fato dele possuir suporte à currency e outras coisas ao mesmo tempo, economizando a necessidade de um novo plugin e mais arquivos pra carregar.
