### ISSUE TITLE
type="number" Firefox and zero "0"

### ISSUE THREAD

**Issue by tonibiocic** [igorescobar/jQuery-Mask-Plugin#415]
If you try to enter zero after any number in Firefox it will fail to display correct number when you are using type="number".

http://jsfiddle.net/u1xhkL0d/

**Comment by tiesont** [comment]
Why are you trying to mask a number input? The browser's built-in functionality already limits the characters that the control accepts.

**Comment by igorescobar** [comment]
@tiesont is right.
