### ISSUE TITLE
mask money bug value

### ISSUE THREAD

**Issue by pedrorossif** [igorescobar/jQuery-Mask-Plugin#416]
When i used the mask money and type only "1", it seems that the value is 1(integer), but truly is 0.01. How can i fix this?
The mask apply just after i type 3 numbers, like "1,11". I want to type "1" and the value need to be "0.01".

**Comment by igorescobar** [comment]
@pedrorossif if it doesn't fit your needs, use a currency-specific plugin.

**Comment by pedrorossif** [comment]
i've already find, you can learn with him if you are not so dumb.
https://github.com/plentz/jquery-maskmoney

**Comment by igorescobar** [comment]
@pedrorossif LOL
