### ISSUE TITLE
Mask for decimal numbers

### ISSUE THREAD

**Issue by ricardojlrufino** [igorescobar/jQuery-Mask-Plugin#417]
You can use a mask to create decimal numbers, something like:
http://robinherbots.github.io/jquery.inputmask/?

The main thing is to leave optional decimal places

**Comment by tiesont** [comment]
Have you reviewed the documentation? http://igorescobar.github.io/jQuery-Mask-Plugin/

**Comment by ricardojlrufino** [comment]
resolved, was using the mask with '0' instead of '9'
