### ISSUE TITLE
Problem with reverse mask

### ISSUE THREAD

**Issue by marcoskichel** [igorescobar/jQuery-Mask-Plugin#419]
Hello Igor,

Using a mask for money purpose in an Angular 2 app, with the exact same pattern of the example page have a weird behaviour.

The input displays the correct value, but the submitted value have the comma in the wrong position.

example: 
Input value: 9,99
Submitted value: 99,9

Happens only with the `reverse `property.

**Comment by igorescobar** [comment]
https://github.com/igorescobar/jQuery-Mask-Plugin#problems--bugs

**Comment by gilderlan** [comment]
+1
