### ISSUE TITLE
.mask on future selectors

### ISSUE THREAD

**Issue by Durrasell** [igorescobar/jQuery-Mask-Plugin#420]
how to initialize plugin .mask on future selectors.  $('body').delegate(selector, 'mask') does not work

**Comment by igorescobar** [comment]
<img width="795" alt="screen shot 2016-06-14 at 11 57 27" src="https://cloud.githubusercontent.com/assets/24032/16040403/33b5a29c-3227-11e6-806a-017a4e390c53.png">
