### ISSUE TITLE
Add placeholder data-mask attribute

### ISSUE THREAD

**Issue by luisabreu** [igorescobar/jQuery-Mask-Plugin#421]
Any hints at why the data-mask-placeholder is not supported? Looking at the code it seems like it should be easy to add...

Thanks

**Comment by igorescobar** [comment]
```javascript
 $('.placeholder').mask("00/00/0000", {placeholder: "__/__/____"});
```

**Comment by luisabreu** [comment]
Hello.
I was talking about processing the html data-mask-placeholder from the html element (similar to the way it's done to others).

**Comment by bassena** [comment]
+1

**Comment by eliasrosa** [comment]
+1
