### ISSUE TITLE
the jquery.mask is not working properly in safari

### ISSUE THREAD

**Issue by jbalam82** [igorescobar/jQuery-Mask-Plugin#422]
you are going to be able to reproduce the issue launching this page using safari and trying to type something in the phone number text box.
https://igorescobar.github.io/jQuery-Mask-Plugin/

**Comment by igorescobar** [comment]
@jbalam82 What isn´t working? Just tested and everything is working fine.

**Comment by jbalam82** [comment]
Is not working on safari, launch the url in safari and try typing something in the us format phone number and you will see the caret is moved back and the digits are misplaced as you type them.

**Comment by tiesont** [comment]
@jbalam82 It would your cause immensely to be more specific, as Safari is available in multiple versions, on multiple operating systems and devices. If you can't demonstrate what's not working, it's not an issue.

**Comment by jbalam82** [comment]
![issuesafari](https://cloud.githubusercontent.com/assets/19917433/16057720/278c57be-3230-11e6-871b-9c9ba3633036.png)

please find the image attached to this comment.
