### ISSUE TITLE
Erro Mobile Devices

### ISSUE THREAD

**Issue by ramiralves** [igorescobar/jQuery-Mask-Plugin#423]
Attention! This framework does not work on mobile devices.

**Comment by igorescobar** [comment]
@ramiralves Could you explain what is happening or this is all you can contribute?

**Comment by ramiralves** [comment]
Igor,

I can´t input dates, the keyboard it´s block. Example:

<input id="weigth" name="weigth" type="tel" placeholder="Weigth Ex.: 70,00"
class="form-control decimal" minlength="5" maxlength="6" required >



Atenciosamente,

Ramir Alves.

2016-06-15 8:50 GMT-03:00 Igor Escobar <notifications@github.com>:

**Comment by igorescobar** [comment]
@ramiralves Any field different than  `type=text` the mobile browser has full control over it. Which means that you can control it by Javascript. In other words there is nothing we can do to help you if you need to use a field `type=tel`. Also... looking at your example you shouldn't be using `type=tel` to input weight that doesnt make much sense.

**Comment by ramiralves** [comment]
Test on mobile devices with: text, cel, date, number or other type... and
you´ll see the same erro.

Atenciosamente,

Ramir Alves.

2016-06-15 10:14 GMT-03:00 Igor Escobar <notifications@github.com>:

**Comment by igorescobar** [comment]
@ramiralves opened: http://igorescobar.github.io/jQuery-Mask-Plugin/ using Safari for iPhone. Works fine. 

Or... You can read this section: https://github.com/igorescobar/jQuery-Mask-Plugin#problems--bugs

And I could help you with your problem. Sounds good?

**Comment by igorescobar** [comment]
@ramiralves Vou falar em português para facilitar o entendimento.

Como eu disse anteriormente. Todos os campos de tipo diferente de "text", ou seja, todos estes que você mencionou, são controlados PELO DEVICE. Não há nada que eu possa fazer.

**Comment by ramiralves** [comment]
Boa tarde Igor.

Sim, compreendo que há limitações e que são mtos dispositivos.

Me desculpe se o que postei pareceu ser ofensivo, tive o intuito apenas de
alerta sobre essa condição.





Atenciosamente,

Ramir Alves.

Em 15 de junho de 2016 15:08, Igor Escobar <notifications@github.com>
escreveu:
