### ISSUE TITLE
using a flexible phone reverse mask

### ISSUE THREAD

**Issue by mauacs** [igorescobar/jQuery-Mask-Plugin#424]
Hi,

In a attempt to create and use a flexible reverse phone number mask I got this specific problem. The mask appears to uncorrect position the first literal character - an open parenthesis - just after the last, eleventh, possible digit. Only after I continue to type another digit, the mask rearrange the input.

See: http://jsfiddle.net/maurissio/fvgfbrv8/4/

**Comment by mauacs** [comment]
You should have, in line 303:
`buf[addMethod](lastMaskCharDigit);`

Shouldn't you?

**Comment by DieguitoBueno** [comment]
Hi guys, is this possibility to have the digits starting from the end fixed ?

**Comment by igorescobar** [comment]
@DieguitoBueno Is this a real issue for you or are you just hacking around?

**Comment by igorescobar** [comment]
+ @mauacs
