### ISSUE TITLE
Documenting: URL to Russian tutorial is outdated

### ISSUE THREAD

**Issue by ddrozdik** [igorescobar/jQuery-Mask-Plugin#425]
Hi,

Please remove link to Russian tutorial http://zencoder.ru/javascript/jquery-mask-plugin/ from Readme, because this URL is outdated.

**Comment by igorescobar** [comment]
@ddrozdik seems to be working, no?

**Comment by ddrozdik** [comment]
Yes, it working now. But it was not working some time ago.
