### ISSUE TITLE
can't select text programatically in masked inputs

### ISSUE THREAD

**Issue by tiancsb** [igorescobar/jQuery-Mask-Plugin#428]
The plugin prevents any masked input to be selected after a focus.
if the input "#data-doc" is masked and you try to select its content like this:

`$("#data-doc).focus().select()`

The selection automatically undoes itself. I tried selecting() after a timeout but the results are unpredictable at best.

**Comment by igorescobar** [comment]
https://github.com/igorescobar/jQuery-Mask-Plugin#bugs
