### ISSUE TITLE
"Hack" solution to support decimal values

### ISSUE THREAD

**Issue by italoosorio** [igorescobar/jQuery-Mask-Plugin#430]
I like this mask plugin, it works very well for what it is intended. However I needed it to support fixed decimal number. I didn't want to add an extra plugin to my code just for that extra functionality. So, I decided to "hack" the code in a no clean way. Sorry to any "academic" coder.

The problem with decimals is that it is difficult to differentiate if the mask if for a plain integer number or for a decimal number, this specially considering international formats. A mask **#,###.###** can be an integer, or a 3 decimal number depending where and how is it used.

The other problem is that the plugin does not format the receiving numeric value to match the mask. For example in a mask **#,###.00** the number **1234** will result on **12.32**, **1234.5** will become **123.45**, which is not correct in a numeric way.

My solution is to add extra an character at the end of the mask to set it as decimal. I use the character **D** (Decimal). The mask for a decimal value will be **#,###.00D** for example.

When the plugin finds the mask ending on **D** it defines the value a decimal value. The last symbol become the decimal marker, in the example it will be the dot. And the number or numeric characters between the decimal maker and the **D** sets the decimal range, in this case 3. With this information the plugin pre-format the receiving value, to the expected decimal, before applying the mask.

Until now it is working for me. I don' have much time to fork this project so I am including the code with the "hack" modification for any one to check or use at their own risk.

This is a "hack" solution for an specify scenario which may not work for others. I don't pretend to spend time justifying or discussing about this solution.

[jquery.mask.js.txt](https://github.com/igorescobar/jQuery-Mask-Plugin/files/347057/jquery.mask.js.txt)

**Comment by igorescobar** [comment]
@italoosorio I appreciate this but for the sake of understanding could you submit this in a form of a PR? Would help me a lot to understand what you did and to discus further changes/suggestions/questions.

**Comment by igorescobar** [comment]
@italoosorio I tried to understand your patch by copying and pasting but unit tests weren't working and seems like you was using a lot of not-native javascript functions too. Let me know if you are still interested on this.
