### ISSUE TITLE
Masked Input Characters not Working in Android Devices

### ISSUE THREAD

**Issue by jonnyserra** [igorescobar/jQuery-Mask-Plugin#431]
Hi i'm having a problem with this plugin on Android devices where my mask allows me to write everything fine on Desktops, but when i switch over to Android devices i can't type any characters, only digits... I've already opened a question about this on Stackoverflow.com hoping it was something i was missing but it appears to be an actual bug in the code somewhere and so i'm opening this issue, if anyone's had this problem before and can help me i'd greatly appreciate it.

**::My Stackoverflow question regarding this issue with a jsFiddle::**
http://stackoverflow.com/questions/38207663/jquery-masked-bugs-on-android

**Comment by Sylphony** [comment]
Which Android version are you using?  It is able to type out the characters on my 2.3.4 and 6.0 just fine.

**Comment by jonnyserra** [comment]
@Sylphony 5.0

**Comment by igorescobar** [comment]
Duplicated take a look to FAQ.
