### ISSUE TITLE
Mudar a chamada da função.

### ISSUE THREAD

**Issue by pedrosalpr** [igorescobar/jQuery-Mask-Plugin#433]
@igorescobar Como eu faço para alterar a chamada da função, em vez de chamar $("#atributo").mask() para  $("#atributo").mask2(), para não dar conflito com outro plugin?

**Comment by igorescobar** [comment]
@pedrosalpr boa pergunta :)

**Comment by maurcarvalho** [comment]
Fala @pedrosalpr, a pergunta é antiga mas vou responder, quem sabe ainda pode ajudar.

Voce tem alguns caminhos, uns menos obscuros do que os outros.

O caminho mais lógico, seria realizar um fork deste projeto e mudar a clousure que faz o export da função mask para mask2. Voce pode dar uma olhada aqui: https://github.com/igorescobar/jQuery-Mask-Plugin/blob/master/src/jquery.mask.js#L465

O modo mais "obscuro" seria importar o jquery.mask.js, exportar uma nova clousure assim:
`$.fn.mask2 = $.fn.mask`
E após isso, importar o seu outro plugin. Quando isso acontecer, o plugin antigo vai assumir a $.fn.mask e voce ainda terá este plugin em $.fn.mask2

Enfim, eu tentaria escolher o melhor plugin e seguir com ele. Caso tenha alguma `function` em que esse projeto ainda não tem suporte, talvez seria a oportunidade de enviar um PR 📦 

Valeu :)
