### ISSUE TITLE
HTML Notation w/translation option

### ISSUE THREAD

**Issue by edinsonVivas** [igorescobar/jQuery-Mask-Plugin#437]
I wanna put in my website a input w/html notation jquery mask trying it:

`<input class="identification" type="text" placeholder="" data-mask="S-00000000-Z" data-mask-translation="S: {pattern: /[VEJG]/}, Z: {pattern: /[0-9]/, optional: true}" />`

or 
`
<input class="identification" type="text" placeholder="" data-mask="S-00000000-Z, translation{S: {pattern: /[VEJG]/}, Z: {pattern: /[0-9]/, optional: true}}" />`

**Comment by igorescobar** [comment]
Sorry @edinsonVivas for advanced scenarios use the javascript notation.

**Comment by nightrider77** [comment]
What if I dynamically generate text inputs with prefixes like "US-"? S letter is being treated as a pattern, and no possibilities to escape it... Use of javascript notations is too complicated for such a simple task.

**Comment by nightrider77** [comment]
I solved by using cyrillic letters, like **ц** states for digits, **б** - for letters, **в** - letters and digits, etc ... :)

**Comment by igorescobar** [comment]
The translations object is completely customizable. You can make it work
with any digit you want and even remove the S and replace by something else.

Cheers.
