### ISSUE TITLE
Alpha Numeric Mask

### ISSUE THREAD

**Issue by austinstudio** [igorescobar/jQuery-Mask-Plugin#439]
I want to allow a user to put in any alpha or numeric but not special characters.  The input they put in can be any length.  I tried a bunch of stuff but nothing works.

  $('.vAlphaNumeric').mask('A#');
  $('.vAlphaNumeric').mask('Z#', {translation:  {'Z': {pattern: /[a-zA-Z0-9]/}}});
  $('.vAlphaNumeric').mask('Z#', {translation:  {'Z': {pattern: /[a-zA-Z0-9]/, recursive: true}}});

What keeps happening is that it will allow a single alpha but then only numbers or it will make me put an alpha in between each number.

Any ideas?

**Comment by austinstudio** [comment]
I seemed to have fixed it.

I used the following:

    $('.vAlphaNumeric').mask('Z',{translation:  {'Z': {pattern: /[a-zA-Z0-9]/, recursive: true}}});

**Comment by luisDanielRoviraContreras** [comment]
es mejor agregar otra letra para quitar un bug de salto de letra algo asi 
`
$("#id-class-tag").mask('ZZ',{translation:  {'Z': {pattern: /[a-zA-Z0-9\s]/, recursive: true}}});
`
