### ISSUE TITLE
Mudança de máscara dinâmica ao colar 

### ISSUE THREAD

**Issue by germanolucas** [igorescobar/jQuery-Mask-Plugin#44]
Configurei um input text para mudar a máscara dinamicamente ao digitar um número de CPF ou CNPJ. O campo é configurado por padrão com a máscara do CPF, aí, dependendo da quantidade de números digitados, a máscara muda dinamicamente. Ao colar um número CPF (11111111122) utilizando o BOTÃO DIREITO DO MOUSE a máscara formata corretamente, no entanto, se inicialmente colarmos um número de CNPJ (11111111000122), como a máscara inicial é a do CPF, o plugin formata o número CNPJ colado com a máscara do CPF, truncando o restante (mostrando assim: 111.111.110-00). Se colarmos o mesmo número CNPJ utilizando agora o CTRL+V a máscara muda, mas, por algum motivo também trunca o número, ficando assim: 11.111.111/0001.

**Comment by danellaclaudioluiz** [comment]
como foi resolvido igor?

**Comment by igorescobar** [comment]
Time solved it :)


- Igor
