### ISSUE TITLE
Mask removed on field when setting value with 'val' function

### ISSUE THREAD

**Issue by jarodsmk** [igorescobar/jQuery-Mask-Plugin#441]
Hey there,
Currently tried using this plugin for money fields on a rather complex front end and found that as soon as the value of the field is set using the JQuery .val function, the mask is removed.

```
var selector = "#someID";
$(selector).val(1000000);
$(selector).mask("#,##0.00", {reverse:true});
//Output is shown as: 1,000,000
...

var value = $(selector).cleanVal();
//Mask will be removed on next line
$(selector).val(1000000);
//Output is shown as: 1000000
```
The mask is removed after the last line has executed.

Is there a correct way to update the field programatically?

Regards,
Jarod

**Comment by jarodsmk** [comment]
Updated this with my new findings

**Comment by thiagogsr** [comment]
+1

**Comment by jarodsmk** [comment]
@thiagogsr 

The workaround I had on my frontend was to create a hidden field with the following properties:

- When the masked field is changed, the hidden field is changed to the cleanVal of the masked field

- When the page is loaded, the hidden field gets the actual value from the backend, and that is then propagated to the masked field

- Finally, when the form is saved, the value from the hidden field is used on your model, not the masked field.

Hope this helps, would be nice if there was a solution for this in the plugin though :)

**Comment by igorescobar** [comment]
Hi there @jarodsmk @thiagogsr.

This is pretty simple. You are using a native jQuery function to set the field's value. The problem here is that jQuery or ther browser itself doesn't trigger any kind of  `event` when you pragmatically change field value. The workaround for this in this case it is to trigger the event yourself. 

*i.e:*
```javascript
$('.date').val('').trigger('input');
```

**Comment by thiagogsr** [comment]
`unmask` works for me.

```js
$(selector).unmask().val(123.00); # output 123,00 and the mask still working
```

**Comment by artem0793** [comment]
Hi all! I have found solution!
You are need to set watchDataMask is true
For example:
```js
$element.mask('#.##0,00', {
        reverse: true,
        watchDataMask: true
      });

$element.val(100000);
$element.trigger('input'); // Will be display 1.000,00
```

**Comment by UnalYeten** [comment]
```
$element.mask('(~99) 999 99 99', {
               placeholder: "_",
            });
$element.val("5123456789").focus().blur(); // will be display (512) 345 67 89
```

**Comment by VitaliyDemchuk** [comment]
There are solutions for how to fix this in Vue.js ?

**Comment by madsongr** [comment]
What worked for me when I get data from database:

```
$('#foo').val(data.foo).mask('999.999.999-99', {
    watchDataMask: true
})
```

`reverse: true` and `trigger()` didn't work
