### ISSUE TITLE
Cant percent not in reverse with % sign

### ISSUE THREAD

**Issue by DusanMilko** [igorescobar/jQuery-Mask-Plugin#443]
I want to use the the percent mask but not in reverse but always have the % symbol at the end of the input. How can I do this??

If the mask isnt in reverse then % doesnt appear till its fully filled out.
If in reverse, % is always there but theres issues when typing into the input

Also hitting a 
Uncaught RangeError: Maximum call stack size exceeded
with the percent mask

**Comment by igorescobar** [comment]
https://github.com/igorescobar/jQuery-Mask-Plugin/blob/master/README.md#problems-or-questions
