### ISSUE TITLE
Samsung Android Keyboard Not Working Well

### ISSUE THREAD

**Issue by malcusimhof** [igorescobar/jQuery-Mask-Plugin#447]
I´m having problems with Samsung keyboard. When you try to type on numeric fields (like CPF or Telephone) after the first character the focus stays in second, no matter how much characters you have already typed.

If switch the keyboard to Swiftkey for example the problem does not appear.

I´m not sure if this is a issue with jQuery-Mask-Plugin or with Samsung keyboard.

**Comment by andre-mendes** [comment]
I'm having the same problem :( .... did you fixed it? :D

**Comment by timschwallie** [comment]
this looks similar to an earlier issue:
https://github.com/igorescobar/jQuery-Mask-Plugin/issues/135

**Comment by pmccloghrylaing** [comment]
I think this is the same as #432

**Comment by andre-mendes** [comment]
Hey guys, I fixed by changing the input type from "text" to "tel" :)

**Comment by igorescobar** [comment]
https://github.com/igorescobar/jQuery-Mask-Plugin/blob/master/README.md#problems-or-questions

**Comment by igorescobar** [comment]
Guys could you test this version, please?
https://github.com/igorescobar/jQuery-Mask-Plugin/blob/android-fix/src/jquery.mask.js
