### ISSUE TITLE
Add typings to support for typescript 

### ISSUE THREAD

**Issue by avidenic** [igorescobar/jQuery-Mask-Plugin#449]
Hello,

it would be great if this plugin had typings so we could work with it using Typescript. 

Either that or maybe add typings to https://github.com/DefinitelyTyped/DefinitelyTyped

What do you think?

Regards,
Anže

**Comment by sergiomichels** [comment]
@avidenic Did you created it? If not I probably will :)

**Comment by sergiomichels** [comment]
Does it looks ok?

```
/// <reference path="../typings/globals/jquery/index.d.ts" />

declare namespace jquery.mask.plugin {
  interface JQueryMaskTranslation {
    pattern: RegExp;
    optional ?: boolean;
    recursive ?: boolean;
  }

  interface JQueryMaskOptions {
    maskElements?: string;
    dataMaskAttr?: string;
    dataMask?: boolean;
    watchInterval?: number;
    watchInputs?: boolean;
    useInput?: boolean;
    watchDataMask?: boolean;
    byPassKeys?: number[];
    translation?: {[key: string] : JQueryMaskTranslation};
    onKeyPress?: (value: any, event: JQueryEventObject, element: JQuery, options: JQueryMaskOptions) => void;
    onChange?: (value: any, event: JQueryEventObject, element: JQuery, options: JQueryMaskOptions) => void;
    onComplete?: (value: any, event: JQueryEventObject, element: JQuery, options: JQueryMaskOptions) => void;
    onInvalid?: (value: any, event: JQueryEventObject, element: JQuery, invalid: boolean, options: JQueryMaskOptions) => void;
  }
}

interface JQuery {
  jMaskGlobals: jquery.mask.plugin.JQueryMaskOptions;
  mask(format:string|((value: any) => string), options?: jquery.mask.plugin.JQueryMaskOptions) : JQuery;
}
```

**Comment by avidenic** [comment]
Hey,

I've created them a while a go, but did not commit, sorry. This is my implementation:

`
interface MaskPattern {
    pattern?: RegExp;
    recursive?: boolean;
    optional?: boolean;
    fallback?: string;
}

interface MaskTranslation {
    [key: string]: MaskPattern | Object;
    placeholder?: string;
}

interface MaskOptions {
    maskElements?: string;
    dataMaskAttr?: string;
    dataMask?: boolean;
    watchInterval?: number;
    watchInputs?: boolean;
    watchDataMask?: boolean;
    byPassKeys?: number[];
    translation?: MaskTranslation;
    selectOnFocus?: boolean;
    reverse?: boolean;
    clearIfNotMatch?: boolean;
    onComplete?(value: Object, e: Event, $element: JQuery, options: MaskOptions): void;
    onKeyPress?(value: Object, e: Event, $element: JQuery, options: MaskOptions): void;
    onChange?(value: Object, e: Event, $element: JQuery, options: MaskOptions): void;
    onInvalid?(value: Object, e: Event, $element: JQuery, options: MaskOptions): void;
}

interface JQuery {
    /**
     * Applies the mask to the matching selector elements.
     * @param mask should be a string or a function.
     * @returns The element.
     */
    mask(mask: (value: string) => string | string): JQuery;

    /**
     * Applies the mask to the matching selector elements.
     * @param mask  should be a string or a function.
     * @param options should be an object.
     * @returns The element.
     */
    mask(mask: string, options: MaskOptions): JQuery;

    /**
     * Seek and destroy.
     * @returns The element.
     */
    unmask(): JQuery;

    /**
     * Gets the value of the field without the mask.
     * @returns Value without the mask.
     */
    cleanVal(): string;

    /**
     * Gets masked value programmatically
     * @returns Masked value.
     */
    masked(value: string): string;
}
`
I don't like the use of "any", linter does not agree with that =) But I like namespacing and JqueryEvent. Let's merge it =)
