### ISSUE TITLE
Help fix inuput type number

### ISSUE THREAD

**Issue by MrMegamind** [igorescobar/jQuery-Mask-Plugin#450]
Hey buddy
If i try to mask for a USA number on <input type="number' ... it gives error. Can you please help fix this ?

Thank you in advance

MAK

**Comment by smileytechguy** [comment]
The number field doesn't allow non-numeric characters.  Also, please give us a traceback and the code you are using

**Comment by MrMegamind** [comment]
hi
I am doing 
<input type="number" id="usnum"/>

$(document).ready(function(){
        $('#usnum').mask('(000) 000-0000');
}

I understand now that it does not work because number can not show brackets like "("

But then how do I show a numeric pad on phone while applying this mask to it ? If I do <input type="text" it shows full keyboard not numeric only.

**Comment by clifforama** [comment]
Possibly related: `<input type="number" data-mask="00" ...>` allows unlimited hyphens, at least in Chrome. In Edge, it allows unlimited non-numeric characters.

**Comment by igorescobar** [comment]
Guys, fields like `number`, `date`, `email` or anything different than `text` it is completely handled by the `browser` via javascript I can't control its behaviour. So basically if your not using type `text` the plugin can't interfere on what the browser is doing with it so even if I wanted to put text in a NUMBER field the browser wouldn't allow. So there isn't much I can do to help.

**Comment by hotwheel16** [comment]
You can use `inputmode="foo"` to pull up a number only mobile keyboard layout.

eg. `<input type="text" inputmode="decimal" />` or `<input type="text" inputmode="numeric" />`

See: https://css-tricks.com/better-form-inputs-for-better-mobile-user-experiences/
