### ISSUE TITLE
Inserts incorrect value on paste

### ISSUE THREAD

**Issue by heaven** [igorescobar/jQuery-Mask-Plugin#451]
Hi, I have the next mask: `+099 (000) 000-0000` and the placeholder: `+_ (___) ___-____`. The country code may vary from 1 to 3 numbers but when the user inserts `+11235555555` it gets `+112 (355) 555-55` instead of `+1 (123) 555-5555`.

So the number is aligned incorrectly – it should fill all the required numbers first putting the rest to the optional spots.

So the algorithm for copy/paste would be:
- insert the value
- align like this is done now
- check if there are missing required numbers but set those that aren't required
- move the value to the right, freeing the optional spots and filling those required

**Comment by igorescobar** [comment]
@heaven I understand you but this is exactly what is suppose to happen. The algorithm for the copy paste is the same used as the one used when the user types things. So instead of trying to guess that should be the right behaviour for each scenario I just fill the chars in the position/order as the mask. If what was copied had the formatation like at least like "+1 (123) 5555555" the plugin would know were to put things.

**Comment by heaven** [comment]
Hi, I think the algorithm is not the best and is not exactly what is supposed to happen. With this mask `+099 (000) 000-0000` users have to manually enter "(" if they need to enter `+1 (123) 555-5555`, so basically this doesn't work as it should.

When I am typing +111 (123) 456-7890 the algorithm should be as follows:
* `1` => `+1`
* `11` => `+1 (1`
* `111` => `+1 (11`
* `1111` => `+1 (111)`
* `11112` => `+1 (111) 2`
* `111123` => `+1 (111) 23`
* `1111234` => `+1 (111) 234`
* `11112345` => `+1 (111) 234-5`
* `111123456` => `+1 (111) 234-56`
* `1111234567` => `+1 (111) 234-567`
* `11112345678` => `+1 (111) 234-5678`
* `111123456789` => `+11 (112) 345-6789`
* `1111234567890` => `+111 (123) 456-7890`

So the idea is that it should *skip* the optional numbers first and shift the entire input later, if required/possible (if the input is long enough). Then with the mentioned mask users can enter numbers with different country code length easily and in the same way for both `+1 (xxx) xxx-xxxx` and for `+111 (xxx) xxx-xxxx`.

Currently I have to change the mask and reinitialize the input every time the country select has changed.

**Comment by igorescobar** [comment]
@heaven I understood. As I said, the algorithm is generic and its not optimised for case X ou Y. it handle logic pretty much the same way for every mask you choose. I'm not sure if this would be true for all scenarios. Would be handy if you could suggest a change via a PR because right now I just can't focus on this.

**Comment by heaven** [comment]
True, may be worth to use different translation for this thing, so this does not break existing setups, e.g. `+1?? ...`. Can't promise that I will be able to work on this soon, but I already have this in my TODO.

**Comment by igorescobar** [comment]
@heaven I'm open to ideas :)

**Comment by heaven** [comment]
While I didn't have time to work on this just wanted to let you know that users are complaining on this issue a lot, so I think this is a bug, the library provides optional input, but this doesn't work properly.

**Comment by igorescobar** [comment]
@heaven that's weird you are the first one complaining about this.

**Comment by heaven** [comment]
And what is weird in that? :) The plugin didn't work for phone numbers with variable country code length. We have the mask `+099 (000) 000-0000` and if a user from US enters a number the code is just one digit, so users end up with something like this: `+161 (799) 999-99` instead of this: `+1 (617) 999-9999`. Some of them tried to enter "+100 (617) ...-...." As on my opinion this is a pretty valid use case.

The solution for us could be to re-initialize the plugin with a new mask on each country change event (we have a country dropdown), but we then have to maintain a list of masks for every country, which is painful.

**Comment by igorescobar** [comment]
@heaven Yeah, I see. Now what the user could do is just type the `(` to break to move to the next block. After the `+0` the user can type the `(` any time and the plugin will move on the put the following digits on the right place. Do you have any other plugin that works the way you think it should?

Thanks for helping me out.

**Comment by heaven** [comment]
I don't know any plugin like that. I don't think this plugin should work the way I described. Well, it would be cool if it worked like that, but this wouldn't solve the phone number formatting problem. Yeah, if they enter "(" that would work, unfortunately not all users realize this.

**Comment by igorescobar** [comment]
@heaven A non-related question... if the user is already informing the country why they need to inform the country code again? The code could be "pre-filled" in this case if you want to let the user change it.

But anyways... 
a. you follow my suggestion above.
b. change the mask as the user change the country.
c. You can change your initial mask to: `+0 (000) 000-00009` and you can check the value length as they types. If the length hits the `9` you can change mask to `+099 (000) 000-0000` or something like that.

Just ideas... :/

**Comment by heaven** [comment]
As for now we did exactly what you suggested and do store the country code separately, so users only have to enter phone numbers. The option "c" also sounds interesting. I think we can close this issue as I don't think the solution I proposed will solve the problem. Thanks for your help and ideas.

**Comment by igorescobar** [comment]
no problem @heaven! I'm glad we "kinda" sorted this our :rofl:
