### ISSUE TITLE
have typing input fall within placeholder regions

### ISSUE THREAD

**Issue by jersingh** [igorescobar/jQuery-Mask-Plugin#452]
If I have a phone placeholder mask as follow: (___) (__)-(____)

If would be nice if clicking into the control places the cursor to the right of the very first parenthesis. As it stands now, my cursor blinks to the left and outside the placeholder.

In addition, what would also be great is to keep the mask placeholder tokens present as the user types through the mask.

digitalbush mask does this but jQuery-Mask-Plugin has more options and much more control.

**Comment by igorescobar** [comment]
I'm sorry @jersingh if this is important to you I recommend you to use this library that you mentioned. I have not plans to implement this. Just because all the edge cases it would make our code base increase considerably. The only thing available is use the HTML5 attribute `placeholder`.
