### ISSUE TITLE
How can you have percentage values

### ISSUE THREAD

**Issue by charalamposc** [igorescobar/jQuery-Mask-Plugin#453]
Is it possible to allow the values 0 to 100 with 2 decimal places?

For example the regex would be "#,###.##|100.00" (or something like that), but I don't know if this is possible with the mask functionality you are using.

**Comment by smileytechguy** [comment]
idk, im sure you could to just ##.##?

**Comment by tiesont** [comment]
According to the basic examples, it would be 

`$('.percent').mask('##0,00%', {reverse: true});`

with the assumption that your selector is elements with the class `percent`.

**Comment by charalamposc** [comment]
This is ok, but I needed to allow values from 0 to 100, that means, 100,01 is an invalid value and should not be allowed.

**Comment by igorescobar** [comment]
Sorry guys:
https://github.com/igorescobar/jQuery-Mask-Plugin/blob/master/README.md#problems-or-questions

**Comment by charalamposc** [comment]
Fair enough! :)

**Comment by romuloMendes** [comment]
I understand that this is doubtful and old, hahaha.
Solution will help if others have the same problem.

```
function setPercentageMask() {
    let input = $('.percent');
    input.mask('##0,00', {reverse: true});
    input.bind("change keyup", function() {
        isBetweenPercentage($(this));
    });
}

function isBetweenPercentage(input) {
    let myNumber = (input.val()) ? parseFloat(input.val()) : 0;
    (myNumber.isBetween(0, 100.00)) ? myNumber : input.val('100,00');
}

if (typeof(Number.prototype.isBetween) === "undefined") {
    Number.prototype.isBetween = function(min, max, notBoundaries) {
            var between = false;
            if (notBoundaries) {
                if ((this < max) && (this > min)) between = true;
            } else {
                if ((this <= max) && (this >= min)) between = true;
            }
            return between;
    }
}

setPercentageMask();
```
