### ISSUE TITLE
text field is not cleared out when blur event is triggered 

### ISSUE THREAD

**Issue by FlavioRodr** [igorescobar/jQuery-Mask-Plugin#454]
Need to confirm but isn't it desired behavior setting the field to empty when the mask is invalid? The example is a date field (MM/DD/YYYY)
![mask](https://cloud.githubusercontent.com/assets/5659387/18277561/43895dcc-7425-11e6-913b-9301fcc05c98.JPG)

**Comment by igorescobar** [comment]
https://github.com/igorescobar/jQuery-Mask-Plugin/blob/master/README.md#bugs
