### ISSUE TITLE
Reverse true and negative numbers

### ISSUE THREAD

**Issue by charalamposc** [igorescobar/jQuery-Mask-Plugin#455]
I am trying to allow negative numbers but it is not working when I use the option `reverse:true`.

Example:
``` html
    <input class="percent" type="text" name="field-name" />
    <script>
    $(document).ready(function() {
        $('.percent').mask('N#.###.##0,00', {
            reverse: true,
            translation: {
                "N": {
                    pattern: /-/,
                    optional: true
                }
            }
        });
    });
    </script>
```

**Comment by sjancke** [comment]
I'm also seeing this problem. Negative numbers with a custom translation seem only to work without reverse. Sadly, I need the combination of both.

http://jsfiddle.net/6pco4om7/439/

**Comment by igorescobar** [comment]
https://github.com/igorescobar/jQuery-Mask-Plugin/blob/master/README.md#negative-numbers-or-currency-related-problems

**Comment by hastalavista911** [comment]
me too, can't dell "%" percent symbol when form is valued by some number. must dell the number first or block that input first :(
