### ISSUE TITLE
adicionar 0 à esqueda com "-" antes do último digito

### ISSUE THREAD

**Issue by leandroruel** [igorescobar/jQuery-Mask-Plugin#457]
quero adicionar uma máscara para conta bancária, onde o campo pode ter 4, 5 e no máximo 9 dígitos, sendo que o último dígito é precedido por um hífen, existe algo neste plugin que faça isso?

0000-0 ?

**Comment by silas-ss** [comment]
acredito que não o que você pode é ir alterando a máscara de acordo com a quantidade de dígitos usando a máscara 9999-9?9999.

**Comment by igorescobar** [comment]
@leandroruel pode fornecer exemplos inputs validos e invalidos?
