### ISSUE TITLE
How do I fire onInvalid callback for times?

### ISSUE THREAD

**Issue by felipecao** [igorescobar/jQuery-Mask-Plugin#458]
Hi!

I have a form with the following `input`:

```
<input type="text" id="startTime" name="startTime" value="" placeholder="00:00">
```

and currently its formatting is set like this:

```
            var timeMaskOptions =  {
                onInvalid: function(val, e, f, invalid, options){
                    var error = invalid[0];
                    console.log ("Digit: ", error.v, " is invalid for the position: ", error.p, ". We expect something like: ", error.e);
                }
            };

            $('#startTime').mask('00:00', timeMaskOptions);
```

The formatting works just fine, the user input is masked as expected. But I assumed that if the user would provide a time like `25:00`, `onInvalid` callback would be invoked, which did not happen.

Am I doing anything wrong here? Or is the `onInvalid` callback not supported for time inputs?

Thanks a lot!

**Comment by igorescobar** [comment]
@felipecao https://github.com/igorescobar/jQuery-Mask-Plugin/blob/master/README.md#add-validation
