### ISSUE TITLE
Not allowing spaces

### ISSUE THREAD

**Issue by genavico** [igorescobar/jQuery-Mask-Plugin#462]
I'm not sure if this is fixed, but when I try using alpha only (so that I can apply it to a city), spaces are not allowed.  I modified the jquery.mask.js file (line 505) where the translations are being defined.

I modified 'S': {pattern: /[a-zA-Z]/ to this:  'S': {pattern: /[a-zA-Z ]/ (I added a space after the Z).  This allows the S translation to account for spaces.

I hope this helps!
Tyler

**Comment by igorescobar** [comment]
Yes @genavico 
Take a look into the docs: http://igorescobar.github.io/jQuery-Mask-Plugin/
In the *Global Options* you will see the `translation` option detailed so you can define new ones or overwrite existing the default. You can do it globally or directly on the method signature.

**Comment by artivilla** [comment]
So if I want spaces only in specific locations I create a pattern for tel as `tel: '(000)Z000-0000',` and add translations as `translation: { Z: { pattern: /\s/ } },`
