### ISSUE TITLE
Mask allows extra characters after updating version

### ISSUE THREAD

**Issue by jsparks19** [igorescobar/jQuery-Mask-Plugin#465]
I was previously using version 1.6.4 and tried to update to 1.14.0. After doing so, my mask is now allowing the user to type extra digits. The extra digits do not display but the model (I'm using Angular) contains the extra digits. Did something change that would cause this? The mask I'm using is "999-99-9999" and I am not specifying any options.

I found this issue and thought it may be similar, but that issue has been closed. https://github.com/igorescobar/jQuery-Mask-Plugin/issues/138

Thanks

**Comment by alexandreviegas** [comment]
I'm having the same problem too.
My mask is this $('.cpf').mask('000.000.000-00'); . When I type some digit, even after input was totally filled, the input not shows the extra digit, but it appears on Angular model.
Solved using maxlength attribute on input, but I think that mask should do it.

**Comment by igorescobar** [comment]
@jsparks19 @alexandreviegas let me know if the latest version works for u.
