### ISSUE TITLE
Currency: How to put manually separator?

### ISSUE THREAD

**Issue by adrianoresende** [igorescobar/jQuery-Mask-Plugin#467]
It is common for users put only integers and when you need to put cents, puts separator manually.
Because if you start typing R$ 123, the plugin does as R$ 1,23 (23 cents), making the user confused, this is bad experience.

You can do this with this plugin?

I looked other plugins but many are not updated and some has bug in precision.

**Comment by igorescobar** [comment]
@adrianoresende https://github.com/igorescobar/jQuery-Mask-Plugin#problems-or-questions
