### ISSUE TITLE
focusout.mask does not trigger the change event

### ISSUE THREAD

**Issue by Kurtaclan** [igorescobar/jQuery-Mask-Plugin#468]
Making the following change rectifies the issue.

.on('focusout.mask', function() {
                    if (options.clearIfNotMatch && !regexMask.test(p.val())) {
                       p.val('');
                       el.trigger('change');
                   }
});

**Comment by igorescobar** [comment]
@Kurtaclan If you don't provide an jsfiddle (or similar) simulating the problem I can't help you.
