### ISSUE TITLE
Ponto Extra ao definir máscara para elemento classe money

### ISSUE THREAD

**Issue by marcosbaesse** [igorescobar/jQuery-Mask-Plugin#469]
Tenho um arquivo em PHP em que escrevo na tela o seguinte valor monetário (exemplo)

333.00

Então, ao executar o .mask na div, ela é exibida da seguinte forma:

.333,00

Se eu colocar outros valores como 333,333.00 A máscara aplicada ficará:
.333.333,00

E assim por diante...

**Comment by igorescobar** [comment]
https://github.com/igorescobar/jQuery-Mask-Plugin#bugs
