### ISSUE TITLE
"0" no different than "Z"

### ISSUE THREAD

**Issue by RobbSadler** [igorescobar/jQuery-Mask-Plugin#470]
I would like to make a mask that puts in all of the decimal digits regardless of the input. Ie:

If the mask is: 
".00" 
and I type in:
"5" 
then the mask should show:
".05"

This is the behaviour I expected from the zeros. But the result I get is "5". But I perceive this as 5.00 (with the decimal missing).

I would expect this more if I had typed ".ZZ" as the mask. It is confusing for the decimal place to be missing for small amounts, and more importantly for your mask that if it is a required zero, that it should be present.

Does this make sense?

Thanks for a nice add on!

**Comment by igorescobar** [comment]
@RobbSadler https://github.com/igorescobar/jQuery-Mask-Plugin#problems-or-questions
