### ISSUE TITLE
Is it possible to show letters ALWAYS when there's an input?

### ISSUE THREAD

**Issue by AlexioVay** [igorescobar/jQuery-Mask-Plugin#471]
Is it possible to show letters ALWAYS when there's an input?
For example I want the user to enter body height and weight and only numbers are allowed and cm or kg indicates the unit.

I tried it this way, but this only shows "cm" or "kg" when you at least enter 3 number plus spacebar:

```
    $('#body_height').mask('000 cm');
    $('#body_weight').mask('000 kg');
```

**Comment by igorescobar** [comment]
https://github.com/igorescobar/jQuery-Mask-Plugin#problems-or-questions
