### ISSUE TITLE
[ready] Rails gem for JQuery mask plugin

### ISSUE THREAD

**Issue by maurcarvalho** [igorescobar/jQuery-Mask-Plugin#477]
Hello @igorescobar :)

I've encapsulated your library in a rails gem making it ready to install with 1 line of code on Rails Applications. You can check it out here: https://rubygems.org/gems/jquery_mask_rails

Next steps:
I'm planning to update the readme file to include to Rails version of how-to install or something like that. Let me know your thoughts about it

Repository: https://github.com/maurcarvalho/jquery_mask_rails

Regards,

**Comment by igorescobar** [comment]
Thanks @maurcarvalho. 👍
