### ISSUE TITLE
Data-Mask attribute only works if script is included after html element

### ISSUE THREAD

**Issue by kyletinsley** [igorescobar/jQuery-Mask-Plugin#478]
On our site, plugin scripts are included in the document header (as some plugins require).  However, with this plugin (which we love), data-mask attributes are not processed for masking if they are rendered after your script.  Can you alter your script so that the data attributes are processed on document.ready, instead of inline, as it appears to be?  That way, declarative masking will work regardless of where your script is located on the page.  This had me and two other colleagues stumped for the past hour, so I would imagine others have run into this as well.

Something like:

$(function(){
 //process data attributes
});

**Comment by vizo** [comment]
I have the same issue ... did you find workaround?

**Comment by igorescobar** [comment]
Just activate the watcher. see the docs.
