### ISSUE TITLE
Is data-mask-placeholder supported?

### ISSUE THREAD

**Issue by kyletinsley** [igorescobar/jQuery-Mask-Plugin#479]
I can get the placeholder to work when called via script, but not when declared as a data attribute.  Is this not supported?  If not, can you add support?

This does not work:
`<input type='text' data-mask='09/09/0099' data-mask-placeholder='__/__/____' />`

**Comment by kyletinsley** [comment]
Oh, I think we should we just use the html "placeholder" attribute.  I was under the impression that the placeholder associated with this plugin would be visible while typing, but I see now that it is like the html placeholder and disappears when typing.  Am I correct?  Any way to get the placeholder to be visible while typing as with this plugin: http://digitalbush.com/projects/masked-input-plugin/

**Comment by igorescobar** [comment]
Yup. just use the placeholder attribute. Placeholder while typing isn't supported.
