### ISSUE TITLE
Wrong link on tutorial 

### ISSUE THREAD

**Issue by iagorios** [igorescobar/jQuery-Mask-Plugin#480]
Hi Igor,

please, replace wget https://github.com/igorescobar/jQuery-Mask-Plugin/blob/master/jquery.mask.min.js (which gives me 404)
 by 
wget https://raw.githubusercontent.com/igorescobar/jQuery-Mask-Plugin/master/dist/jquery.mask.min.js
on your tutorials. 

Thanks.

**Comment by igorescobar** [comment]
@iagorios I think its fixed now. Let me know if there is anything missing.
