### ISSUE TITLE
Unmask only works for original selector

### ISSUE THREAD

**Issue by deckar01** [igorescobar/jQuery-Mask-Plugin#481]
**Issue:**

Calling `unmask` on individual inputs is not persistent. It removes the formatting for a few hundred milliseconds, then restores the mask.

**Example:**

https://jsfiddle.net/o4zzby58/

**Cause:**

The jQuery `selector` attribute is being used incorrectly as an index for a set of intervals. Some jQuery operations like `filter` also clear the selector, which makes it an unsuitable identifier.

 - [src/jquery.mask.js#L458-L459](https://github.com/igorescobar/jQuery-Mask-Plugin/blob/dd4763c/src/jquery.mask.js#L458-L459)
 - [src/jquery.mask.js#L471-L472](https://github.com/igorescobar/jQuery-Mask-Plugin/blob/dd4763c/src/jquery.mask.js#L471-L472)

**Note:**

The mask does not automatically update if the original query has an empty selector, which could also be avoided.

**Solution:**

Apply a class to masked elements and query them in a global interval.

**Comment by igorescobar** [comment]
@deckar01 You are right. In order to catch new inputs (pragmatic inserted fields) we need to constantly be look for new elements based on its selector (instead of looking for the entire DOM tree) so if your mask doesn't have a selector its impossible to monitor it and to make it work as expected so it's always good to code your masks attached to a class or id. If you don't want to jQuery Mask to watch for new elements you can tweek the global options:

```javascript
// nonInput: elements we consider nonInput
// dataMask: we mask data-mask elements by default
// watchInputs: watch for dynamically added inputs by default
// watchDataMask: by default we disabled the watcher for dynamically added data-mask elements by default (performance reasons)
 $.jMaskGlobals = {
    maskElements: 'input,td,span,div',
    dataMaskAttr: '*[data-mask]',
    dataMask: true,
    watchInterval: 300,
    watchInputs: true, // <-
    watchDataMask: false, // <-
    byPassKeys: [9, 16, 17, 18, 36, 37, 38, 39, 40, 91],
    translation: {
        '0': {pattern: /\d/},
        '9': {pattern: /\d/, optional: true},
        '#': {pattern: /\d/, recursive: true},
        'A': {pattern: /[a-zA-Z0-9]/},
        'S': {pattern: /[a-zA-Z]/}
    }
  };
```

And disable this behaviour.

**Comment by igorescobar** [comment]
Also @deckar01 let me know if we can make this better. Always open to suggestions. Cheers!

**Comment by deckar01** [comment]
It is unusual for a jQuery plugin to only work with the `$(selector)` syntax and reuse the selector to requery the DOM later.

Normally only the elements that exist at the time of the query are affected, and it does not matter to the plugin how the collection of elements was queried.

The `.selector` property was actually deprecated in jQuery 1.7 and remove in 3.0, because of it's questionable reliability.

https://api.jquery.com/selector/

A more common plugin pattern is to apply a plugin specific class to the selection.

**Comment by deckar01** [comment]
I'm also not sure that the ["dynamically loaded elements"](https://github.com/igorescobar/jQuery-Mask-Plugin/blob/master/test/jquery.mask.test.js#L669) test is written correctly. Is it supposed to be testing elements created after the mask is applied?

**Comment by deckar01** [comment]
https://github.com/igorescobar/jQuery-Mask-Plugin/compare/master...deckar01:481-input-watchers

This branch demonstrates creating the static interfaces `$.mask(selector)` and `$.unmask(selector)` since `$el.selector` is no longer supported.

**Comment by igorescobar** [comment]
@deckar01 

> It is unusual for a jQuery plugin to only work with the $(selector) syntax and reuse the selector to requery the DOM later.

The plugin works, the watchers won't.

> Normally only the elements that exist at the time of the query are affected, and it does not matter to the plugin how the collection of elements was queried.

I agree and I hated doing this. But seems like the majority of the users uses the plugin specifying a selector and it's a cool "feature" to add a built-in solution to apply masks on dynamically loaded elements. Don't forget that you can also apply masks to non-input fields like a div, span etc. pretty common when you have a ajax search and some of your columns are masked too.

> The .selector property was actually deprecated in jQuery 1.7 and remove in 3.0, because of it's questionable reliability.

Hum... Didn't knew that.

> This branch demonstrates creating the static interfaces $.mask(selector) and $.unmask(selector) since $el.selector is no longer supported.

Why don't you submit a PR with those changes and we can discuss there?

**Comment by deckar01** [comment]
Closing due to lack of interest from the maintainer. This is still an issue. Latest repro: https://jsfiddle.net/o8vb3gpw/
