### ISSUE TITLE
Limitar um campo money com o mask

### ISSUE THREAD

**Issue by davidhalves** [igorescobar/jQuery-Mask-Plugin#483]
Quero limitar um campo que contenha a mask de money para um campo de no máximo 16 caracteres, como posso fazer isso? Pois ao colocar um a mascara como  "9.999.999.999,99" o resultado no input é "...4,72"

**Comment by igorescobar** [comment]
`maxlength`.  anything else: https://github.com/igorescobar/jQuery-Mask-Plugin#problems-or-questions

**Comment by davidhalves** [comment]
maybe i'm being stupid but i didn't found anything about the property maxlength in the issues or in your documentation...
can u show me how i use this? i tried to put this on the options like '.mask(scope.mask, {reverse: scope.reverse, maxlength : 16})' but didn't work.

**Comment by igorescobar** [comment]
@davidhalves the `maxlength` is a html property and isn't related to the plugin. But... you can also try the new version that I released today and it should fix it for you.

**Comment by davidhalves** [comment]
@igorescobar  i'll try this and report you if i need some help, thank u
