### ISSUE TITLE
Caret issue using Samsung keyboard

### ISSUE THREAD

**Issue by gersteba** [igorescobar/jQuery-Mask-Plugin#487]
Hi!

Also latest version 1.14.3 is buggy using Samsung keyboard:
i.e. I am using this code:
jQuery(function($){
    $("input.myinput").mask("0000h00h000", {
        translation: {
            "h": {
                pattern: /[\-]/,
                fallback: "-"
            }
        },
        placeholder: "____-__-___"
    });
});
When I enter the first three digits and then enter a hyphen, everything is okay.
But when I omit entering the hyphen instead and just continue entering the fifth digit, nothing is entered and the caret moves 3 digits to the left.
This makes inputting very difficult, if I don't want to enter the hyphens myself!

Kind regards,
Gerald

**Comment by af-unipro** [comment]
Having a similar issue using the native browser on an Galaxy Nexus tablet running os 4.1

**Comment by igorescobar** [comment]
Duplicated:
https://github.com/igorescobar/jQuery-Mask-Plugin/pull/464
https://github.com/igorescobar/jQuery-Mask-Plugin/issues/432
https://github.com/igorescobar/jQuery-Mask-Plugin/issues/135
