### ISSUE TITLE
Definition file for Typescript

### ISSUE THREAD

**Issue by MichielDP** [igorescobar/jQuery-Mask-Plugin#489]
Is it possible to add a definition file for Typescript?

**Comment by igorescobar** [comment]
@MichielDP Submit your PR and I will analyse it.

**Comment by MichielDP** [comment]
I'm not an active user of GitHub so I don't know how PRs work. It's just that I have used your javascript library before in the past and I was really happy about it. Now I want to implement it into system where we use typescript instead of javascript but I need a typescript definition file fot that (.d.ts). That definition file basically tells typescript what kind of functions are available for us and will give intelisense about it.

**Comment by igorescobar** [comment]
@MichielDP For now what you can do is convert this source file with this project:
https://www.npmjs.com/package/javascript-to-typescript

Never used but it might work.

Let me now if it works okay so I could use it to and automate the process.

**Comment by MichielDP** [comment]
I scrolled about through the other issues and saw that this question had already been asked (my bad).

https://github.com/igorescobar/jQuery-Mask-Plugin/issues/449

I ended up using Avidenic's solution. It works for me, not sure if it will work as it should for everyone.

Maybe you should review it and include it in the official distribution? And even maybe add it to the community list of typed definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by igorescobar** [comment]
@MichielDP @avidenic is there any way we can add this to the project? Submit a PR with this... I never used typescript so I'm not sure where I should add this and which filename it should have etc.

**Comment by avidenic** [comment]
Hey, 

I'll create a PR with my solution and add it to DefinetileyTyped as well. Give me a day or two please =)
