### ISSUE TITLE
Negative Money Amounts

### ISSUE THREAD

**Issue by Knowtie** [igorescobar/jQuery-Mask-Plugin#492]
QUESTION: How do I implement a mask that supports money that also supports negative amounts, because:

     "-0,000,000,000.00" and "reverse: true"

doesn't want to work for me.  I mean I can understand why, if it is "-000.00" I can put in "-900.05", but "-90.05" doesn't work unless it's "-090.05".

**Comment by igorescobar** [comment]
https://github.com/igorescobar/jQuery-Mask-Plugin#problems-or-questions
