### ISSUE TITLE
Problema ao setar valor

### ISSUE THREAD

**Issue by kellerkichel** [igorescobar/jQuery-Mask-Plugin#493]
Olá, bom dia, estava com um problema para setar um valor, seja com jquery _(el.val(123))_ ou com javascript mesmo _(el.value = 123)_, em ambos os casos o valor aplicado no campo não era mascarado pelo plugin.

Fiz uma pequena alteração no código fonte para que isto funcionasse mas não sei se foi a melhor solução e gostaria da opinião, consegui fazer de 2 maneiras, mas a primeira é a mais interessante, genérica e fácil de executar, segue abaixo as alterações que fiz:

---

**Situação 01**
Executando o código: `$('elemento').val('12345678').trigger('change');`

** Problema 02**
O valor é aplicado no elemento, porém sem a mascara.

**Solução 01**
No evento **change.mask** simplesmente mando setar o valor do campo também.
``` 
.on('change.mask', function () {
  el.data('changed', true);
  p.val(p.getMasked());
})
```

---

**Situação 02**
Executando o código: `$('elemento').val('12345678');` e na sequência `$.applyDataMask();`.

**Problema 02**
A função **notSameMaskObject** sempre retorna false, simplesmente não aplicando a mascara no campo escolhido.

** Solução 02**
Desativei esta validação.
```
//if (notSameMaskObject(input, mask, options)) {
  return input.data('mask', new Mask(this, mask, options));
//}
```

**Comment by igorescobar** [comment]
The solution it is just:
```
$('elemento').val('12345678').trigger('input');
```
