### ISSUE TITLE
Apply mask in a span or a div

### ISSUE THREAD

**Issue by hmartinsceven** [igorescobar/jQuery-Mask-Plugin#494]
Hello,

I've been trying to apply a mask in a div. The element is like this span id="budget-total-sum"  10111

After trying to apply  $("#budget-total-sum").mask('000.000.000.000.000,00 $'); the result is the same as without mask.

I attached and print screen, where you can see the mask applied to input and it works fine, but in span I can't have the same results.

Can you please help me? 
Thanks in advance.

![screenshot from 2016-12-21 10 41 38](https://cloud.githubusercontent.com/assets/3170222/21386332/3340285e-c76a-11e6-815d-bbf9f73f0ef7.png)

**Comment by igorescobar** [comment]
I can't help you if you don't provide a jsfiddle or something.

Enviado do meu iPhone
