### ISSUE TITLE
Erratic caret movement when deleting something from the middle

### ISSUE THREAD

**Issue by mehraan** [igorescobar/jQuery-Mask-Plugin#497]
JSFiddle: https://jsfiddle.net/pwpnh4Lf/

The mask is `000-000-000`
If you start with `123-456-789`, delete the middle three digits, and then type those digits again, the result should be again `123-456-789`, but the cursor moves erratically, and the result is `123-475-689`.

![2016-12-24 17_49_46](https://cloud.githubusercontent.com/assets/993959/21469422/6c0e2d18-ca01-11e6-98b5-1d78b88b1a20.gif)

**Comment by igorescobar** [comment]
@mehraan just released a new version, could you verify? thanks!

**Comment by mehraan** [comment]
@igorescobar works. Thanks!
