### ISSUE TITLE
How to Integrate jQuery Mask Plugin with React.js?

### ISSUE THREAD

**Issue by igorescobar** [igorescobar/jQuery-Mask-Plugin#498]
I've made a simple jsfiddle showing how to integrate jQuery Mask with React.js:
https://jsfiddle.net/igorescobar/47ubm7az/

**Comment by rinatsafin** [comment]
not work fiidle

**Comment by wemersonrv** [comment]
Hello, to use with React, i need to install this plugin and jquery too ?

**Comment by duynguyenhoang** [comment]
Definitely yes, It is jQuery plugin.

**Comment by LuizFellype** [comment]
Yes, Need install and import jQuery as $ and need to import the code on top of the file, like this:
```js
import $ from 'jquery';
import 'jquery-mask-plugin/dist/jquery.mask.min'; 
```

Theeennn... You can use it:
```js
$('.dinheiro').mask('#.##0,00', {
      reverse: true,
      placeholder: '0,00'
    });
```

I am clarifying this because I didn't find anyone saying nothing. And just adding the script into header tag doesn't work.

**Comment by relaxdd** [comment]
так же почему то не работает если прописать в input data-mask="..."

**Comment by Alberto-Frigatto** [comment]
1. First you must install jquery-mask-plugin by your package manager:

**NPM:**

`npm i jquery-mask-plugin`

**Bower:**

`bower install jquery-mask-plugin`

**Meteor:**

`meteor add igorescobar:jquery-mask-plugin`

**Composer:**

`composer require igorescobar/jquery-mask-plugin`

<br/>

2. Then you will import jquery and jquery-mask-plugin in your component:

```javascript
import $ from 'jquery';
import 'jquery-mask-plugin';

const Component = () => {
  $(() => {
    $('#date').mask('00/00/0000');
  });

  return (
    <form onSubmit = { e => e.preventDefault() }>
      <input
        type = 'text'
        id = 'date'
        placeholder = '00/00/0000'
      />
    </form>
  );
}

export default Component;
```
