### ISSUE TITLE
How to Integrate jQuery Mask Plugin with Angular.js?

### ISSUE THREAD

**Issue by igorescobar** [igorescobar/jQuery-Mask-Plugin#499]
I've done a simple example showing how to integrate jQuery Mask Plugin with Angular.js:
http://jsfiddle.net/igorescobar/4ezow2p7/

**Comment by arimourao** [comment]
This fiddle is not working. Tested on 
Chromium Version 55.0.2883.75 
and
Firefox ESR 45

Built on 8.6, running on Debian 8.6 (64-bit)

**Comment by igorescobar** [comment]
@arimourao 
<img width="536" alt="screen shot 2017-01-02 at 17 44 49" src="https://cloud.githubusercontent.com/assets/24032/21593812/2ffa18fa-d113-11e6-9377-7e41a07d5d0f.png">

Tested on Chrome, Safari and Firefox (Mac). Is it giving you any error?

**Comment by fdeslandes-wk** [comment]
@igorescobar Here is a more complete example: [http://jsfiddle.net/qhcqbef5/6/
](http://jsfiddle.net/qhcqbef5/6/)

You used a pretty old version of angular in your example, I updated it to use the newer syntax, which is easier to understand.

**Comment by rafael-andrade** [comment]
How could I use it with angular 2? Thanks

**Comment by yodanielo** [comment]
Hello, there's an error with de parameter "reverse" when I integrate it with angular:
http://jsfiddle.net/4ezow2p7/205/

**Comment by prometeomcclellan** [comment]
fdeslandes-wk ... dude! Your code is not easier to understand. Still is a pretty nice example! Thanks

**Comment by fdeslandes-wk** [comment]
@prometeomcclellan I was talking about a newer angularJs syntax,  which is easier to understand compared to the older version in which the example was written when I contributed the example.

My code adds some more use cases that were not covered, so of course it is not easier to understand.
