### ISSUE TITLE
unjustifiable wrapper around plugin - breaks in Webpack

### ISSUE THREAD

**Issue by folmert** [igorescobar/jQuery-Mask-Plugin#500]
This wrapper:
```
// UMD (Universal Module Definition) patterns for JavaScript modules that work everywhere.
// https://github.com/umdjs/umd/blob/master/jqueryPluginCommonjs.js
(function (factory, jQuery, Zepto) {

    if (typeof define === 'function' && define.amd) {
        define(['jquery'], factory);
    } else if (typeof exports === 'object') {
        module.exports = factory(require('jquery'));
    } else {
        factory(jQuery || Zepto);
    }

}(function ($) {
```

doesn't make sense. The user himself should explicitly decide if he wants to use AMD, CommonJS or none.

But what's worse is that it breaks in Webpack. I'm adding jquery-mask-plugin by:
`require('jquery-mask-plugin');`
so I'm using CommonJS approach, but the wrapper falsely chooses to use AMD, because the line in first condition is executed:
```
if (typeof define === 'function' && define.amd) {
        define(['jquery'], factory);
```

which makes the plugin unusable, because then `$.fn.mask` and other functions are not added to my `$`.

Only when I removed first two conditions and used only:
`factory(jQuery);`
the plugin was usable.

**Comment by igorescobar** [comment]
@folmert Sorry to hear that it isn't working for you. Now help me to help you. 

Does this works for you:
https://github.com/umdjs/umd/blob/master/templates/jqueryPlugin.js

?

If it works, could you submit a PR with this change and the we could discuss it there if necessary. How does it sound?

**Comment by folmert** [comment]
Ok, I've copy-pasted this jQueryPlugin.js template to my node_modules and added it by:
`require('jqueryPlugin');`
	
and it appears that behaves in the same way - it assumes that I used AMD, because define.amd exists. But this logic is broken on Webpack ground - the fact define.amd exists is because Webpack supports multiple module definitions, not because I'm using it at the moment.

I've noticed it's a known [issue](http://stackoverflow.com/questions/28969861/managing-jquery-plugin-dependency-in-webpack). and there is a hacky, temporary solution for Webpack users:

"4. Use the imports-loader to disable AMD
	
There are modules that support different module styles, like AMD, CommonJS and legacy. However, most of the time they first check for define and then use some quirky code to export properties. In these cases, it could help to force the CommonJS path by setting define = false."

To reduce confusion around this, on plugin side we can either rewrite the wrapper (not sure if possible), or remove it and leave the plugin simply as:
(function ($) {
	/* plugin */
}(jQuery));
which is a common practice in other jQuery plugins.

**Comment by igorescobar** [comment]
@folmert Have you looked into this thread:
https://webpack.github.io/docs/library-and-externals.html

Seems that they are discussing about webpack there too. I'm kinda insecure on changing this because this is exactly the way UMD recommends us to do it as a jQuery Plugin. Unless we got something official I'm really not sure how to proceed here.
