### ISSUE TITLE
IE9 Masks

### ISSUE THREAD

**Issue by italofds** [igorescobar/jQuery-Mask-Plugin#502]
Olá!

Estou usando a versão 9.0.8112.16421 do Internet Explorer e percebi que nenhuma das máscaras da página de demonstração (https://igorescobar.github.io/jQuery-Mask-Plugin/) está funcionando corretamente.

Exemplos:
Ao digitar 12345678 na máscara de data, o resultado é 12/45/7863;
Ao digitar 12345678 na máscara de telefone, o resultado é 1234-6785;
Ao digitar 01234567890 na máscara de CPF, o resultado é 013.467.890-52;

Att,
Ítalo Santos.

**Comment by igorescobar** [comment]
@italofds is this still hapenning?

**Comment by rmirandad** [comment]
Hi,
Yes, this still happenning.

Best regards

**Comment by joaopintof** [comment]
@igorescobar  @italofds 

i changed on "behavior" function this code and now it's working.

`//setTimeout(function(caretPos, newVal) { //comment this line`

`setTimeout(function() { //replace for this`
