### ISSUE TITLE
Problem with mask in mobile devices

### ISSUE THREAD

**Issue by nettopaulo** [igorescobar/jQuery-Mask-Plugin#503]
When I use a mobile device, the masks behaviour does not work.
I am using Galaxy S7, but others devices have the same problem.

The mask: 00000-000.
When I type the first character after "-", the cursor came to before this character, just after "-".

I type 27329876.
The masked value should be 27329-876.
But with this problem, it become 27329-768.

Some fix for this??

Thanks.

**Comment by DanyDoi** [comment]
The problem also occurs in IE Edge...
+1

**Comment by eduardoluizm** [comment]
The problem also occurs in last chrome on mobile android devices.

**Comment by igorescobar** [comment]
@nettopaulo an functional jsfiddle would be great.

**Comment by robertotremonti** [comment]
I confirm the problem with default Samsung browser (the one called "Samsung Internet for Android") on their phones.
When you start typing, the caret moves to the beginning.

**Comment by robertotremonti** [comment]
I think I've found the problem.
I was running the script thru CDN at https://cdnjs.com/libraries/jquery.mask.
Thus reporting the correct version number, actually it doesn't include [all changes](https://github.com/igorescobar/jQuery-Mask-Plugin/commit/c79e2a7529dc80771db0b00183a94d6c5cfe3137) in v1.14.8 available in this repository.
I fixed the problem by downloading v1.14.8 from here and running it as a local copy in my application.

**Comment by igorescobar** [comment]
@robertotremonti That's weird. Can you show me the diff between what you had and have now?

**Comment by robertotremonti** [comment]
The generated file for v1.14.8 (dist)
https://github.com/igorescobar/jQuery-Mask-Plugin/blob/master/dist/jquery.mask.js

is not the same as this one (src)
https://github.com/igorescobar/jQuery-Mask-Plugin/blob/master/src/jquery.mask.js

Just run a diff.
https://www.diffchecker.com/BcILgYGn

**Comment by igorescobar** [comment]
@robertotremonti damn... that was my bad! I fixed a few issues but completely forgot to release a new version with this fix. You now should be able to use the `v1.14.9`.

**Comment by felipedrumond** [comment]
I can confirm that v.1.14.10 solves the following issue:

When using v.1.14.3 I had the following issue when using Samsung's native browser:

mask: 00000-000 (Brazilian zip code)
intended value: 12345-678

Issue: after typing '6', the value shown is '123456-' instead of '12345-6'.
