### ISSUE TITLE
Retaining decimal in Money when retrieving cleanVal()

### ISSUE THREAD

**Issue by merccat** [igorescobar/jQuery-Mask-Plugin#504]
This may fall under a feature request, but it would be nice if certain elements of a mask could be retained even on clean.

For example with Money one may mask as $('.mask-money').mask('000,000,000.00', { reverse: true });

calling cleanVal() will clear out the commas for saving the data but unfortunately it also clears out the decimal, effectively changing the value.  5,000.00 becomes 5000000 = 500,000.00

**Comment by igorescobar** [comment]
@merccat Sorry.

https://github.com/igorescobar/jQuery-Mask-Plugin/issues/436#issuecomment-253176511
