### ISSUE TITLE
Mask as a function, input error

### ISSUE THREAD

**Issue by sentfanwyaerda** [igorescobar/jQuery-Mask-Plugin#505]
Hi, I adapted the 'Mask as a function' example to fit the telephone masks in the Netherlands

```javascript
$( function() {
	var SPMaskBehavior = function(val){
		var masks = ['(00) 00 00 00 00','(000) 000 00 00', '(0000) 00 00 00'];
		return ($.inArray(val.replace(/[^0-9]/gi,'').substring(0,3), ['061','062','063','064','065','068','069']) >= 0 ? masks[0] : ($.inArray(val.replace(/[^0-9]/gi,'').substring(0,3), ['010','013','015','020','024','026','030','033','035','036','038','040','043','045','046','050','053','055','058','070','071','072','073','074','075','076','077','078','079','088']) >= 0 ? masks[1] : masks[2] ) );
	}
	var spOptions = {
		onKeyPress: function(val, e, field, options) {
			field.mask(SPMaskBehavior.apply({}, arguments), options);
		}
	};
	$("input[type='tel']").mask(SPMaskBehavior, spOptions);
});
```
```html
<form><input type="tel" name="telefoonnummer" /></form>
```
When someone enters their phone number like `06123456789`, the result will be: `(06) 34 67 85 21`. The error is the result of not remembering the carot/cursor to its relative place...

_Forgive me when the solution is already provided, but I couldn't find it._

**Edit:** version `v1.14.8`, and familiarity with #497 
**Edit:** https://jsfiddle.net/nc6q78ee/ does not reproduce the error, wondering if jquery.mask interacts with other libs?
**Edit:** tested with jquery `3.1.1` and `1.11.1`.
**Edit:** does not fail with jquery.mask `1.14.3` -- time to `git blame`! Error reproduced with https://jsfiddle.net/nc6q78ee/1/

**Comment by sentfanwyaerda** [comment]
Pointing to the *edits* above: this error arises with the alterations between `1.14.3` and `1.14.8`

could it be a typo on line 102 and 191? [ generating jquery mask files v1.14.6 / igorescobar authored 16 days ago]
```javascript
102: el.data('mask-previus-value', el.val());
191:  oValue = el.data('mask-previus-value'),
```

**Comment by strigona-worksight** [comment]
I ran into the same error, though had yet to isolate a testcase - so thanks for creating the ticket! I had to revert to 1.4.3 as well to get my project to work correctly.

**Comment by strigona-worksight** [comment]
Actually scratch that.. I had another error that is entirely unrelated where
 oValue = el.data('mask-previus-value')
was undefined. I'll try to create a test case & submit a ticket.

**Comment by igorescobar** [comment]
@strigona-worksight @sentfanwyaerda Test this version:
https://github.com/igorescobar/jQuery-Mask-Plugin/blob/master/src/jquery.mask.js

Let me know if this works for you.

**Comment by sentfanwyaerda** [comment]
I tested it against the use-cases that produced the error, including within the deployed environment. It appears to be fixed. 

**# Closed**
