### ISSUE TITLE
Data with decimal being ignored

### ISSUE THREAD

**Issue by jaredgalanis** [igorescobar/jQuery-Mask-Plugin#506]
I'm using library on an html input whose value is being populated with data from our server. When the data contains a decimal the plugin seems to ignore the decimal and just read the digits. 

So for example, 2.0 from the back end is read interpreted by jQuery-Mask-Plugin as 20, and 22.0 as 2.20 respectively, etc.

I'm using:

```.mask('000,000,000,000,000.00', {reverse: true});``` 

to format the data. Is this a limitation of the library or am I just using it incorrectly / not seeing a feature in the docs?

**Comment by igorescobar** [comment]
@jaredgalanis You need to normalize the data before putting inside of the HTML field. If you input 10.00 and the data is coming from the server like 10.0. You will have a problem because it will probably become 1.00.
