### ISSUE TITLE
Native browser autocomplete bug

### ISSUE THREAD

**Issue by xarder** [igorescobar/jQuery-Mask-Plugin#508]
Here's an error in console when you try to choose value from native browser autocomplete
http://jsfiddle.net/nwbcj9ud/8/
steps to reproduce:
1. Enter here http://jsfiddle.net/nwbcj9ud/8/
2. Double click with mouse on field to call native autocomplete http://take.ms/MlaDp
3. Choose something from autocomplete list with mouse click
And here's error in console after step 3 http://take.ms/rtwWV

**Notice**, if you enter something in field and clear then error won't fire, it's firing only after load and field is not "touched"

**Comment by igorescobar** [comment]
@xarder what native browser? can you provide more information?

**Comment by xarder** [comment]
@igorescobar 
Sorry for not being clear. I meant native autocomplete (not any js plugin), browser has it's own autocomplete dropdown for the same field IDs(name) that you've used recently, this one http://take.ms/rDlIa
But the bug seems related to #513 , #512.

**Comment by igorescobar** [comment]
@xarder So test what I'm recomending inside of those issues and let me know if this works for you.

**Comment by xarder** [comment]
@igorescobar work's good, thank you.
