### ISSUE TITLE
US Telephone mask shifts the entered value on second entry

### ISSUE THREAD

**Issue by bodhicittaben** [igorescobar/jQuery-Mask-Plugin#509]
On the jQuery Mask Plugin demo page (https://igorescobar.github.io/jQuery-Mask-Plugin/):

1. Enter a US Telephone value (E.g. 5555555555)
2. Leave the field (used the tab button)
3. Re-enter the US Telephone field, use ctrl+a to select all of the information, press delete to remove it, start typing 1234567890
4. Observe that the number appears as (213) 456-7890 instead of (123) 456-7890

This was observed using Chrome 55 on Windows 10 and Windows 7. This was not an issue in version 1.14.3 but appears to be an issue in 1.14.5, .6, .7, .8, and .9.

![2017-01-26_15-50-56](https://cloud.githubusercontent.com/assets/7022645/22349848/78a10986-e3df-11e6-818b-748de2c9530f.gif)

**Comment by bodhicittaben** [comment]
Just updated to 1.14.10 and still observe this issue.

Why this is a minor bug? We observe it on Windows 7 and Windows 10 latest Chrome as well as Firefox 46 (slightly out of date, I know).

Any workarounds suggested besides pinning our version to 1.14.3?

**Comment by igorescobar** [comment]
Fixed
