### ISSUE TITLE
máscara para inteiro negativo opcional

### ISSUE THREAD

**Issue by tetri** [igorescobar/jQuery-Mask-Plugin#51]
bom dia,

como criar uma máscara para inteiros com sinal negativo opcional?
não consigo escapar o caractere `-` usando 

`.mask("S9999999999", { translation: { 'S': { pattern: /\-/, optional: true } } });`

**Comment by thiagosimoes1305** [comment]
Isso aqui resolve notas escolares:

```
var maskNota = function(val){
	return ( val.replace(/\D/g, '') == '100' ) ? '10,0' : '0,09';
	},
	optionsZ = {onKeyPress: function(val, e, field, options){
		field.mask(maskNota.apply({}, arguments), options);
	}
};

$('.mask-nota').mask(maskNota, optionsZ);
```
