### ISSUE TITLE
Cursor goes to wrong position

### ISSUE THREAD

**Issue by razoomnick** [igorescobar/jQuery-Mask-Plugin#510]
I have faced with the issue with IBAN mask.

Steps to reproduce:

1. Create a page with the following code:

```
$.jMaskGlobals = {
  translation: {
    '9': { pattern: /\d/ },
    '*': { pattern: /[a-zA-Z0-9]/ }
  }
};
  
$('#txtIban').mask('IT99-****-****-****-****-****-***', {placeholder: 'IT__-____-____-____-____-____-___'});
```

2. Type 000111

3. Put cursor between "0" and "1"

4. Type 1234567891234567891

5. Actual result: 
`IT00-0123-5678-1234-6789-1594-111` 
Expected result: 
`IT00-0123-4567-8912-3456-7891-111`

**Comment by razoomnick** [comment]
https://jsfiddle.net/90731urg/

**Comment by igorescobar** [comment]
@razoomnick I can't overwrite global options like that because you are removing all the other ones... all you need is this:

https://jsfiddle.net/90731urg/1/

Docs: https://igorescobar.github.io/jQuery-Mask-Plugin/

**Comment by razoomnick** [comment]
Thanks @igorescobar. It almost resolved the issue with fast typing. I was able to reproduce it several times but I have to press keys like Jerry Lee Lewis does and it's not a real case.

But the issue with wrong cursor position still exists even in your jsfiddle.

Let's imagine that user wants to type the following iban: IT00-0000-1234-5678-1234-5678-000. One of ways to do that is to type nine zeros and then move cursor to fourth position from the right and type 1234567812345678.

If I do that I get IT00-0000-1234-6781-3456-8725-000.

**Comment by igorescobar** [comment]
@razoomnick if you want to look a way to make it fail... it will eventually :)

**Comment by igorescobar** [comment]
@razoomnick It's working okay here... maybe a screen recording would help.

**Comment by razoomnick** [comment]
Actually, I don't. With regards to fast typing it was just a remark and it's not a real case since I removed jMaskGlobals. You can ignore that :)

Here is a video of cursor moving to wrong position when it's in the middle of the string
https://www.youtube.com/watch?v=Q8CS2mxKSRM

**Comment by onuradsay** [comment]
I can confirm that similar behavior occurs on the documentaiton page. Here is the scenario;
* Go to https://igorescobar.github.io/jQuery-Mask-Plugin/
* Enter a phone number > 1234-5678
* Put cursor after dash > 1234-|5678
* Press del 3 times and remove 567 > 1234-|8
* Enter 567 again > 1234-5867| (However, the expected result is 1234-567|8)

**Comment by roberthgodoy** [comment]
I have same proble :(
