### ISSUE TITLE
Cursor goes to the middle of a string during fast typing

### ISSUE THREAD

**Issue by razoomnick** [igorescobar/jQuery-Mask-Plugin#511]
Steps to reproduce:

1. Create page with the following code

```
$.jMaskGlobals = {
  translation: {
    '9': { pattern: /\d/ },
    '*': { pattern: /[a-zA-Z0-9]/ }
  }
};
  
$('#txtIban').mask('IT99-****-****-****-****-****-***', {placeholder: 'IT__-____-____-____-____-____-___'});
```

2. Put the cursor to the input and type anything quickly.

3. Actual result: cursor goes to the middle of a string. Expected result: cursor should be at the end of a string.

Actually, to reproduce the issue on desktop you should type really quickly. But on mobile it's a real issue and can be reproduced by typing with regular speed.

**Comment by igorescobar** [comment]
@razoomnick please, provide a funtional jsfiddle.

**Comment by igorescobar** [comment]
Duplicated: 510
