### ISSUE TITLE
Chrome AutoComplete throws exception Cannot read property 'length' of undefined on line 

### ISSUE THREAD

**Issue by roysanchez** [igorescobar/jQuery-Mask-Plugin#512]
When a user in chrome uses autocomplete to fill a masked input element as its first value, the library throws the following exception:
```
Uncaught TypeError: Cannot read property 'length' of undefined
    at Object.calculateCaretPosition (VM130 jquery.mask.js:192)
```

after some fiddling the cause seems to be that Chrome autocomplete raises the `input` event from jquery instead of the `paste` event, so the library tries to look for the length of the previous value in `calculateCaretPosition` and as there is no previous value throws the exception.

You can see this repo in fiddler: https://jsfiddle.net/ec0obp78/

I changed the [line 192](https://github.com/igorescobar/jQuery-Mask-Plugin/blob/master/src/jquery.mask.js#L192) to this:
`oValueL = oValue ? oValue.length : 0;`

and it seems to fix it.

Do you want a PR so you can added for your next release?

**Comment by strigona-worksight** [comment]
Aha - that is the issue I was experiencing.. I played around with fixing it. In this case, it appears to not call the "[keydown.mask](https://github.com/igorescobar/jQuery-Mask-Plugin/blob/master/src/jquery.mask.js#L100-L103)" event is not firing.

I had experimented by executing ` el.data('mask-previus-value', el.val());` after line 332 and it appeared to work.

**Comment by Kevin-Chinem** [comment]
Same issue here, roysanchez solution worked fine +1.
strigona, are you sure its not calling the "keydown.mask" and setting el.val() as undefined?

**Comment by igorescobar** [comment]
Guys could you please test this version: https://mixpanel.com/report/1128800/explore/#user?distinct_id=15a32db3df5a3-015643ad0577564-1d317173-13c680-15a32db3df67a5 and see if this works for you? Seems to be also related to #513

**Comment by Kevin-Chinem** [comment]
Works fine here =)

**Comment by simaodeveloper** [comment]
I catch this error using with sp-phones, but the simple workaround was change onKeyPress to onKeyUp, to get at least 1 char in the beginning of typing

```javascript
const behaviorMaskPhoneSP = (val) => val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
const optionsPhoneSP = {
    onKeyUp: (val, e, field, options) => {
        field.mask(behaviorMaskPhoneSP.apply({}, arguments), options)
    }
};
```

**Comment by anitalad28** [comment]
Object.get Regex Mask jQuery-Mask-Plugin.js:141 Uncaught TypeError: Cannot read property 'length' of undefined

Can anyone please help me?
