### ISSUE TITLE
IE: Unable to get property 'length' of undefined or null reference

### ISSUE THREAD

**Issue by yuliankarapetkov** [igorescobar/jQuery-Mask-Plugin#513]
Hola! Thanks for the awesome plugin!

There's a small issue on IE that's actually causing no harm but displaying errors in the browser console. It happens on all IE versions and only on initial loading of the page, when there wasn't a previous value in the input.

> SCRIPT5007: Unable to get property 'length' of undefined or null reference

You can also get the error displayed if you start focusing and blurring on the input. 

The problem is in the **calculateCaretPosition** function on initializing the oValue and oValueL variables. There isn't a previous value of the oValue variable and that's why we're getting the error. This can be easily avoided just by checking if there's a value assigned to the variable.

```
var oValue = el.data('mask-previus-value');
if (!oValue) {
   // Return from the function.
   // Or handle it in a wiser manner than me.
   return;
}
var oValueL = oValue.length;
```

That's it. I don't consider this as a big issue, but still, if you think it is good to be fixed, change it. Cheers, bro!

**Comment by igorescobar** [comment]
Hello @yuliankarapetkov !

Thanks for sharing this with me.

Can you test this version: https://github.com/igorescobar/jQuery-Mask-Plugin/blob/2f0017fed30b63eb749934f352f31cf3f15d8d32/src/jquery.mask.js

le me know if this works for you and then I can release it ASAP.

**Comment by yuliankarapetkov** [comment]
Hey, sorry for the late response. Yes, it's working correct and your
solution is nicer and cleaner than mine. Thanks and have a nice day!

**Comment by igorescobar** [comment]
@yuliankarapetkov cool and thanks a lot.

The new version (v1.14.10) is already available.
