### ISSUE TITLE
Input not accepting comma or dots.

### ISSUE THREAD

**Issue by RafaelRViana** [igorescobar/jQuery-Mask-Plugin#515]
In a mask money input for an user insert the value 5,50. He needs to type, "5", "5", "0". To complete the mask. Is there a way the user type "5", ",", "5"?

The input mask doesn't accept comma or dots. So, the user needs to type the last zero.

**Comment by igorescobar** [comment]
https://github.com/igorescobar/jQuery-Mask-Plugin#problems-or-questions
