### ISSUE TITLE
Campos HTML, máscara em momentos errados

### ISSUE THREAD

**Issue by marcosbaesse** [igorescobar/jQuery-Mask-Plugin#517]
Os campos html recebem a máscara inicial caso o campo contenha pelo menos um espaço vazio.

Detalhes: http://jsfiddle.net/koa37zjn/

**Comment by marcosbaesse** [comment]
Bem, eu contornei o problema alterando a função

`var maskBehavior = function (val) {
  return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
},
options = {onKeyPress: function(val, e, field, options) {
        field.mask(maskBehavior.apply({}, arguments), options);
    }
};

$('.phone').mask(maskBehavior, options);`

para

`
var maskBehavior = function (val) {
	if (val == ' ')
  	return '';
  return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
},
options = {onKeyPress: function(val, e, field, options) {
        field.mask(maskBehavior.apply({}, arguments), options);
    }
};

$('.phone').mask(maskBehavior, options);`

**Comment by igorescobar** [comment]
@marcosbaesse Sorry. Not a bug. Just don't return the empty string or trim it in your code.
