### ISSUE TITLE
$(..).mask is Not a Function, Requiring Wrong?

### ISSUE THREAD

**Issue by Crowes** [igorescobar/jQuery-Mask-Plugin#518]
I have followed the instructions like so:

``npm i jquery-mask-plugin --save``.

``require('jquery-mask-plugin');``

``$('#myElement').mask('A000');``.

Though, the console throws the error that the ``.mask`` method does not exist. FYI, I'm using Electron and have required it in the renderer process, so unless the require identifier is wrong, I don't understand why it does not work.

**Comment by thalisvilela** [comment]
Is this typho: require('jquery-mask-plugin`); (observe the diferent quoting at the end of the string) in your code too? Or just here?

**Comment by Crowes** [comment]
Just here.

**Comment by thalisvilela** [comment]
Make sure you have already included Jquery when you call `require('jquery-mask-plugin');`
Try ensuring JQuery is set like this:
`window.$ = window.jQuery = require('jquery');`
Then ensure the mask plugin is set everywhere:
```
var mask = require('jquery-mask-plugin');
$.mask = mask;
window.mask = mask;
```
