### ISSUE TITLE
Assign a default value for the 9

### ISSUE THREAD

**Issue by reimax** [igorescobar/jQuery-Mask-Plugin#520]
by default in plugin:
translation:{
0:{pattern:/\d/},
9:{pattern:/\d/,optional:!0},
"#":{pattern:/\d/,recursive:!0},
A:{pattern:/[a-zA-Z0-9]/},
S:{pattern:/[a-zA-Z]/}
}

if I need pattern for phone number:
+39 (###) ###-##-##

default settings for 9 ignored my pattern +39
and in the field, you can enter the numbers of the form 
36 (###) ### - ## - ##
37 (###) ### - ## - ##

**Comment by aditya1122** [comment]
i also want to know how to fix the number 9

**Comment by igorescobar** [comment]
@reimax  use the fallback. check out the docs.
