### ISSUE TITLE
Editing input does not change the model value properly

### ISSUE THREAD

**Issue by felipedrumond** [igorescobar/jQuery-Mask-Plugin#522]
I have an input field with the following mask: 99999-999

When I type 12345-78 and them add '6' right after '5', the view shows 12345-678 (correct), but the model value is 123456-78 (wrong)

The image below shows the input with the correct value (well formated), and the text above the input is the {{ model }} value.

<img width="119" alt="screen shot 2017-02-24 at 11 21 30" src="https://cloud.githubusercontent.com/assets/17038136/23306736/84e147be-fa83-11e6-8f84-1e5891b92230.png">

**Comment by felipedrumond** [comment]
@igorescobar, não sabia que você sabe português :-)
Creio que estes problemas estão acontecendo porque eu estou usando seu plugin com Angular2. No Angular 2, o valor da view pode ser um, e do model outro.

Creio que este tipo de problema não ocorra ao usar seu plugin num site com html/angularjs, correto?

<img width="89" alt="screen shot 2017-02-24 at 11 46 43" src="https://cloud.githubusercontent.com/assets/17038136/23307651/095c42a2-fa87-11e6-9a03-494892a85199.png">

**Comment by igorescobar** [comment]
@felipedrumond Sua mascara esta errada. `00000-000` é a correta. Issues relacionadas a caret positioning deve ter sido corrigida na ultima versão.

**Comment by felipedrumond** [comment]
@igorescobar Realmente foi corrigida. Na ocasião eu acabei me esquecendo de vir aqui informar. Muito obrigado!
