### ISSUE TITLE
Mask function not working in input while we use with jquery.autotab.js plugin

### ISSUE THREAD

**Issue by ilaiyaraja** [igorescobar/jQuery-Mask-Plugin#523]
Hi,

Anyone please help me to solve this issue.

Mask function is not working in input when we use both mask plugin and jquery.autotab.js plugin. Without autotab plugin mask is working fine. I don't know what is conflicting with these. Please guide me.

jquery.autotab.js plugin link: https://github.com/Mathachew/jquery-autotab

**Comment by igorescobar** [comment]
@ilaiyaraja This is an issue with `autotab` not jQuery Mask Plugin. Looking into their code I can see that they aren't using events with namespaces that's why things are conflicting.
