### ISSUE TITLE
Correct Usage of the Data-Mask Attribute

### ISSUE THREAD

**Issue by DomSles** [igorescobar/jQuery-Mask-Plugin#524]
Hello!

Does anyone know the correct usage of the data-mask attribute on elements?

I've read the documentation and from what i gather you add the attribute to the element and call the plugin, like so ([http://jsfiddle.net/tzq43560/](http://jsfiddle.net/tzq43560/)) - 

`<input type="text" value="01234567890" data-mask="00000 000 000">`
`$('input').mask();`

But that results in a 'Cannot read property 'length' of undefined' error.

I'm sure it's something simple and/or i've missed something but any help will be appreciated 👍

**Comment by igorescobar** [comment]
@DomSles The problem here is that you should always load your javascript files at the end of your `<body>` (it's a best practice). If you don't want to do that, you should right after loading your javascript file set up a global options called `watchDataMask` to true. (it is in the docs)
