### ISSUE TITLE
How do I accomplish an email address mask and can the plugin keep within a range?

### ISSUE THREAD

**Issue by davea38** [igorescobar/jQuery-Mask-Plugin#525]
As the subject says, I was wondering how to accomplish two things:

1. An email mask.
2. A percentage (0 - 100).

Can this be done?

Thanks in advance for a very nice plugin :)

**Comment by igorescobar** [comment]
1. no
2. https://github.com/igorescobar/jQuery-Mask-Plugin#problems-or-questions
