### ISSUE TITLE
How to make money mask allways show decimal point?

### ISSUE THREAD

**Issue by stefan-beyer** [igorescobar/jQuery-Mask-Plugin#527]
How can I get a behavior like:
Initially 0,00 is shown.
I type "1" - 0,01 is shown.
I type "2" - 0,12 is shown.
I type "3" - 1,23 is shown.
and so on

**Comment by stefan-beyer** [comment]
I fiddled something:  http://jsfiddle.net/c6qj0e3u/11/
There must be a better solution I hope!?

**Comment by ehSistemas** [comment]
+1

**Comment by gmergel** [comment]
+1

**Comment by igorescobar** [comment]
https://github.com/igorescobar/jQuery-Mask-Plugin#problems-or-questions
