### ISSUE TITLE
Formatação tardia

### ISSUE THREAD

**Issue by germanolucas** [igorescobar/jQuery-Mask-Plugin#53]
Prezados, fiz um teste com a versão v1.1.1 do plugin para testar uma máscara dinâmica entre CPF e CNPJ. O código está em http://jsfiddle.net/zWPs7/1/, o único detalhe adicional é que no meu código "d.byPassKeys = [];". O que ocorre é que quando digito um número 12345678900 a máscara formata corretamente tal número como CPF, mas, se eu digitar mais um dígito (ex.: 123456789000), em vez da máscara chavear para máscara de CNPJ exibindo 12.345.678/9000, a máscara continua com o formato do CPF exibindo 123.456.789-000. Da mesma forma ocorre ao apagar dígitos, é como se a máscara estivesse "demorando um dígito a mais para chavear". Lembrando que na versão v0.11.4 a mudança de máscara funcionava corretamente.

**Comment by GustavoDMS** [comment]
A mesma coisa acontece comigo. Detalhe estou usando Bootstrap.

**Comment by ufocruz** [comment]
Continua não funcionando. Acabei de baixar e testar

**Comment by matmiranda** [comment]
@jorgesomers na documentação já tem um exemplo [aqui](https://igorescobar.github.io/jQuery-Mask-Plugin/docs.html#mask-as-a-function).

Veja rodando: [JsFiddle](http://jsfiddle.net/znuph72f/264/).

**Comment by jorgesomers** [comment]
Ola caro @matmiranda muito obrigado !
Valeu mesmo.. está lindo .. ficou muito bacana mesmo.. 
Obrigado !
