### ISSUE TITLE
Strange behavior when using translation

### ISSUE THREAD

**Issue by lisandroTSilva** [igorescobar/jQuery-Mask-Plugin#531]
I am using translation to facilitate the format of hours. Here is an example in the gif, but basically it is to put a zero before the digit if it is bigger than 2. In the first edition works perfectly, however if the text is selected `Ctrl + A` and edited again the editing pointer is lost.

> translation: {
>             '2': {
>                 pattern: /[0-2]/,
>                 fallback: '0'
>             },
>             '5': {
>                 pattern: /[0-5]/,
>                 fallback: ''
>             }
>         }

![querymask](https://cloud.githubusercontent.com/assets/794679/24217208/db522a92-0f1d-11e7-9048-cb9958c1bf58.gif)

**Comment by igorescobar** [comment]
I believe this is fixed now.
