### ISSUE TITLE
Number pattern inserting the ) character at the end

### ISSUE THREAD

**Issue by amrigo** [igorescobar/jQuery-Mask-Plugin#537]
Hi 

I try to create a mask for Brazilian car plates, using the format: AAA0000 .

It is inserting a ) character at the final 

How can i avoid the ) character  ?

$('.placaBrasil').mask('AAA0000)', {'translation': {
            A: {pattern: /[a-zA-Z]/},
            0: {pattern: /[0-9*]/}
          }
    });

**Comment by igorescobar** [comment]
@amrigo remove the ) at the end of the mask and you are good to go.

**Comment by amrigo** [comment]
Thank you Igor, did not look at that line,now it working!
