### ISSUE TITLE
Value chopping off

### ISSUE THREAD

**Issue by VD17593** [igorescobar/jQuery-Mask-Plugin#547]
A suggestion.

When typing a value that doesn't correspond, even if the translation is optional, the remaining value is chopping off : 

> Allowing only numbers ; initial value '1234' ; typing 'a' between '2' and '3' gives : '12'

I would like to have all allowed values.

Except if anyone has a suggestion with the parameter setting , I changed this : 

```
Lines 282 - 283 

Replaced :
        m += offset;
        v -= offset;

By (same code as found above) :

      if(m != maskLen-1){
             m += offset;
             v -= offset;
      }else{   		
             if (translation.recursive) {
                    if (resetPos === -1) {
                          resetPos = m;
                    } else if (m === lastMaskChar) {
                          m = resetPos - offset;
                    }

                    if (lastMaskChar === resetPos) {                                        
                            m -= offset;
                    }
               }
                m += offset;
                        		
        }

```

Again, if there was a parameter for this functionality, I didn't found it.

Regards

**Comment by igorescobar** [comment]
@VD17593 I don't think I followed what you meant.

**Comment by VD17593** [comment]
I experienced this problem with my implementation: when tying to insert a character not allowed (eg a letter when only a number is expected) then the remaining characters are lost.
To correct this I added above code.

It's just a suggestion. Feel free.

**Comment by igorescobar** [comment]
@VD17593 Can you provide a functional jsfiddle showing your issue?

**Comment by VD17593** [comment]
Here is a [fiddle](https://jsfiddle.net/VD17593/r5ocmhsa/)

When you enter 12345.
And between 2 and 3 you enter a letter then 345 is lost.

**Comment by igorescobar** [comment]
@VD17593 You can't have ALL you mask digits as optional. Doesn't make sense and will create confusion with the algorithm. 
I've changed a bit and now it isn't chopping digits anymore: https://jsfiddle.net/r5ocmhsa/13/

**Comment by VD17593** [comment]
The problem now is that you can't enter this number:

.123

**Comment by igorescobar** [comment]
@VD17593 You can't because your mask says you can't :)

Changed to this: 
https://jsfiddle.net/r5ocmhsa/14/

Now you can.

**Comment by igorescobar** [comment]
@VD17593 I realized that you are trying to accomplish and I recommend you to read the FAQ:
https://github.com/igorescobar/jQuery-Mask-Plugin#problems-or-questions

**Comment by VD17593** [comment]
I have looked at the different options, and havn't found what I needed.

So I just want a number (integer or float), possibly with sign to be allowed.
A few weeks ago I have been looking at different combinations, without finding what I really wanted.
That's why I used the mask in my initial fiddle.

With you last example you could enter for example:

123.456.789

**Comment by igorescobar** [comment]
@VD17593 that's why I'm kindly asking you to read the FAQ.
