### ISSUE TITLE
Bad number mask in first 2 digits

### ISSUE THREAD

**Issue by marcosbaesse** [igorescobar/jQuery-Mask-Plugin#550]
In a field with the following definition of masks:

$ ('.money').mask ('000.000.000.000.000,00', {reverse: true});
$ ('.money2').mask ("#. ## 0.00", {reverse: true});

If the user enters two digits, an integer value is returned.
Example:
11
Returns
11 (monetary value would be 11.00)

But if the user enters three digits, a decimal is returned (as expected):
Example:
111
Returns
1.11

This error also occurs on the plugin's disclosure page:
Https://igorescobar.github.io/jQuery-Mask-Plugin/

This error is also likely to occur with percentage masks.
It would be interesting to replace them with a mask similar to that used in 'Crazy Zip Code'.

**Comment by gmergel** [comment]
Completely agree with marcos.

Typing 11 should give me monetary value of 0.11, not 11.00.

**Comment by igorescobar** [comment]
https://github.com/igorescobar/jQuery-Mask-Plugin#problems-or-questions
