### ISSUE TITLE
Input is being typed backwards

### ISSUE THREAD

**Issue by marychloe** [igorescobar/jQuery-Mask-Plugin#551]
Enter a number in the phone field with the following mask:
$("#mobile-num").mask("+1 (000) 000 0000");
Select all contents in the input field
Try typing numbers again

Input will be entered backwards.

When you select all and delete first, it will enter the numbers correctly. But if you enter a number right away, it will be backwards.

This doesn't happen when there are no special characters like () or +1.

**Comment by igorescobar** [comment]
I believe this is fixed now.
