### ISSUE TITLE
Problem when type a letter in a value mask - Mobile

### ISSUE THREAD

**Issue by deyvisonsouto** [igorescobar/jQuery-Mask-Plugin#552]
When Type a letter in a mask like this $("#Valor").mask("99.999.999.999,99", { reverse: true });

the entire mask bugs and clear the field and put only the points.

Chrome - 58.0.3029.83
Device - GTN8010 - Android 4.1.2

**Comment by igorescobar** [comment]
@deyvisonsouto your mask is wrong buddy. replace the `9`s by `0`s
