### ISSUE TITLE
On the fly mask not working

### ISSUE THREAD

**Issue by iamjonathankush** [igorescobar/jQuery-Mask-Plugin#554]
Here is my code:
    var options =  {onKeyPress: function(cep, e, field, options){
 		      var masks = ['(000) 000-0000', '0000000000000000'];
 		      var mask = (cep.length>14) ? masks[1] : masks[0];		
 		     $('.phone-us').mask(mask,options);
 	}};
 	$('.phone-us').mask('(000) 000-0000',options);
It doesn't use the second mask when the length is greater than 14

**Comment by igorescobar** [comment]
https://github.com/igorescobar/jQuery-Mask-Plugin#bugs
