### ISSUE TITLE
Problem on mask with long decimal place

### ISSUE THREAD

**Issue by LeoJMrozek** [igorescobar/jQuery-Mask-Plugin#555]
I have a mask for a number for a monetary calculation: $(".txt").mask("?9.999999"). The problem comes in (and it may be in how I am using it). When the page first loads, it is loaded with a value like "9.123456"
 (notice it is < 10 so the optional character is not there).

The problem comes in when a user goes to the end of the number and deletes the 6 and changes it to 7. The number temporarily goes to "?9.12345" then the 7 is added the end to make "9.123457" but it displays "?9.123457." 

In this page, the number is part of a calculation that returns "NaN" because the question mark is being considered part of the value. Right now I think I have to put in code to strip the "?" from the string before the calculation, but I don't think it should even show it when the user modifies the number this way. (FYI, I am using the mask in a rebuild of this page and our users do this many times a day on the current page at this control doing "What-If' on the text box by changing the number out a the end to see how it affects the rest of the calculation.

Thanks.

**Comment by igorescobar** [comment]
Sorry @LeoJMrozek but read our FAQ:
https://github.com/igorescobar/jQuery-Mask-Plugin#problems-or-questions
