### ISSUE TITLE
Zepto v1.2.0 compatibility 

### ISSUE THREAD

**Issue by allanesquina** [igorescobar/jQuery-Mask-Plugin#559]
Hi, I'm trying to use this plugin with [Zepto](http://zeptojs.com/) and I'm getting the following error:
![image](https://cloud.githubusercontent.com/assets/3584636/26503944/106d5110-4219-11e7-8ed3-a74d88ac5368.png)

I realized that Zepto's `data` function is returning a number instead string. 
I've changed this [line](https://github.com/igorescobar/jQuery-Mask-Plugin/blob/master/src/jquery.mask.js#L191) to the following code and seems to be solved, but I'm not sure about the whole plugin. 
```javascript
  oValue  = el.data('mask-previus-value').toString() || '',
```
Could you please take care about that?

Thanks man, :+1:

**Comment by igorescobar** [comment]
@allanesquina can you open a PR with the fix? thanks!

**Comment by allanesquina** [comment]
Sure, no worries. 
:+1:

**Comment by allanesquina** [comment]
Hey man, my bad, sorry, the `data` module wasn't being loaded, I had a content type problem here. 
Now it's working fine. :+1: 
You've done a good job on that plugin. Thx!

**Comment by igorescobar** [comment]
:D
