### ISSUE TITLE
Android Samsung Keyboard - Predictive Text Problem

### ISSUE THREAD

**Issue by ericksonlbs** [igorescobar/jQuery-Mask-Plugin#560]
Hi, i had problem in Android with Samsung Keyboard using Predictive Text, for to fix this i changed line 64. (jQuery.Mask)

from:
cSelStart = ctrl.selectionStart;

to:
cSelStart = ctrl.selectionEnd;

Can you to see problem this way? If no, can you continue with this fix in next version?

**Comment by igorescobar** [comment]
@ericksonlbs is this still happening with latest version? Let me know and I will re open it.

**Comment by rupeshdabbir** [comment]
This is still happening with latest version
