### ISSUE TITLE
IE 9 issue Unable to get property 'length' of undefined 

### ISSUE THREAD

**Issue by josedesa** [igorescobar/jQuery-Mask-Plugin#561]
Thank for this amazing plugin. IE9 throws the issue  "Unable to get property 'length' of undefined or null reference" in "  var newValL = newVal.length,"  of calculateCaretPosition function.

**Comment by igorescobar** [comment]
@josedesa is this still happening on the latest version?

**Comment by ikr0m** [comment]
It was not working with 1.14.10 version. It is working with 1.14.12 version. Thanks!
