### ISSUE TITLE
Setar máscara após set value via javascript

### ISSUE THREAD

**Issue by diegosilvagit** [igorescobar/jQuery-Mask-Plugin#563]
Boa tarde

Estou com um problema, que na verdade acontece as vezes sim e outras não.
Eu estou usando $('#form #campo').val(data).trigger('input'); para ajustar a mascara depois que eu setar o valor.
Se eu não dou nenhum post ou via ajax ele funciona certinho, mas as vezes quando faço uma chamada via ajax por um botão ou onchange, ele não funciona depois o trigger('input').
Posso clicar para visualizar que não vai, ele seta o valor, mas a mascara não atualiza. 
Eu preciso limpar o campo, e digitar novamente, ai funciona, mas se depois eu faço outra chamada ajax, ele não funciona novamente.

Já passaram por algo parecido?

**Comment by raaffaaeell** [comment]
Acho que você tem que usar o bind ou on nesse caso, não ? eu não lembro direito agora, isso acontece comigo quando algum elemento é criado dinamicamente ou algo do tipo

**Comment by diegosilvagit** [comment]
Então eu não crio nada dinamicamente, única coisa que faço é tenho um campo cep que no onchange, busco o cep e atualizo os campos, após isso o trigger('input') não funciona mais, como eu disse tenho que apagar e informar novamente para pegar a mascara.

**Comment by raaffaaeell** [comment]
Você ta tentando setar um valor e dai aplicar a mascara ? Eu acho que não entendi direito ainda.

Se for isso, você ja tentou esse metodo `$('.date').masked('19840807');` (ta no exemplo das demonstrações)

**Comment by diegosilvagit** [comment]
Eu achei o que pode ser. Pode ser loucura, mas pelo que testei até agora é isso mesmo.
Quando eu digito o valor e clico em TAB para ir para o próximo campo ele funciona normalmente, ai eu salvo o registro, quando vou visualizar o mesmo, ele não atualiza a mascara usando trigger('input').
Agora eu eu digito o valor e clico no próximo campo (sem usar TAB) e salvo o registro, e depois clico em visualizar, ele atualiza com sucesso a mascara usando trigger('input').

Vou dar uma olhada no js do plugin para ver o que eu acho.

**Comment by diegosilvagit** [comment]
@igorescobar você poderia me falar para que serve o byPassKeys: [9, 16, 17, 18, 36, 37, 38, 39, 40, 91], fazendo favor?
Porque eu tirei o tab 9, do byPassKeys e resolveu meu problema, mas queria saber se vai afetar nas máscaras.

**Comment by diegosilvagit** [comment]
Onde eu consigo setar as variáveis globais e eu consigo setar somente o byPassKeys ?

$.jMaskGlobals = {
                byPassKeys: [9, 16, 17, 18, 36, 37, 38, 39, 40, 91]
            };

Já coloquei dentro $(document).ready(function () { e fora, mas não da certo de jeito nenhum, o plugin da erro.

**Comment by diegosilvagit** [comment]
Retirei o 9 do byPassKeys e funcionou normalmente
