### ISSUE TITLE
Method to get mask used on input

### ISSUE THREAD

**Issue by waghcwb** [igorescobar/jQuery-Mask-Plugin#565]
Is there any way to get the mask that is under use on the input?

I'm trying to make a validation to display a error to the user when he doesn't type all needed characters. This event insn't trigerring on 'onInvalid' event!

To do this, I need to "remake" the logic that applies the mask, so in that way, I know what mask is currently applyed to the field. But if the plugin provide this info, we don't neeed to remake the logic.

**Comment by igorescobar** [comment]
@waghcwb provide a functional jsfiddle please.
https://github.com/igorescobar/jQuery-Mask-Plugin#bugs
