### ISSUE TITLE
`onComplete` not called when selecting from input history via keyboard in Firefox

### ISSUE THREAD

**Issue by msbit** [igorescobar/jQuery-Mask-Plugin#566]
*Brower:* `Firefox 53.0.3 (64-bit)`
*OS:* `macOS 10.12.5`

When selecting a previously entered matching value via the keyboard (using arrow down then tab) the `onComplete` callback is not called.

Illustrated in [this video](https://github.com/igorescobar/jQuery-Mask-Plugin/files/1056909/firefox-keyboard-oncomplete.mov.zip) (drop the `.zip` extension to view).

**Comment by igorescobar** [comment]
@msbit The problem is the browser doesn't fire any event when you select something from the autocomplete. So while there isn't an elegant way to solving this the best solution for you would be set the `autocomplete="off"` this is an issue for you. If you have any thoughts on this, please, share.

**Comment by msbit** [comment]
@igorescobar that's kind of correct, though it does fire the `change` event when the value has changed. I guess I wonder whether that could be used to trigger the same masking behaviour?
