### ISSUE TITLE
On-the-fly mask not working

### ISSUE THREAD

**Issue by anafreitas** [igorescobar/jQuery-Mask-Plugin#567]
Hi, I'm trying to use the on-the-fly mask in a CPF/CNPJ input, but when the input reaches the first mask's max length it's blocks and doesn't let me to continue typing.

Here is a jsfiddle: [http://jsfiddle.net/h2jnbwcc/18/](http://jsfiddle.net/h2jnbwcc/18/)

**Comment by raaffaaeell** [comment]
Ana, try this

`var options = {onKeyPress: function(cpf, e, f, options){
    var masks = ['000.000.000-009', '00.000.000/0000-00'];
    mask = (cpf.length>14) ? masks[1] : masks[0];
    $('#tb').mask(mask, options);
    }};

$('#tb').mask('000.000.000-009', options);`

Your code had another problem, this line `$('#tb').mask('00000-000', options);` you were still using the cep mask there

**Comment by anafreitas** [comment]
It works! Thanks!

**Comment by flavionam** [comment]
does not work on paste value
