### ISSUE TITLE
Mask on mobile changing the keyboard

### ISSUE THREAD

**Issue by rikarudoaranha** [igorescobar/jQuery-Mask-Plugin#568]
I discovered that when we change the keyboard to numeric and type the first digit, the keyboard changes to the letters keyboard. It just happens in the first digit.

**Comment by igorescobar** [comment]
@rikarudoaranha and why do you think that this is a problem related to jQuery Mask Plugin? A functional jsfiddle reproducing the problem would be nice.

**Comment by rikarudoaranha** [comment]
Because i was visitting the https://igorescobar.github.io/jQuery-Mask-Plugin/ to see the behavior of the plugin. I focused the date input, changed the keyboard to the number keyboard and after I typed the first number, it changed back to the char keyboard. To be honest, I don't know if this happen because of the plugin or because the chrome for android, but I guessed that it would be better if you know. This is the fiddle: https://jsfiddle.net/1tj0c14k/2/

**Comment by igorescobar** [comment]
@rikarudoaranha Thanks for that. I can ensure you that we don't do anything related to what you are reporting. This is probably the browser switching to the right keyboard based how you configured your HTML. If you want to ensure numeric keyboard just use the tag ´pattern="[0-9]+"` and the numeric keyboard will show up by default. But you can't have a numeric keyboard if on your field you use string and numbers.
