### ISSUE TITLE
Mask CPF/CNPJ

### ISSUE THREAD

**Issue by wagnerfillio** [igorescobar/jQuery-Mask-Plugin#571]
Olá!
Adicionei a função para contemplar tanto CPF quanto CNPJ no mesmo campo.

Porem ao digitar um CNPJ, a entrada de mask CNPJ retorna para CPF.

O máximo de caracteres que obtenho é isto: 000.000.000.000

Como corrigir ?

**Comment by raaffaaeell** [comment]
Seria bom saber o seu código pra ver o que ta errado (ou de preferencia um jsfiddle)

Mas esse código deve resolver o seu problema

var options = {onKeyPress: function(cpf, e, f, options){
var masks = ['000.000.000-009', '00.000.000/0000-00'];
mask = (cpf.length>14) ? masks[1] : masks[0];
$('#tb').mask(mask, options);
}};

$('#tb').mask('000.000.000-009', options);

**Comment by wagnerfillio** [comment]
Este não funcionou, o que estou utilizando é como este:

Outra coisa, não consigo carrega-lo num .js externo.

Somente como <script> código </script> no próprio html.

var options = {
  onKeyPress: function(cpf, ev, el, op){
    if(cpf.length > 14) eh_cnpj();
	if(cpf.length < 15) eh_cfp();
    var masks = ['000.000.000-000', '00.000.000/0000-00'],
        mask = (cpf.length > 14) ? masks[1] : masks[0];
    el.mask(mask, op);	
  }
}
$('#cpf_cnpj').mask('000.000.000-000', options);

**Comment by raaffaaeell** [comment]
Sobre não conseguir separar o código em outro arquivo, você tem certeza que ta carregando tudo na ordem certa ? Primeiro as dependencias depois o seu arquivo ? E outra, que erro que dá ?
Outra coisa, o ultimo digito no seu código precisa ser o 9, não 0 (pra dar certo)

**Comment by igorescobar** [comment]
@wagnerfillio Sem um jsfiddle eu não posso te ajudar. Re-abro a issue quando tiver.
