### ISSUE TITLE
Cursor goes to the wrong position after a new mask is applied

### ISSUE THREAD

**Issue by gilbarbara** [igorescobar/jQuery-Mask-Plugin#572]
Hey,

You can see this behavior here (http://jsfiddle.net/h2jnbwcc/1/) when you type that seventh character and the cursor goes to a new position.

thanks

**Comment by Guihgo** [comment]
this older version don't have this error: 
[](https://pastebin.com/duW93HBn)

**Comment by sistemaswebbrasil** [comment]
In the current version V1.14.11 returned to the same problem.

**Comment by igorescobar** [comment]
@gilbarbara thanks for that. This is related to the new caret positioning logic when using on the fly mask updates. I will look into it ASAP.

**Comment by sadfuzzy** [comment]
@igorescobar any progress?

**Comment by credencie1** [comment]
@igorescobar Any progress? I'm using version 1.14.16 and that is still happening. The caret appears before the last number when change mask from CPF to CNPJ.

**Comment by marcos-queiroz** [comment]
I can't use the CPF and CNPJ mask

CPF / CNPJ: <input type="text" class="crazy_cep" name="crazy_cep" id

var options =  {
  onKeyPress: function(cpfcnpj, e, field, options) {
    var masks = ['000.000.000-00', '00.000.000/0000-00'];
    var mask = (cpfcnpj.length>11) ? masks[1] : masks[0];
    $(this).mask(mask, options);
}};

$('.crazy_cep').mask('000.000.000-00', options);

**Comment by marcos-queiroz** [comment]
I got it with the following example:

    var CpfCnpjMaskBehavior = function (val) {
        return val.replace(/\D/g, '').length <= 11 ? '000.000.000-009' : '00.000.000/0000-00';
    },
    cpfCnpjpOptions = {
        onKeyPress: function(val, e, field, options) {
            field.mask(CpfCnpjMaskBehavior.apply({}, arguments), options);
        }
    };
    
    $(function() {
        $('.mask-cpfcnpj').mask(CpfCnpjMaskBehavior, cpfCnpjpOptions);
    });
