### ISSUE TITLE
HTML5 Patterns for Dates

### ISSUE THREAD

**Issue by dademaru** [igorescobar/jQuery-Mask-Plugin#574]
Hi,

I'm trying to use [HTML5 Patterns for Dates](http://html5pattern.com/Dates) 

```
$( "#date" ).mask('YYYY-MM-DD', {
	'translation': {
		Y: {pattern: /(?:19|20)[0-9]{2}/},
		M: {pattern: /(0[1-9]|1[012])/},
		D: {pattern: /(0[1-9]|1[0-9]|2[0-9]|3[01])/}
	}
});
```
But it doesn't work.
Any idea?

Thanks
Davide

**Comment by igorescobar** [comment]
@dademaru It doesn't work like that. Those patterns work if you consider the entire input value and not a single digit at a time.
