### ISSUE TITLE
Test Page with examples

### ISSUE THREAD

**Issue by brunotdantas** [igorescobar/jQuery-Mask-Plugin#576]
Hello @igorescobar 

Thanks for this mask solution. That was a great work that you and the others did. 

I saw the [page](https://igorescobar.github.io/jQuery-Mask-Plugin/):   but in my opinion the approach on **how to use** the mask solution could be better, for example have a test.html page  that the user can download with the solutions applied.

Here is an example of what I'm trying to say : https://www.w3schools.com/bootstrap/bootstrap_get_started.asp

Have a great day.

**Comment by igorescobar** [comment]
Hey there @brunotdantas!

Thanks for your feedback! We will try to improve it!
