### ISSUE TITLE
mutil-date input 

### ISSUE THREAD

**Issue by chenjf2k** [igorescobar/jQuery-Mask-Plugin#577]
example:

![image](https://user-images.githubusercontent.com/18625683/28322356-79a487b6-6c08-11e7-9cef-e4e9118042e8.png)

**Comment by igorescobar** [comment]
?????????????

**Comment by chenjf2k** [comment]
my problem is input many date in a textbox

**Comment by igorescobar** [comment]
https://github.com/igorescobar/jQuery-Mask-Plugin#bugs
