### ISSUE TITLE
Optional character doesn't work in samsung mobile

### ISSUE THREAD

**Issue by jodinathan** [igorescobar/jQuery-Mask-Plugin#578]
This doesn't work in Samsung S7:

$('.ip_address').mask('0ZZ.0ZZ.0ZZ.0ZZ', {
    translation: {
      'Z': {
        pattern: /[0-9]/, optional: true
      }
    }
  });

It doesn't let you type in any Z spot.

**Comment by igorescobar** [comment]
@jodinathan I can't help you if you don't read the guidelines for opening issues.
