### ISSUE TITLE
Masked elements after .clone()

### ISSUE THREAD

**Issue by argentinaspy** [igorescobar/jQuery-Mask-Plugin#579]
Hello, 
i have a form with some masked inputs and they also can be multiplied/cloned.
how to use .mask on new elements?

example code:
https://jsfiddle.net/j1412t2w/1/

i've tryed: 
1. same selector, 
2. another new selector (".cloned_ip"), 
3. clear handlers (.off()) at cloned elements,
4. unmask all elements and .mask again all of them on click event;

system req: ie8

ty

**Comment by igorescobar** [comment]
@argentinaspy use `.clone();` without the true argument and you are good to go.
