### ISSUE TITLE
how do i mask a read-only input 

### ISSUE THREAD

**Issue by Zabanya** [igorescobar/jQuery-Mask-Plugin#580]
<div class="form-group">
        <div class="input-group">
            <span class="input-group-addon"> Total </span>
                <input class="form-control dpp text-right" type="text" value="{{$total}}" readonly/>
        </div>
    </div>

script:
    
    $('body').on('load', 'input.form-control.text-right', function () {
         formatNumber();
    });
    function formatNumber() {            
        $('input.form-control.text-right').maskNumber({decimal: ',', thousands: '.', integer: true});
    }

it did not fire, how do i do this?

**Comment by igorescobar** [comment]
@Zabanya I believe you are on the wrong plugin :)

**Comment by Zabanya** [comment]
thanks for info, quick ddg brought me here. ;)
