### ISSUE TITLE
VALIDAR CPF

### ISSUE THREAD

**Issue by carlosalbertocruz** [igorescobar/jQuery-Mask-Plugin#581]
Como validar um campo de cpf, ja procurei em todos os lugares e tentei implementar, mais sem sucesso :(

**Comment by ruanltbg** [comment]
@carlosalbertocruz isso te ajuda? https://pt.stackoverflow.com/questions/51340/como-validar-cpf-no-lado-do-cliente-com-script

**Comment by igorescobar** [comment]
https://github.com/igorescobar/jQuery-Mask-Plugin#problems-or-questions
