### ISSUE TITLE
E-mail Mask

### ISSUE THREAD

**Issue by igorescobar** [igorescobar/jQuery-Mask-Plugin#582]
This is just for future reference. Those who want to accomplish some sort of help on e-mail fields here is my explanation about this topic:
https://stackoverflow.com/a/34138169/1250728

**Comment by nullmem** [comment]
A better solution would be to include allowed special characters before the @ and only letters, numbers, and dashes and dots after. For sanity, I limited the local or "user" and domain part to 50 characters each.

This solution is not 100% accurate as a valid email can contain other characters and even an @ inside the user part of the email as long as they are enclosed in quotes. I simply excluded those extra characters and the @ in the user part of the email for simplicity. Also, a valid domain cannot start or end with a dash. With these limitations, I think this solution combined with good back-end validation is "good enough."

`
$(#'selector').mask("L".repeat(50) + "@" + "D".repeat(50), {
    translation: {
        "L": { pattern: /[\w\.!#$%&'*-+/=?^`{|}~]/, recursive: true, optional: true },
        "D": { pattern: /[\a-z0-9\-.]/, recursive: true, optional: true }
    }
});
`
