### ISSUE TITLE
Using Regex as a mask

### ISSUE THREAD

**Issue by wyeack** [igorescobar/jQuery-Mask-Plugin#584]
I currently have a field that is validated using this regex:

`(((?=.{3,51}$)[a-z0-9]+\-[a-z0-9]+)|[a-z0-9]`

This basically ensures that input will be between 3 and 51 characters, and composed of lowercase letters, digits and an optional single hyphen that cannot be at the beginning or the end.

I am having trouble translating this into a mask that I can use with jQuery validate, since (as i understand it) the regex mask used for your library refers only to individual entries which do not have an understanding of what other entries exist.  This is the closest that I have gotten:

`
$(s.GetInputElement()).mask('XZZZZZZZZZZZZZZZZZZZZYZZZZZZZZZZZZZZZZZZZZ', {
	translation: {
		'X': { pattern: /[a-zA-Z0-9]/, optional: false },
		'Z': { pattern: /[a-zA-Z0-9]/, optional: true },
		'Y': { pattern: /[-]/, optional: true }
	}
});
`

This ensures that there is a non-hyphen in the beginning and allows for a hyphen in the middle. However, if you are in the middle of the entry and you insert a second hyphen, everything after it gets deleted, for instance:
https://www.screencast.com/t/gstpi4ed4T

Is there another way to approach this to get it working?

**Comment by igorescobar** [comment]
@wyeack would you mind setting up a jsfiddle reproducing your problem? The screencast is great but I can't start hacking with it :)

It's all on: https://github.com/igorescobar/jQuery-Mask-Plugin/blob/master/ISSUE_TEMPLATE.md

Thanks!
