### ISSUE TITLE
Variable max length to the mask

### ISSUE THREAD

**Issue by amilagres06** [igorescobar/jQuery-Mask-Plugin#586]
I have an input with maxlength=100. I'd like to have the option to repeat the pattern for all the chars without need to input in the mask multiples 'X'. Follow the fiddle with the pattern and multiple 'X'.

http://jsfiddle.net/6pco4om7/744/

**Comment by igorescobar** [comment]
You have three alternatives:
```javascript
       $('#iptUsuario').mask('X', {'translation':{
			 'X': {pattern: /^[a-z0-9\_\.]+$/, recursive: true}
		}
	});
```

Or 

```javascript
       $('#iptUsuario').mask('X'.repeat(100), {'translation':{
			 'X': {pattern: /^[a-z0-9\_\.]+$/}
		}
	});
```

Or

```javascript
       $('#iptUsuario').mask(Array(100).join("X"), {'translation':{
			 'X': {pattern: /^[a-z0-9\_\.]+$/}
		}
	});
```

More info, read the docs: https://igorescobar.github.io/jQuery-Mask-Plugin/
