### ISSUE TITLE
Reapply a mask every time a button is clicked

### ISSUE THREAD

**Issue by trajber** [igorescobar/jQuery-Mask-Plugin#588]
I'm trying to re-apply a mask on a div element that is updated when a button is clicked.

I've created a [JSFiddle here](https://jsfiddle.net/g0h3ggx1/2/) as an example. As you can see, the div is 'masked' on page load but it's not updated when the button is clicked.

How can I reformat a field every time a button is clicked?

**Comment by trajber** [comment]
Nevermind guys.

I've found a simple solution: Just triggering a 'input' event on the 'div' solves the problem  [as you can see here](https://jsfiddle.net/g0h3ggx1/3/)

Please, correct me if there's a more simple or idiomatic way to do it.
Thanks.

**Comment by igorescobar** [comment]
```javascript
   // add 10 on every click
    $("#value").text((parseInt($("#value").text()) + 1000) + "");
    
    // this will trigger the re-mask
    $("#value").trigger('input');
```

Have in mind that when you add +10 bucks to the value you need to make sure that sum output has the same output as the mask otherwise the plugin will trim unvalid chars and the outcome won't be what you expect :).
