### ISSUE TITLE
Typing in a decimal point.

### ISSUE THREAD

**Issue by TommySharpNZ** [igorescobar/jQuery-Mask-Plugin#589]
This plugin is great and is going to help us mask phone numbers perfectly!

One issue we have is with decimal numbers. We'd like users to enter numbers but only kick in the decimal point if they type it on their keyboard.

For example,... The user can type"100" and press tab to go to the next field, this should store a value of 100. If they type "100.45" then this should store 100.45.

At the moment if the user types "100" we end up with a value of "1.00" which will frustrate some users if they type quickly through fields.

Is this possible with this plugin?

**Comment by igorescobar** [comment]
Sorry but no.
https://github.com/igorescobar/jQuery-Mask-Plugin#problems-or-questions
