### ISSUE TITLE
International number with prepended "+"

### ISSUE THREAD

**Issue by jucedupp** [igorescobar/jQuery-Mask-Plugin#590]
I have created a mask: "+00 (000) 000-0000

The issue is this:

I cannot find a way to handle single digit international dialing codes.  For example:

The above mask works well with numbers like +27 (071) 123-1234
But when I need to enter, let's say: +1 (071) 123-1234 I am left with the mask applying it as: 
+10 (711) 231-234

How can I have the number  +1 (071) 123-1234 work properly?

Thank you.

**Comment by jmlavoier** [comment]
Hi @jucedupp, try it `+#0 (000) 000-0000`.
