### ISSUE TITLE
Keyboard switches from number back to text on Android (specific versions)

### ISSUE THREAD

**Issue by vicpuntnl** [igorescobar/jQuery-Mask-Plugin#591]
#### Device
Some newer builds of Android. Especially around version 7.1.x the issue pops up.

#### Browser
Chrome 

#### Example:
Already on the plugins's demo-page (https://igorescobar.github.io/jQuery-Mask-Plugin/)

#### Describe de problem depth:
Focus on input, switch to numeric keyboard. Type a number. Now the keyboard switches back to the textual keyboard. On earlier/other versions, as well as on iOS the keyboard remains in the selected mode (numeric/textual)..

**Comment by globsecure** [comment]
+1

**Comment by igorescobar** [comment]
@vicpuntnl this happens because you are typing on a field with letters and numbers. the browsers does that decision, not the plugin. I can't see how I can help with this one because it isn't in my control.  Have you tried to setup the pattern HTML attribute do see how it handles it? like ex: `pattern="[0-9/]+"`

**Comment by vicpuntnl** [comment]
@igorescobar I understand it's the browser's decision, but since real people use this browser, the plugin is kind of "worthless" when it's not able to handle this flaw, and the ux breaks. Which is kinda pitty because the plugin is great!

**Comment by igorescobar** [comment]
@vicpuntnl help me to find a solution. Open issues and tell that this project is now worthless won't fix your problem. 

I understand your point and I would love to fix it but so far I don't know any technology we could use to workaround this once this is A BROWSER CHOICE and NOT A JAVASCRIPT IMPLEMENTATION BUG. 

I encourage you to test any other mask plugin you may want and you wil find the same problem. BUT if you do find someone who fixed this, please I would love to know who did 👍

**Comment by vicpuntnl** [comment]
@igorescobar please don't understand me wrong! I love the project, and it's absolute not worthless. And even if I don't have a solution myself right now I thought it would be better to mention it. 
I'm aware that this is not a bug in the implementation, and I know Chrome on Android has some crazy random issues so now and then. So I hoped that by letting know that there is an issue, a possible solution/workaround might be there, in the heads who know the code best. Which unfortunately isn't there.

**Comment by igorescobar** [comment]
@vicpuntnl I really appreciate you taking the time and opening the issue. Really do. I just did not appreciate the way you expressed your point. From my perspective, it wasn't cool. But, if you didn't mean it, that's fine.

But hey, don't forget,  if you discover a solution, let us know. I would love to fix it.
