### ISSUE TITLE
Dinheiro -  Colocando máscara "0,00" como padrão

### ISSUE THREAD

**Issue by matmiranda** [igorescobar/jQuery-Mask-Plugin#593]
Gostaria de saber, como eu posso definir a mascara "0,00" independendo de "0" digitados ?

Exemplo: 

0.000.000.000.000,00 retorna 0,00
00.000.000.000,00 retorna 0,00
0.000.000.000,00 retorna 0,00
0 retorna 0,00

**Comment by jmlavoier** [comment]
Na [documentação](https://igorescobar.github.io/jQuery-Mask-Plugin/docs.html#translation) - **Recursive digits** está explicando. 

`$('.money_example').mask('#.##0,00', {reverse: true});`
