### ISSUE TITLE
Credit Card Expiration Date - Unexpected behavior on __/20__ mask 

### ISSUE THREAD

**Issue by jmlavoier** [igorescobar/jQuery-Mask-Plugin#594]
## Description
I would like to create a mask to expiration date of credit card. So I didn't find in the documentation, how can I use numbers as a mask. 

### Example
My mask is `$('.expiration-date').mask("99/2099", {placeholder: "__/20__"});`. 

### Happening 
Using [jQuery Mask Plugin](http://jsfiddle.net/xvLzfys4/)

### Expected
I've expected the mask works like `mm/20aa`. Months with 2 digits and Years also with 2 digits.
So after I've typed some thing like `0817` I've expected the `08/2017` as a result. 

Using [jQuery Masked Input](http://jsfiddle.net/355wqp67/) I have what I expected.

*I hope I was clear explaining my expectation about the behavior of this library. Thank you!*

**Comment by jmlavoier** [comment]
I've fixed the expected example.

**Comment by igorescobar** [comment]
If you don't expect the user to type the full year why do you need to display it? The mask could be just:
`$('.expiration-date').mask("00/00", {placeholder: "MM/YY"});` (like stripe does)

But yeah, this plugin doesn't support what you wanted initially which is like a default pre-filled value.
