### ISSUE TITLE
Typing values going backwards on Galaxy Tab A

### ISSUE THREAD

**Issue by JCTirado** [igorescobar/jQuery-Mask-Plugin#595]
When typing a value cursor is always in position 1.

This is only happening on Samsung Galaxy Tab A.
Android version: 6.0.1
Chrome version: 55.0.2883
Jquery Mask Version: v1.14.11

I uploaded a video for a better understanting

[Mask bug.zip](https://github.com/igorescobar/jQuery-Mask-Plugin/files/1228846/Mask.bug.zip)

**Comment by JCTirado** [comment]
Changing cSelStart = ctrl.selectionStart for cSelStart = ctrl.selectionEnd; fixed the problem.

Help found on:
https://github.com/igorescobar/jQuery-Mask-Plugin/issues/560

**Comment by rupeshdabbir** [comment]
Try this: https://github.com/igorescobar/jQuery-Mask-Plugin/pull/602

This should fix the issue.

**Comment by JCTirado** [comment]
Thanks...

I will close this issue
