### ISSUE TITLE
jQuery Mask Plugin and Vue.js

### ISSUE THREAD

**Issue by straube** [igorescobar/jQuery-Mask-Plugin#596]
I'm trying to use this plugin in an application that is using Vue.js 2.x. I'm applying the masks using the `data-mask` HTML attribute. However, the masks won't get applied. Actually, the `maxlength` attribute is added to the field but it seems the events are not bound.

I have a JSFiddle showing what's going on: https://jsfiddle.net/cotvw2q6/

If I simply comment the following line, it works:

    el: '#app'

That proves that there is some conflict between the two libraries. Unfortunately, I cannot remove Vue.js from my project. Well, not without rewriting a couple components using jQuery or vanilla Javascript.

Somebody has any idea how to use this plugin inside a Vue.js app?

**Comment by straube** [comment]
Doing some more tests I've found that if I load the plugin after creating the Vue.js instance, it works. Here is the updated fiddle: https://jsfiddle.net/cotvw2q6/2/

I'm using that solution right now, but it would be nice to know why that happens. :)

**Comment by igorescobar** [comment]
@straube yeah. I'm not that familiar with vue.js so I can't explain to you why that happens. It's always a good practice to load what is most important first and then load the rest... your explanation makes sense for me. It could be vue.js erasing/overwriting jQuery's events.
