### ISSUE TITLE
Como integrar o pugin no angular 2?

### ISSUE THREAD

**Issue by diegoserrat** [igorescobar/jQuery-Mask-Plugin#598]
Boa tarde!

Eu gostaria de saber se é possível integrar o plugin com o angular 2? 
Sou iniciante e não achei nada sobre isso.

Obrigado!

**Comment by straube** [comment]
Have you tried this? #499

**Comment by diegoserrat** [comment]
Hmm, I've take a look on this but as I said I'm a beginner. 
I don't know how to "translate" this directive to a angular 2 directive, if you have a "tutorial" I could use it. 
I didn't found any one :/

**Comment by rodolfojnn** [comment]
Você precisa criar uma diretiva no elemento input. 

No construtor da diretiva faço a injeção do ElementRef, e no AfterViewInit chamo o plugin jquery normalmente.

```
constructor(public el: ElementRef) { }

  ngAfterViewInit() {
    (<any>$(this.el.nativeElement)).mask('00.000.000/0000-00');
  }
```

**Comment by paulosouzainfo** [comment]
Use a jQuery trick using "on" like this...
$(document).on('keyup', '.bornDate', function() {
    $(this).mask('0000-00-00');
  });
