### ISSUE TITLE
CPF e CNPJ no mesmo campo

### ISSUE THREAD

**Issue by guicamarotto** [igorescobar/jQuery-Mask-Plugin#600]
Pessoal, para quem precisar, criei uma logica simples para CPF e CNPJ no mesmo campo.

No caso a mascara só se aplica quando o campo perder o foco. Caso você tenha colocado o CPF e queira trocar para CNPJ, exclua o conteúdo e digite normalmente, a mascara reiniciara.

$(".cpfcnpj").keypress(function () {
        var texto = $(".cpfcnpj").val();

        if (texto != "") {
            var tamanho = $(".cpfcnpj").val().length;
            if (tamanho == 14) {
                $(".cpfcnpj").unmask();
            }
            else {
                $(".cpfcnpj").unmask();
            }
        }
    });

    $(".cpfcnpj").blur(function () {
        
        var texto = $(".cpfcnpj").val();

        if (texto != "") {
            var tamanho = $(".cpfcnpj").val().length;

            if (tamanho > 11) {
                $(".cpfcnpj").unmask();
                $(".cpfcnpj").mask("99.999.999/9999-99");
            }
            else {
                $(".cpfcnpj").unmask();
                $(".cpfcnpj").mask("999.999.999-99");
            }
        } 
    });

**Comment by igorescobar** [comment]
@guicamarotto abro novamente a issue quando disponibilizar um jsfiddle funcional, ok? abraços.
https://github.com/igorescobar/jQuery-Mask-Plugin#bugs

**Comment by guicamarotto** [comment]
opa! blz! segue o jsfiddle
https://jsfiddle.net/acskm91n/1/

**Comment by igorescobar** [comment]
@guicamarotto O jsfiddle não funciona...

**Comment by igorescobar** [comment]
@guicamarotto O que podes usar para resolver o teu problema é este exemplo:
http://igorescobar.github.io/jQuery-Mask-Plugin/docs.html#on-the-fly-mask-changes

**Comment by guicamarotto** [comment]
na verdade não é um problema, é uma contribuição ai pra quem precisar. isso que postei foi um código que fiz que me atendeu aqui para o que eu precisava hehe.
