### ISSUE TITLE
Include mask characters in result.

### ISSUE THREAD

**Issue by beerygaz** [igorescobar/jQuery-Mask-Plugin#603]
I'm using the plugin to capture IP addresses, is there any way to embed the full stop (period) marks into the resulting string?  The mask formats my IP as 192.168.1.1 but the result is 19216811 (so that could be 192.1.68.11 or 192.16.8.11, etc)

Is there an option that I'm missing to achieve this?

**Comment by igorescobar** [comment]
@beerygaz There is an IP example on the project page. Have you seen it?

**Comment by beerygaz** [comment]
@igorescobar I did see it, and my mask works perfectly, but the output does not contain the periods.

**Comment by igorescobar** [comment]
@beerygaz I'm not sure if I followed what you are trying to accomplish here... If your mask are working fine how come the result is 19216811? I think you need to be more visual here because I'm not getting 🦆
