### ISSUE TITLE
import 'jquery-mask-plugin' question

### ISSUE THREAD

**Issue by jhernandes** [igorescobar/jQuery-Mask-Plugin#605]
Is that possible to import JqueryMaskPlugin like:

`import JqueryMaskPlugin from 'jquery-mask-plugin'`

or only via HTML <script> tag?

I've tried but no luck. I'm always getting 

_Uncaught TypeError: $(...).mask is not a function_

I'm new to this import thing, so maybe I'm doing something wrong...

Thanks!

[Import Docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import)

**Comment by igorescobar** [comment]
@jhernandes Have you tried with `require('jquery-mask-plugin')` ?

**Comment by orditeck** [comment]
Simply `import 'jquery-mask-plugin';` ;-)

**Comment by DesenvolvimentoSociisRH** [comment]
> Simply `import 'jquery-mask-plugin';` ;-)

it does not work for me. got `Cannot find module 'jquery-mask-plugin'`

**Comment by orditeck** [comment]
Did you install it through your package manager (i.e. npm/yarn)?

**Comment by DesenvolvimentoSociisRH** [comment]
yes. 

I have installed via npm @types/jquery and jquery-mask-plugin.


![image](https://user-images.githubusercontent.com/48104723/56051324-9c0fd580-5d24-11e9-8623-da738e33b178.png)

**Comment by orditeck** [comment]
It'd seem like you installed the @types for typescript definitions, but not the actual jquery-mask-plugin

**Comment by DesenvolvimentoSociisRH** [comment]
ow. got it. its because the plugin i was including on html file. maybe i got whats wrong now. thanks!!
