### ISSUE TITLE
Trouble with materialize

### ISSUE THREAD

**Issue by YamilBracho** [igorescobar/jQuery-Mask-Plugin#606]
Hi
I am using materialize and I want to masked input a amount. I have this in my document.ready :

> $(document).ready(function () {
            $('#txtMontoCuota').mask('#.##0,00', { reverse: true, selectOnFocus: true });
        });

And when i run my app, i am able to input letters, etc to my input box. I am positive that jquery.mask is loaded..
Any special action that i need to do ?

TIA,
Yamil

**Comment by igorescobar** [comment]
@YamilBracho I can't help you if you don't read the guidelines when opening issues.
