### ISSUE TITLE
Colocar caracteres depois de número

### ISSUE THREAD

**Issue by dardos** [igorescobar/jQuery-Mask-Plugin#609]
Oi Igor,

Tudo bem? 

Gostaria de saber se é possível incluir no input após digitar os números as siglas de centímetro (cm) e quilo (kg). Deu pra entender?

Valeu ai! Esse teu plugin já salvou minha vida diversas vezes!

**Comment by igorescobar** [comment]
https://github.com/igorescobar/jQuery-Mask-Plugin#prefix-or-sufix-on-the-mask  :-)
