### ISSUE TITLE
CPF e CNPJ no mesmo campo

### ISSUE THREAD

**Issue by lucaspaulino** [igorescobar/jQuery-Mask-Plugin#611]
Adicione isto nos seus códigos de exemplo! Até mais! CPF e CNPJ no mesmo campo.

```javascript
       var options = {
		onKeyPress : function(cpfcnpj, e, field, options) {
			var masks = ['000.000.000-000', '00.000.000/0000-00'];
			var mask = (cpfcnpj.length > 14) ? masks[1] : masks[0];
			$('.cpfcnpj').mask(mask, options);
		}
	};

	$('.cpfcnpj').mask('000.000.000-000', options);
```

**Comment by igorescobar** [comment]
Vou deixar aqui para referencia futura e search engines. Obrigado!

**Comment by TiagoFuelber** [comment]
Tentei usar, mas o atributo `maxlength` do input fica sempre com o número da máscara menor, impossibilitando formatar a mascara menor.
Por ex.: 
- Quando recarrego a página: 
```<input class="cpfcnpj" type="text" maxlength="18"></input>```
- Quando começo a digitar atualiza o maxlength para o número da máscara menor
```<input class="cpfcnpj" type="text" maxlength="14"></input>```
- Quando chega aos 14 o input não recebe mais caracteres.

**Comment by pyetrosafe** [comment]
@TiagoFuelber 
Tenta esse código que usamos nos nossos projetos:
```
// Mascara de CPF e CNPJ
var CpfCnpjMaskBehavior = function (val) {
			return val.replace(/\D/g, '').length <= 11 ? '000.000.000-009' : '00.000.000/0000-00';
		},
    cpfCnpjpOptions = {
    	onKeyPress: function(val, e, field, options) {
      	field.mask(CpfCnpjMaskBehavior.apply({}, arguments), options);
      }
    };
```
https://jsfiddle.net/pdd8g4mf/

**Comment by TiagoFuelber** [comment]
Valeu brother, muito bom.

**Comment by raphamatador** [comment]
pyetrosafe 
Funcionou direitinho!!!

**Comment by AndersonMarquess** [comment]
@pyetrosafe 
Muito obrigado =D

**Comment by weidmaster** [comment]
@pyetrosafe Obrigado! Única forma que funcionou! Acho que é um bug do max-length que não calcula direito, no código original.

**Comment by claudemirmendes** [comment]
obrigado @pyetrosafe ! salvou meu dia.

**Comment by joaocarias** [comment]
só contribuindo com o primeiro código, é só trocar o último dígito da máscara cpf de 0 (zero) para 9 (nove) que irá funcionar e não terá problema com o maxlength.

Segue:

var options = {
		onKeyPress : function(cpfcnpj, e, field, options) {
			var masks = ['000.000.000-009', '00.000.000/0000-00'];
			var mask = (cpfcnpj.length > 14) ? masks[1] : masks[0];
			$('.cpfcnpj').mask(mask, options);
		}
	};

	$('.cpfcnpj').mask('000.000.000-009', options);

**Comment by carlosdavi7** [comment]
Show. Top. Funcionou bem. Obrigado.

**Comment by fandrefh** [comment]
> só contribuindo com o primeiro código, é só trocar o último dígito da máscara cpf de 0 (zero) para 9 (nove) que irá funcionar e não terá problema com o maxlength.
> 
> Segue:
> 
> ```
> 
> var options = {
> 		onKeyPress : function(cpfcnpj, e, field, options) {
> 			var masks = ['000.000.000-009', '00.000.000/0000-00'];
> 			var mask = (cpfcnpj.length > 14) ? masks[1] : masks[0];
> 			$('.cpfcnpj').mask(mask, options);
> 		}
> 	};
> 
> $('.cpfcnpj').mask('000.000.000-009', options);
> ```

Show mano, funcionou aqui! Estava desesperado já. ;-)

**Comment by lucas-eedu** [comment]
@pyetrosafe Muito obrigado!

**Comment by gjmucciolo** [comment]
Opa pessoal, tudo certo?

Estava com problemas nessa função no momento em que o meu usuário tentava dar Ctrl+C e Ctrl+V nos CNPJs, então fiz uma pequena alteração no comportamento da Função e resolveu.

Segue meu código com o Ctrl+C e Ctrl+V funcionando tanto para CNPJ quanto para CPF:


```
// Mascara de CPF e CNPJ
var CpfCnpjMaskBehavior = function (val) {
    var length = val.replace(/\D/g, '').length;
    return (length > 11 || length === 0) ? '00.000.000/0000-00' : '000.000.000-009';
},
cpfCnpjpOptions = {
    onKeyPress: function(val, e, field, options) {
        field.mask(CpfCnpjMaskBehavior.apply({}, arguments), options);
    }
};

  //Mascara de Documentos
  $('#documento_cliente').mask(CpfCnpjMaskBehavior, cpfCnpjpOptions);
```


[jsfiddle](https://jsfiddle.net/gjmucciolo/1d96jh4m/7/)
