### ISSUE TITLE
Add a flag to reveal Mask as soon as the user types in?

### ISSUE THREAD

**Issue by rupeshdabbir** [igorescobar/jQuery-Mask-Plugin#612]
Hi @igorescobar 

I tried looking into the API but couldn't find any.

Let's imagine we are doing an expiry field: (MM/YY)

After entering `07` the mask does not get applied. (i.e 07/)

Is there anyway to automatically add mask when the user types in two numbers? (Instead of waiting for the user to type the third number)

**Comment by igorescobar** [comment]
Duplicated #604
