### ISSUE TITLE
For All. Best settings for mask Money/Decimals. New feature?

### ISSUE THREAD

**Issue by pyetrosafe** [igorescobar/jQuery-Mask-Plugin#619]
#### Português
Oi galera.

Eu estava querendo adicionar uma funcionalidade para o plugin, para mascarar valores decimais e monetários, mantendo os zeros à esquerda e apagar completamente o valor do campo caso o valor fosse "0,00" (ou "0.00") ao pressionar backspace.

Antes eu havia aberto uma Issue, para isso: https://github.com/igorescobar/jQuery-Mask-Plugin/issues/123 e usava abordagem do @straube mas ainda não estava totalmente como eu queria...

Procurando por novas postagens desse problema achei essa Issue https://github.com/igorescobar/jQuery-Mask-Plugin/issues/527 onde o @stefan-beyer postou seu código no jsfiddle:  http://jsfiddle.net/c6qj0e3u/11/
Já foi muito melhor que o anterior que eu usava, mas não deixava apagar por completo o campo. Então editei o código e cheguei nisso que vim mostrar pra vocês aqui: http://jsfiddle.net/c6qj0e3u/15/

______________________________________________________________________________
#### English
Hi guys.

I was wanting to add a functionality to the plugin, to mask decimal and monetary values, keeping zeros to the left and completely erasing the field value if the value was "0.00" (or "0.00") when pressing backspace.

Before I had opened a Issue for this: https://github.com/igorescobar/jQuery-Mask-Plugin/issues/123 and I used the @straube approach but it still was not quite as I wanted ...

Looking for new posts from this problem I found this Issue https://github.com/igorescobar/jQuery-Mask-Plugin/issues/527 where @stefan-beyer posted his code in jsfiddle: http://jsfiddle.net/c6qj0e3u/11/
It was already much better than the previous one I used, but it did not let the field completely clear. So I edited the code and I came to this that I came to show you here: http://jsfiddle.net/c6qj0e3u/15/
______________________________________________________________________________
#### Full code here:
```javascript
// Font base: http://jsfiddle.net/c6qj0e3u/11/
// Edited by: Pyetro Costa
// New feature: Check if field value is "0,00" and Backspace was pressed, so clean Val
// Accept decimals "." or ","
var MoneyOpts = {
  reverse:true,
  maxlength: false,
  placeholder: '0,00',
  onKeyPress: function(v, ev, curField, opts) {
    var mask = curField.data('mask').mask;
        decimalSep = (/0(.)00/gi).exec(mask)[1] || ',';
    if (curField.data('mask-isZero') && curField.data('mask-keycode') == 8)
      $(curField).val('');
    else if (v) {
      // remove previously added stuff at start of string
      v = v.replace(new RegExp('^0*\\'+decimalSep+'?0*'), ''); //v = v.replace(/^0*,?0*/, '');
      v = v.length == 0 ? '0'+decimalSep+'00' : (v.length == 1 ? '0'+decimalSep+'0'+v : (v.length == 2 ? '0'+decimalSep+v : v));
      $(curField).val(v).data('mask-isZero', (v=='0'+decimalSep+'00'));
    }
  }
};

$('#money-field').mask("#.##0,00", MoneyOpts);

```
Talvez @igorescobar possa inserir esse código no plugin... É um código bem pequeno e bem útil que torna o plugin um MoneyPlugin... bastando definirmos algo como $('.money').mask('#.##0,00', {money: true});

Fica a dica... Abraço!

**Comment by tiesont** [comment]
If you are wanting to contribute code, that's best handled with a pull-request. Is that something you are familiar with?

**Comment by pyetrosafe** [comment]
I'm not familiar with either the Pull Request or the source code of the plugin. I just wanted to share with the developers who use this plugin and had the same difficulty with this monetary part, and this onKeyPress method I shared helps to solve those issues. If someone who is familiar with such things can use this code I share and move on with the Pull Request.

**Comment by igorescobar** [comment]
Hey @pyetrosafe!

That is a long thread and I really really really believe that this should be out of the official source code. As I describe on many of those threads our engine/algorithm is generic. It doesn't know what is money or what is an IP or date etc. It just follows generic expressions. For now, the best I can do here is to make sure that the people interested in this kind of use get this message and implement it on their own risk.

Thanks for sharing this with us.

**Comment by pyetrosafe** [comment]
E aí Igor...
Eu acabei achando um problema quando eu adiciono um código para "$.jMaskGlobals = {};"
Eu quis adicionar alguns translations para funcionar em todas as páginas em um arquivo global com esse código:

```
              <script type="text/javascript" src="localhost/jQuery-Mask-Plugin/jquery.mask.min.js"></script>
              <script>
              $.jMaskGlobals = {
                translation: {
                  '0': {pattern: /\d/},
                  '9': {pattern: /\d/, optional: true},
                  '#': {pattern: /\d/, recursive: true},
                  'A': {pattern: /[a-zA-Z0-9À-ÿ _-]/}, //Char(192) À até Char(255) ÿ // /[a-zA-Z0-9]/
                  'S': {pattern: /[a-zA-Z]À-ÿ/},
                  'C': {pattern: /[\x20-\x7E\x80-\xFF]/} // Toda tabela Asc II
                }
              };
              </script>
```
O que aconteceu é que como adicionei esse código Abaixo da linha <script src="jquery.mask.min.js"></script> por algum motivo fez com que o código pelo qual eu criei essa Issue, deixasse de funcionar perfeitamente. Porém colocando o código do $.jMaskGlobals acima da linha <script src="jquery.mask.min.js"></script>, então funciona o código dessa Issue perfeitamente... Porém as novas translations deixam de funcionar...

Alguma idéia de como resolver?

**Comment by igorescobar** [comment]
@pyetrosafe É um problema mesmo de lógica e não há muito o que fazer. A o plugin rodou pela primeira vez com as definições padrão e somente depois você re-definiu elas ou seja, as definições só passaram a valer na segunda linha. Lembre-se que toda instrução `<script></script>` é sincrona. Veja esta linha: https://github.com/igorescobar/jQuery-Mask-Plugin/blob/master/src/jquery.mask.js#L585

Eu já estou contando com a possibilidade desta globa estar definida antes do carregamento do código do plugin :-)

**Comment by pyetrosafe** [comment]
@igorescobar Minha questão anterior sobre as definições globais, foi um tanto estúpida e fiz com pressa, por causa das tarefas no meu trabalho. Ficou sem sentido. Agora com mais calma, fazendo alguns testes eu descobri o que causa o erro...

Usando o objeto MoneyOpts que citei nessa Issue no primeiro comentário. Eu testei 3 casos em que um aparece o erro e nos outros dois funcionam, sendo o último o que entendi a causa do erro.

1º Caso (Não funciona):
```
  $.jMaskGlobals = {
    translation: {
      '0': {pattern: /\d/}, '9': {pattern: /\d/, optional: true}, '#': {pattern: /\d/, recursive: true},
      'A': {pattern: /[a-zA-Z0-9À-ÿ _-]/}, //Char(192) À até Char(255) ÿ // /[a-zA-Z0-9]/
      'S': {pattern: /[a-zA-Z]À-ÿ/},
      'C': {pattern: /[\x20-\x7E\x80-\xFF]/} // Toda tabela Asc II
    }
  };
  $('.money').mask("#.##0,00", MoneyOpts);
```
Resultado: A funcionalidade esperada das opções MoneyOpts não executam como deviam, parece que o evento onKeyPress definido, na verdade funciona como um evento onKeyUp;

2º Caso (Funciona mas deve setar mascaras antes das definições globais, o que não é viável):
```
  $('.money').mask("#.##0,00", MoneyOpts);
  $.jMaskGlobals = {
    translation: {
      '0': {pattern: /\d/}, '9': {pattern: /\d/, optional: true}, '#': {pattern: /\d/, recursive: true},
      'A': {pattern: /[a-zA-Z0-9À-ÿ _-]/}, //Char(192) À até Char(255) ÿ // /[a-zA-Z0-9]/
      'S': {pattern: /[a-zA-Z]À-ÿ/},
      'C': {pattern: /[\x20-\x7E\x80-\xFF]/} // Toda tabela Asc II
    }
  };
```
Resultado: Funciona como esperado, mas é ruim para o código definir mascaras antes da definição global, sendo que em algum caso poderia se precisar usar de algumas dessas definições globais e então ter de setar elas individualmente.

3º Caso (Setando parâmetro "useInput: true" a opção MoneyOpts definida, funciona e do jeito que deve ser):
```
  $.jMaskGlobals = {
    useInput: true,
    translation: {
      '0': {pattern: /\d/}, '9': {pattern: /\d/, optional: true}, '#': {pattern: /\d/, recursive: true},
      'A': {pattern: /[a-zA-Z0-9À-ÿ _-]/}, //Char(192) À até Char(255) ÿ // /[a-zA-Z0-9]/
      'S': {pattern: /[a-zA-Z]À-ÿ/},
      'C': {pattern: /[\x20-\x7E\x80-\xFF]/} // Toda tabela Asc II
    }
  };
  // Pode setar a mascara MoneyOpts em qualquer lugar do código agora que funciona...
  $('.money').mask("#.##0,00", MoneyOpts);
```
Resultado: O parametro useInput das definições globais, se não setado ou setado como false, causa o erro de uma opção definida com método onKeyPress funcionar como se fosse chamado por onKeyUp... Ao definir useInput como True, o código funcionou como esperado. Definimos as opções globais no topo do código, e definições individuais com onKeyPress funcionam corretamente.

**Comment by pyetrosafe** [comment]
@igorescobar Então... Eu li o código do plugin... Fiz algumas alterações que creio serem minimalistas e de grande utilidade ao plugin. Consegui evitar o problema das definições Globais com um ajuste no código fonte... As alterações estão no Pull Request que fiz: https://github.com/igorescobar/jQuery-Mask-Plugin/pull/624

Evita eu fazer todo esse código no meu fonte:
```
    // Retirado do código do Mask Plugin, para verificar se o Chrome tem a funcionalidade do input Event
    var eventSupported = function(eventName) {
      var el = document.createElement('div'), isSupported;
      eventName = 'on' + eventName;
      isSupported = (eventName in el);
      if ( !isSupported ) {
          el.setAttribute(eventName, 'return;');
          isSupported = typeof el[eventName] === 'function';
      }
      el = null;
      return isSupported;
    };

    // Definições globais para o jQuery Mask Plugin
    $.jMaskGlobals = {
      // old versions of chrome dont work great with input event
      useInput: !/Chrome\/[2-4][0-9]|SamsungBrowser/.test(window.navigator.userAgent) && eventSupported('input'),
      byPassKeys: [9, 16, 17, 18, 36, 37, 38, 39, 40, 91],
      translation: {
        '0': {pattern: /\d/},
        '9': {pattern: /\d/, optional: true},
        '#': {pattern: /\d/, recursive: true},
        'A': {pattern: /[a-zA-Z0-9À-ÿ _-]/}, //Char(192) À até Char(255) ÿ // /[a-zA-Z0-9]/
        'S': {pattern: /[a-zA-Z]À-ÿ/},
        'C': {pattern: /[\x20-\x7E\x80-\xFF]/} // Toda tabela Asc II
      }
    };
```

Para fazer somente isso:
```
    // Definições globais para o jQuery Mask Plugin
    $.jMaskGlobals = {
      addTranslation: {
        'A': {pattern: /[a-zA-Z0-9À-ÿ _-]/}, //Char(192) À até Char(255) ÿ // /[a-zA-Z0-9]/
        'S': {pattern: /[a-zA-Z]À-ÿ/},
        'C': {pattern: /[\x20-\x7E\x80-\xFF]/} // Toda tabela Asc II
      }
    };
```

**Comment by benjover** [comment]
@pyetrosafe , eu dei o pull no seu código do #624, entretanto encontrei um pouco de dificuldade em entender onde eu deveria definir o objeto `addTranslation`. Tentei definir antes e depois de chamar a lib, mas em nenhum dos casos obtive sucesso.

Acho importante mencionar que estou usando o modelo `data-mask=""` para facilitar. Da mesma forma que você, tenho que aplicar isso num template. 

Estou tentando seu método para solucionar o #361, que [em tese](https://igorescobar.github.io/jQuery-Mask-Plugin/docs.html#translation) deveria funcionar com o `data-mask="S#"`, mas na prática não funciona. 

O código abaixo funciona bem:

```
<input class="name"/>

<script src="jquery.js"></script>
<script src="jquery.mask.js"></script>
<script>
$('.name').mask('Z',{translation: {'Z': {pattern: /[a-zA-Z ]/, recursive: true}}});
<script>
```

Entretanto, não posso usá-lo porque tenho que colocar dentro de um template. Somente posso usar o `data-mask`. Eu tentei o seguinte:

```
<input data-mask="Z"/>
<script>
$.jMaskGlobals = {
  addTranslation: { 'Z': {pattern: /[a-zA-Z ]/, rescursive: true} }
};
</script>
<script src="jquery.mask.js"></script>
```

Também tentei chamar o `addTranslation` depois do `<script src="jquery.mask.js"></script>` sem sucesso. Também tentei definir o `$.jMaskGlobals.translation` manualmente, também sem sucesso. 

Alguma chance ou fazer o `data-mask="S#"` funcionar, ou do `addTranslation` pegar nos `data-mask`, ou dele interpretar uma adição manual do  `$.jMaskGlobals.translation` depois que ele carregar a lib?

**Comment by pyetrosafe** [comment]
@benjover Bom... fiz uns testes aqui, e acho que resolvi nossos problemas... Primeiramente para o addTranslation funcionar corretamente sem alterar todo objeto global, o uso correto dele deve ser diferente, já corrigi no meu comentário no #624, seria assim:
```
$.jMaskGlobals.addTranslation = { 'Z': {pattern: /[a-zA-Z ]/, rescursive: true} };
```
Outra coisa, tive umas alterações em relação ao meu código, que são necessárias para que as novas translations do addTranslations permaneçam em novas instâncias do plugin, elementos a seguir que fazem sua chamada. Preciso ver como faço para alterar meu PR ou mandar um novo corrigindo ele, ainda não sei (se tiver mais tempo que eu fique a vontade)... Mas a correção seria adicionar algumas linhas entre as linhas 429 e 430:

```
426|            // Caso nenhuma definição foi feita nas Definições Globais pelo usuário, pega o padrão do plugin!
427|            jMask.translation      = Object.keys(jMask.translation).length == 0 ? globals.translation : jMask.translation;
428|
429|            // addTranslation: Propriedade para Adicionar translation sem remover as definidas por padrão!
430|+           // Necessário aplicar o addTranslation na propriedade translation do obj jMask e do $.jMaskGlobals, pois se não perde a referência nas próximas instâncias
431|            jMask.translation      = $.extend({}, jMask.translation, $.jMaskGlobals.addTranslation);
432|+           $.jMaskGlobals.translation = $.extend({}, jMask.translation, $.jMaskGlobals.addTranslation);
433|+
434|+           // Uma vez copiado para a propriedade translation não precisa mais dessa propriedade.
435|+           delete $.jMaskGlobals.addTranslation;
436|
437|            // Caso o usuário não tenha definido a propriedade, obtém o valor padrão do Plugin!
438|            $.jMaskGlobals.useInput = ('useInput' in $.jMaskGlobals) ? $.jMaskGlobals.useInput : globals.useInput ;

```

Agora para o seu código funcionar, eu percebi que quando é usado o data-mask, a chamada do plugin é imediata, antes de qualquer verificação de Globals... Para isso é necessário definir a Globals antes da chamada da lib, depois da chamada do jQuery. Como a Globals ainda não existe porque a lib não foi chamada também precisa instanciar ela primeiro.

```
  <input data-mask="Z"/>

  <script src="jquery.js"></script>
  <script type="text/javascript">
    $.jMaskGlobals = $.jMaskGlobals || {};
    $.jMaskGlobals.addTranslation = {
      'Z': {pattern: /[a-zA-Z ]/, rescursive: true} }
    };
  </script>
  <script src="jquery.mask.js"></script>
```

Pronto seu código agora vai funcionar... E se definir outras mascaras, por javascript depois, vão funcionar também:

```
  <input data-mask="Z"/>
  <input class="outroInput"/>

  <script src="jquery.js"></script>
  <script type="text/javascript">
    $.jMaskGlobals = $.jMaskGlobals || {};
    $.jMaskGlobals.addTranslation = {
      'Z': {pattern: /[a-zA-Z ]/, rescursive: true} }
    };
  </script>
  <script src="jquery.mask.js"></script>

  <script type="text/javascript">
    $('.outroInput').mask('Z');
  </script>
```
