### ISSUE TITLE
Using masked input on Bootstrap 4 Modal

### ISSUE THREAD

**Issue by felzend** [igorescobar/jQuery-Mask-Plugin#620]
**Chrome 61
Win10 x64.**

There's a issue on using your plugin on Bootstrap 4 modals. When I apply the mask for the input field and type on this one, it keeps "flickering" (alterning between masked and common text), so it doesn't applies and I am unable to get the field correctly formated for my date. However, bootstrap-datepicker works normally.
Already questioned on BS4 issues and they told to talk to plugin's author.

Below the basic example I tried to do. The mask is applied when modal opens (also tried without opening callback and same result.)

![image](https://user-images.githubusercontent.com/10427954/31856421-232f2b46-b697-11e7-8036-b31a960cb2e5.png)

**Comment by igorescobar** [comment]
Can you provide a functional jsfiddle as stated on the temples you got when
opened this issue?

Thanks a lot!

**Comment by tiesont** [comment]
Also helps to note the browsers in which you are seeing this issue; Webkit and Blink browsers (Safari and Chrome, basically) and Edge have a native date input, so trying to mask that (especially with the format you're using) would cause some issues.

**Comment by igorescobar** [comment]
@felzend I will open this again once you provide a jsfiddle. Thanks!
