### ISSUE TITLE
How to Integrate jQuery Mask Plugin with Vue.js? 

### ISSUE THREAD

**Issue by Aleksandr-ru** [igorescobar/jQuery-Mask-Plugin#621]
subj :)
In case of ```<input v-model="...">``` masks are not working. Please help me to solve it.

**Comment by Aleksandr-ru** [comment]
But it still not working in markup like
```
<div v-for="...">
<input v-model.lazy="...">
</div>
```
The only idea for now is use `setTimeout` to wait until DOM changed.

**Comment by igordelorenzi** [comment]
I'm playing with Vue.js and noticed a different issue (using the workaround you suggested, v-model.lazy): there is no char limit on the text field as you can see on the gif below.
![mask-input-bug](https://user-images.githubusercontent.com/2574541/32393359-49a768f0-c0c0-11e7-8377-9feaf0e3ca82.gif)

**Comment by Aleksandr-ru** [comment]
Unable to reproduce absence of char limit in Firefox and Opera on Linux.
I'm playing with date mask:
```
$('input.mask-date').mask('30.10.0000', {
	translation: {
		'1': {pattern: /[0-1]/},
		'3': {pattern: /[0-3]/}
	},
	selectOnFocus: true
});
```

**Comment by igorescobar** [comment]
More on: https://github.com/igorescobar/jQuery-Mask-Plugin#problems-or-questions
