### ISSUE TITLE
mask with numeric keypad on the cell phone

### ISSUE THREAD

**Issue by muriloelias** [igorescobar/jQuery-Mask-Plugin#623]
Hello friends,
First of all, congratulations for the work. The library is helping me a lot.
I have a question, how can I use the jQuery-Mask-Plugin to open the phone's numeric keypad?
I want to for example use the following mask: $ ('. Cpf').Mask('000.000.000-00', {reverse: true});
I tried to put the field with type number, but the add buttons appear and it was not cool.
I tried to put the pattern property, but when we need other characters automatically the browser opens the alphanumeric keyboard.
The solution I found so far was to use the "tel" type, but I have already been informed that I will have accessibility problems.
I'm testing with chrome on iphone 5s.
Any suggestion?
Hug.

**Comment by igorescobar** [comment]
@muriloelias no jquery can have control over the device's keyboard. Sorry. If you search on our issues we already have a few conversations around this issue. Thanks.
