### ISSUE TITLE
Numbers only mask allows unlimited letters for field type "number" in FF and IE

### ISSUE THREAD

**Issue by pauldeg** [igorescobar/jQuery-Mask-Plugin#625]
### Have you take a look into our docs?
https://igorescobar.github.io/jQuery-Mask-Plugin/

### Make sure your read this before opening a new issue:
https://github.com/igorescobar/jQuery-Mask-Plugin#problems-or-questions

#### Device
Windows 7 laptop

#### Browser (and version)?
FF 55 64bit or IE 11

#### Functional `jsfiddle` exemplifying your problem: 
You can use this one as exemple: http://jsfiddle.net/igorescobar/6pco4om7/

#### Describe de problem depth:
When using mask '0000' in FF for a field with type "number" letters allowed typed into the field.
Example input field: <input type='number' name='accnum' id='accnum'>

Is this plugin helping you out? Buy me a beer and cheers! :beer:

:bowtie: https://www.paypal.me/igorcescobar

**Comment by igorescobar** [comment]
Please, take a look into this (was on our FAQ):
https://github.com/igorescobar/jQuery-Mask-Plugin/issues/450#issuecomment-253225719

**Comment by pauldeg** [comment]
Well, your plugin works in Chrome perfectly even for input with type numeric, and partially works in FF and IE. 
The only problem with IE and FF that letters can be typed, when mask is numeric - yet length limit works fine for digits.
