### ISSUE TITLE
unmask() does not remove the placeholder

### ISSUE THREAD

**Issue by bellwood** [igorescobar/jQuery-Mask-Plugin#626]
#### Device
OSX / MBP

#### Browser (and version)?
Chrome Version 62.0.3202.94 (Official Build) (64-bit)

#### Functional `jsfiddle` exemplifying your problem: 
http://jsfiddle.net/6pco4om7/924/

#### Describe de problem depth:
When applying unmask, the placeholder is not removed.

**Comment by PauloHDSousa** [comment]
@igorescobar  Can I solve this? also, take a look at the pull request that I did.

**Comment by igorescobar** [comment]
I've just released a new version fixing two `unmask` issues with the placeholder and the maxlength field.
