### ISSUE TITLE
Solution for using jQuery Data Mask with Knockout

### ISSUE THREAD

**Issue by Soulriser** [igorescobar/jQuery-Mask-Plugin#627]
Hi there,

I've been using jQuery Data Mask with Knockout for a while. I created a custom binding handler that integrates data masking with observables and observed elements, so you can mask any input value or element text from your view model. The masked element and its bound observable maintain the masked value and you can change the element's masking on the fly. It also includes two preset values, numberMask and moneyMask, to simplify those common scenarios.

Fiddle here:
https://jsfiddle.net/soulriser/s9uaqynp/

The fiddle only allows for strings as masks, but you can also pass mask objects, or anything that works with $.mask().

Please let me know what you think, if this is helpful, or if you'd recommend any changes. Thanks for a great plugin!

**Comment by igorescobar** [comment]
Thanks @Soulriser I will close this as this isn't an issue but it still crawlable by search engines. thx!
