### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by motoroller1983** [igorescobar/jQuery-Mask-Plugin#631]
### Have you take a look into our docs?
https://igorescobar.github.io/jQuery-Mask-Plugin/

### Make sure your read this before opening a new issue:
https://github.com/igorescobar/jQuery-Mask-Plugin#problems-or-questions

#### Device
[Desktop]

#### Browser (and version)?
[Mozilla latest]

#### Functional `jsfiddle` exemplifying your problem: 
You can use this one as exemple: http://jsfiddle.net/igorescobar/6pco4om7/

#### Describe de problem depth:
[
Can u help me with your plugin

For example I want insert before number code of the country (Portugal)

$('#phone').mask('+351 (000) 000-00-00');

Its working well if my number stats any digit except 3 5 1, but if my first digit of number consist of 3 or 5 or 1, plugin jump me not to my number. Jump to the code of the country, how can I avoid it?

I need if I input any number it should by after «(«
If I input 9 I  have +351 (9 – good
If I input 5 I have +35 – bad (

]

Is this plugin helping you out? Buy me a beer and cheers! :beer:

:bowtie: https://www.paypal.me/igorcescobar

**Comment by pyetrosafe** [comment]
@motoroller1983 

Hi... I think your problem is not a Bug but just need some adjusts.
Try the code exemplify on link below:

http://jsfiddle.net/6pco4om7/931/

**Comment by igorescobar** [comment]
https://github.com/igorescobar/jQuery-Mask-Plugin/issues/166
