### ISSUE TITLE
Cursor jumps left when masking div with css text-align:right

### ISSUE THREAD

**Issue by kevlin79** [igorescobar/jQuery-Mask-Plugin#635]
### Have you take a look into our docs?
https://igorescobar.github.io/jQuery-Mask-Plugin/

### Make sure your read this before opening a new issue:
https://github.com/igorescobar/jQuery-Mask-Plugin#problems-or-questions

#### Device
Apple MacBook Pro

#### Browser (and version)?
Safari 11.0

#### Functional `jsfiddle` exemplifying your problem: 
https://jsfiddle.net/c5aot5te/12/

#### Describe de problem depth:
When masking a div with css text-align:right the cursor jumps to the left after a while. An input works just fine.

Is this plugin helping you out? Buy me a beer and cheers! :beer:

:bowtie: https://www.paypal.me/igorcescobar

**Comment by igorescobar** [comment]
@kevlin79 we don't support that. sorry.
