### ISSUE TITLE
Caret is jumping a letter when translation and recursive options are used together

### ISSUE THREAD

**Issue by onuradsay** [igorescobar/jQuery-Mask-Plugin#636]
#### Functional `jsfiddle` exemplifying your problem:
http://jsfiddle.net/njeto2zn/2/

#### Describe de problem depth:
Using translation and recursive opitons together causes caret to jump wrong position. Please follow instructions on jsfiddle example to produce this bug.

**Comment by igorescobar** [comment]
@onuradsay I couldn't reproduce. Can you be more specific?

**Comment by onuradsay** [comment]
@igorescobar  Sorry, the jsfiddle link was wrong. Can you try this one http://jsfiddle.net/njeto2zn/2

**Comment by igorescobar** [comment]
@onuradsay are you trying to achieve a specific use case here? What kind of mask are you trying to do?

**Comment by onuradsay** [comment]
@igorescobar  I'm trying to allow only alpha-numeric characters. By the way, I just created a pull request fixing this issue.

**Comment by igorescobar** [comment]
@onuradsay thanks for your help! I need to run a few tests before merging it. messing with the caret engine is aaaalways tricky 📟

**Comment by onuradsay** [comment]
@igorescobar Yes, you are right. If you think that the pull-request may cause more issues than it fixes, here is a working example for this specific case: http://jsfiddle.net/njeto2zn/4/

**Comment by igorescobar** [comment]
@onuradsay yeah that explains a lot 😆

**Comment by igorescobar** [comment]
thanks @onuradsay I will take a look in a few

**Comment by igorescobar** [comment]
@onuradsay it's on master, can you give it a try and let me know so I can release a new version?

**Comment by onuradsay** [comment]
@igorescobar It seems that everything is fine.

**Comment by onuradsay** [comment]
@igorescobar Thanks for the quick release, that was sooo fast ⚡️
