### ISSUE TITLE
Docs should have information about default translations

### ISSUE THREAD

**Issue by adityasharma7** [igorescobar/jQuery-Mask-Plugin#638]
I moved from http://digitalbush.com/projects/masked-input-plugin/ to jQuery-Mask-Plugin. All I wanted was default translations information.
There is a line in translation section 
https://igorescobar.github.io/jQuery-Mask-Plugin/docs.html#translation

> By default, jQuery Mask Plugin only reconizes the logical digit A (Numbers and Letters) and S (A-Za-z) but you can extend or modify this behaviour by telling to jQuery Mask Plugin how to interpret those logical digits.

but there is no info about numbers or if there are any other translations available by default.
Translation section should have information about the default translations in the beginning that come with the plugins and it would even be better if the section is at the top.

**Comment by lfelizari** [comment]
This information is in the end, in global options.
https://igorescobar.github.io/jQuery-Mask-Plugin/docs.html#global-options

**Comment by igorescobar** [comment]
Thanks @lfelizari !
