### ISSUE TITLE
Mask as a function is called infinitely

### ISSUE THREAD

**Issue by edilsonmendes** [igorescobar/jQuery-Mask-Plugin#639]
I using mask as function (as show documentation) to format CPF/CNPJ depend on user input lenght. Logging the mask function, we can see (in browser console tab) that the function is called infinitely. I've tested with the code below:

**JS**

```
<script>
			var CPFCNPJMaskBehavior = function (val) {
				console.log(val);
			        return val.replace(/\D/g, '').length > 11 ? '00.000.000/0000-00' : '000.000.000-000';
			},
			cpfCnpjOptions = {
			  onKeyPress: function(val, e, field, options) {
				  field.mask(CPFCNPJMaskBehavior.apply({}, arguments), options);
				}
			};

			$('#cpfcnpj-field').mask(CPFCNPJMaskBehavior, cpfCnpjOptions);
</script>
```

**HTML**

```
<form role="form">
				
				<div class="form-group">
					<label for="cpfcnpj-field">CPF/CNPJ</label>
					<input type="text" class="form-control" id="cpfcnpj-field">
				</div>
			
</form>
```
*In jsfiddle the problem does not seem to occur, but extracting the code into an HTML file we can realize the error.

**Comment by edilsonmendes** [comment]
![masasfunctionproblem](https://user-images.githubusercontent.com/27703772/34308692-3e2f9482-e72d-11e7-84b3-0c51b1a2af1b.png)

**Comment by igorescobar** [comment]
@edilsonmendes I will re-open the issue once you provide a functional jsfiddle. thanks!
