### ISSUE TITLE
Typo in the Docs

### ISSUE THREAD

**Issue by fbmarinho** [igorescobar/jQuery-Mask-Plugin#641]
### Have you take a look into our docs?
Yep

### Make sure your read this before opening a new issue:
Ok

#### Device
Desktop

#### Browser (and version)?
Chrome last version

#### Describe de problem depth:
In the docs, in the Public methods section the comment for the Seek and Destroy region says:
"@selector elements to be masked" where it should be "@selector elements to be UNMASKED".

**Comment by igorescobar** [comment]
I will look into it, thanks @fbmarinho
