### ISSUE TITLE
$('input',container).mask('00/00') or $(container).find('input').mask('00/00') applies to all input Elements

### ISSUE THREAD

**Issue by SiamandMaroufi** [igorescobar/jQuery-Mask-Plugin#643]
I used jquery mask plugin with knockout.js and I find out that the jquery selector `$(selector).find(something).mask()` does not works fine and the mask will applied to all input element in the page,
and there is a workground for this issue that  its use `$(element.querySelector('input')).mask('00/00');` instead of the above code.

**Comment by igorescobar** [comment]
Thanks @SiamandMaroufi
