### ISSUE TITLE
Uncaught TypeError: Cannot set property 'maskWatchers' of undefined

### ISSUE THREAD

**Issue by merteroglu01** [igorescobar/jQuery-Mask-Plugin#645]
jquery.mask.js:467 Uncaught TypeError: Cannot set property 'maskWatchers' of undefined
    at jquery.mask.js:467
    at jquery.mask.js:47
    at jquery.mask.js:50

**Comment by knight1219** [comment]
What was the solution for this?
Did you find one?

**Comment by merteroglu01** [comment]
i don't remember

**Comment by CTrevar** [comment]
Make sure you include jQuery before jQuery.mask

**Comment by fajusto** [comment]
> Make sure you include jQuery before jQuery.mask

It is this way but still not working.

In my case are these lines:

Uncaught TypeError: Cannot set property 'maskWatchers' of undefined
    at jquery.mask.min.js:15
    at jquery.mask.min.js:6
    at jquery.mask.min.js:6
