### ISSUE TITLE
Mask Phone SP + clearIfNotMatch

### ISSUE THREAD

**Issue by ftbraian** [igorescobar/jQuery-Mask-Plugin#646]
Igor como poderia colocar o 'clearIfNotMatch = true' no exemplo da mask para telefone com novo digito:

var maskBehavior = function (val) {
  return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
},
options = {onKeyPress: function(val, e, field, options) {
        field.mask(maskBehavior.apply({}, arguments), options);
    }
};

$('.phone').mask(maskBehavior, options);

ou teria como colocar o clearIfNotMatch true para todos as mask ?

abs

**Comment by igorescobar** [comment]
Olá @ftbraian !

Infelizmente o clearIfNotMatch não é uma opção global e sim de cada input.
