### ISSUE TITLE
I's wrong while I use the wrong num

### ISSUE THREAD

**Issue by webfeat** [igorescobar/jQuery-Mask-Plugin#649]
### Have you take a look into our docs?
https://igorescobar.github.io/jQuery-Mask-Plugin/
Yes

### Make sure your read this before opening a new issue:
https://github.com/igorescobar/jQuery-Mask-Plugin#problems-or-questions
Yes
#### Device
win10

#### Browser (and version)?
chrome

#### Functional `jsfiddle` exemplifying your problem: 
You can use this one as exemple: http://jsfiddle.net/igorescobar/6pco4om7/

#### Describe de problem depth:
 I set the parttern (/[0-2]/), then I set 9 with it.The content value was changed as  '...'.
THe is my example 🔢 https://jsfiddle.net/topfun/gydmm492/

Is this plugin helping you out? Buy me a beer and cheers! :beer:

:bowtie: https://www.paypal.me/igorcescobar

**Comment by igorescobar** [comment]
@webfeat You can't have a  mask on a field where ALL digits are optional. You need to do something closer to what it is on the documentation:

```javascript
$('.ip_address').mask('0ZZ.0ZZ.0ZZ.0ZZ', {
    translation: {
      'Z': {
        pattern: /[0-9]/, optional: true
      }
    }
  });
// or
$('.ip_address').mask('099.099.099.099');
```

**Comment by igorescobar** [comment]
@webfeat can you reproduce it on any other device? I couldn't reproduce on my Google Chrome (Mac).
