### ISSUE TITLE
Mascara e Banco de dados

### ISSUE THREAD

**Issue by Aandrels** [igorescobar/jQuery-Mask-Plugin#651]
Bom dia,
sou estudando de Analise e desenvolvimento de sistemas, e estou fazendo meu trabalho de conclusão de curso e estou com uma duvida, já tentei procurar na internet mas não achei nada que solucionou meu problema. 

Estou desenvolvendo em asp.net core, com o entity framework core, e coloquei mascara no campo CNPJ desse jeito, na view:

<div class="form-group">
                <label asp-for="Cnpj" class="control-label"></label>
                <input asp-for="Cnpj" placeholder="Somente Numero" data-cleanVal() data-mask="00.000.000/0000-00" data-mask-reverser="true" class="cnpj" />
                <span asp-validation-for="Cnpj" class="text-danger"></span>
</div>

Ela funciona normal, mas quando dou um create na pagina ela estoura, por causa da mascara, como posso fazer para mandar pro banco de dados sem a mascara? Tem algum jeito sem ter que criar o Insert no BD na mão?
Muito obrigado

**Comment by igorescobar** [comment]
Duplicated #463
