### ISSUE TITLE
Erro no Angular 2

### ISSUE THREAD

**Issue by edersonsergiocoelho** [igorescobar/jQuery-Mask-Plugin#653]
Poderia me ajudar estou tentando usar seu plugin no Angular 2 e não estou conseguindo está dando esse erro abaixo:

VM9194 jquery.mask.js:410 Uncaught TypeError: Cannot set property 'maskWatchers' of undefined
    at VM9194 jquery.mask.js:410
    at VM9194 jquery.mask.js:49
    at VM9194 jquery.mask.js:52

Minha página aonde estou tentando usar:

`<app-utils-nav></app-utils-nav>

<br>

<h1>Cadastro Da Entrega</h1>

<br>

<div class="container">
  <div class="row">
    <div class="col">
      <form novalidate [formGroup]="entregaForm" (ngSubmit)="onSubmit()">
        <div class="form-group">
          <label class="font-weight-bold">Código Da Entrega</label>
          <input type="number" class="form-control form-control-lg" formControlName="codigoEntrega" disabled="false">
        </div>

        <div class="form-group">
          <label class="font-weight-bold">Nome Da Entrega</label>
          <input type="text" class="form-control form-control-lg" formControlName="nomeEntrega">
        </div>

        <div class="form-group">
          <label class="font-weight-bold">Valor Da Entrega</label>
          <input type="text" class="form-control form-control-lg money" id="valorEntrega" formControlName="valorEntrega">
        </div>

        <br>

        <button type="submit" class="btn btn-success btn-lg"  [disabled]="!entregaForm.valid" >Registrar</button>
        <button type="button" class="btn btn-warning btn-lg" (click)="redirectEntregasPage()">Cancelar</button>
        <button type="button" class="btn btn-info btn-lg" routerLink="/entregas" routerLinkActive="active">Listar Entregas</button>
      </form>
    </div>
  </div>
</div>

<app-utils-nav-usuario></app-utils-nav-usuario>

<router-outlet></router-outlet>`

**Comment by igorescobar** [comment]
https://github.com/igorescobar/jQuery-Mask-Plugin/blob/master/ISSUE_TEMPLATE.md

**Comment by CTrevar** [comment]
Make sure you include jQuery before jQuery.mask
