### ISSUE TITLE
.mask is not a function...

### ISSUE THREAD

**Issue by shoio** [igorescobar/jQuery-Mask-Plugin#655]
Existe alguma incompatibilidade do jQueryMask com a versão CDN do Bootstrap 3?
Chamo o jQueryMask depois do jQuery, abro o script e digito:
<script type="text/javascript">
	$(document).ready(function(){
		$('.nota').mask('00.00');
	});
</script>
Nada funcionando :(
Alguma dica?

**Comment by igorescobar** [comment]
https://github.com/igorescobar/jQuery-Mask-Plugin/blob/master/ISSUE_TEMPLATE.md
