### ISSUE TITLE
Um campo com dois valores

### ISSUE THREAD

**Issue by jevitor** [igorescobar/jQuery-Mask-Plugin#657]
Pessoal, alguem pode me ajudar?

Tenho um input no qual ele é CPF/CNPJ, como faço uma mascara contendo dois valores diferentes para um mesmo campo? E como ficaria o codigo contendo um campo adicional de telefone? Ou seja mascara no input cpf/cnpj e mascara no telefone, so consegui do cpf, nao consigo do telefone junto!

```
<input type="text" name="cpf" id="cpf">
<input type="text" name="tel" id="tel">
```

$(document).ready(function(){
  var SPMaskBehavior = function (val) {
    return val.replace(/\D/g, '').length === 11 ? '000.000.000.00' : '00.000.000/0000-01';
  },
  spOptions = {
    onKeyPress: function(val, e, field, options) {
        field.mask(SPMaskBehavior.apply({}, arguments), options);
      }
  };

  $('#cpf').mask(SPMaskBehavior, spOptions);
});

**Comment by jevitor** [comment]
```
Solucao:

var options =  {
  onKeyPress: function(cpf, e, field, options) { //Quando uma tecla for pressionada
    var masks = ['000.000.000.00', '00.000.000/0000-01']; //Mascaras
    var mask = (cpf.length > 13) ? masks[1] : masks[0]; //Se for de tamanho 11, usa a 2 mascara
    $('#cpf').mask(mask, options); //Sobrescreve a mascara
}};

$('#cpf').mask('000.000.000.00', options); //Aplica a mascara
```

**Comment by guitexa** [comment]
@jevitor, comigo funcionou assim:

```js
var options =  {
  onKeyPress: function(cpf, e, field, options) { //Quando uma tecla for pressionada
    var masks = ['000.000.000-00', '00.000.000/0000-00']; //Mascaras
    var mask = cpf.length > 14 ? masks[1] : masks[0]; //Se for de tamanho 18, usa a 2ª mascara
    $('#cpf').mask(mask, options); //Sobrescreve a mascara
}};

$('#cpf').mask('00.000.000/0000-00', options); //Aplica a mascara
```
