### ISSUE TITLE
Logo Proposal Request

### ISSUE THREAD

**Issue by LuigiBaute** [igorescobar/jQuery-Mask-Plugin#658]
Id like to collaborate _for free_ with this project by delivering on a logo that suits the project! let me know if interested! Cheers!

**Comment by igorescobar** [comment]
Hey there @LuigiBaute!

That would be awesome ^^

How can I help you with this quest?

**Comment by LuigiBaute** [comment]
Good morning, I would like to know more details about your project so that the logo is as accurate as possible @igorescobar

**Comment by igorescobar** [comment]
@LuigiBaute The project is quite simple in essence. It just do text "mask" in input/div/span/... HTML elements. I'm not sure what details you are interested in.

**Comment by LuigiBaute** [comment]
The name of the project is jQuery Mask Plugin or just Mask Plugin? @igorescobar
