### ISSUE TITLE
mask shows pattern label

### ISSUE THREAD

**Issue by andreika63** [igorescobar/jQuery-Mask-Plugin#659]
#### Device
PC, Windows7

#### Browser (and version)?
Chrome 65.0.3325.181

#### Functional `jsfiddle` exemplifying your problem: 
http://jsfiddle.net/6pco4om7/1786/

#### Describe de problem depth:
$('#val-field').mask('QW', {translation: {Q: {pattern: /[1-9]/}}, W: {pattern: /[0-9]/, optional: true}});
when I type a char, "W" pattern puts after masked value

**Comment by andreika63** [comment]
translation characters are reserved
        translation: {
            '0': {pattern: /\d/},
            '9': {pattern: /\d/, optional: true},
            '#': {pattern: /\d/, recursive: true},
            'A': {pattern: /[a-zA-Z0-9]/},
            'S': {pattern: /[a-zA-Z]/}
        }
I think this fact should be mentioned in documentation ))

**Comment by igorescobar** [comment]
It's mentioned :)

**Comment by igorescobar** [comment]
@andreika63 https://igorescobar.github.io/jQuery-Mask-Plugin/docs.html#global-options
