### ISSUE TITLE
CHANGELOG.md contains only an error message

### ISSUE THREAD

**Issue by Boldewyn** [igorescobar/jQuery-Mask-Plugin#660]
### Have you take a look into our docs?
n/a

### Make sure your read this before opening a new issue:
n/a

#### Device
n/a

#### Browser (and version)?
n/a

#### Functional `jsfiddle` exemplifying your problem: 
n/a

#### Describe de problem depth:
The content of the CHANGELOG.md file is only

> StepUp Exception: undefined method `parse' for Time:Class

The history confirms, that that error was introduced with the last change in 73199b3f5988c40383d916a88b1d8603a4f379cd.

**Comment by igorescobar** [comment]
@Boldewyn thanks! fixed!
