### ISSUE TITLE
what is 0, # , 9 ,Z mean?   

### ISSUE THREAD

**Issue by sg552** [igorescobar/jQuery-Mask-Plugin#671]
I check all the docs and demos but found nothing.  

please give me a clue.  thanks a lot~ 

I am guessing    0:  [0-9],  #:  any character. 

am I right? 

---------------------
YES ### Have you take a look into our docs?
YES ### Make sure your read this before opening a new issue:
https://github.com/igorescobar/jQuery-Mask-Plugin#problems-or-questions

**Comment by pyetrosafe** [comment]
Hi @sg552 
In the font code has this:

    translation: {
        '0': {pattern: /\d/},
        '9': {pattern: /\d/, optional: true},
        '#': {pattern: /\d/, recursive: true},
        'A': {pattern: /[a-zA-Z0-9]/},
        'S': {pattern: /[a-zA-Z]/}
    }

The "#" character is the same as [0-9] (digits), with "recursive" == true.
Most used to mask numbers with separators like: "#.##,0,00", this mask accept numbers like: 
           1,23
         12,34
       123,45
    1.234,56
  12.345,67
123.456.78
Where the thousands places can be repeated many times.

**Comment by sg552** [comment]
thanks a lot @pyetrosafe ,  very helpful and concise. 
I think this is the most important knowledge for the beginning user, and should be placed in the official document.

**Comment by igorescobar** [comment]
@sg552 @pyetrosafe It's not only on the code. it's also on our docs:
http://igorescobar.github.io/jQuery-Mask-Plugin/docs.html#global-options

**Comment by sg552** [comment]
OK 。

**Comment by Adden07** [comment]
how to auto fill with 92 in ?
$('#mobile').mask('920000000000'); tried this but still causing a problem.
