### ISSUE TITLE
Mascara '0,00' permite apenas uma digito

### ISSUE THREAD

**Issue by EvandersonSilva** [igorescobar/jQuery-Mask-Plugin#676]
Ola,

Eu tenho uma campo que deve permitir apenas 0,01 a 9,99. Porem quando eu insiro a mascara '0,00' o jquery permite eu digitar apenas um  numero.

Para facilitar segue jsfiddler do meu caso.

http://jsfiddle.net/xpvt214o/653683/

**Comment by pyetrosafe** [comment]
@EvandersonSilva Bom?

Não entendi teu problema e teu link está direcionando pra outro tipo de código...

Não sei que problemas está tendo, mas até onde testei aqui vai funcionar como você quer:
http://jsfiddle.net/xpvt214o/667441/

**Comment by wanderleihuttel** [comment]
Acredito que o EvandersonSilva  possa estar falando que se eu colocar 1 no input ele deveria mostrar 0,01 e não só 1
Mesma coisa acontece para o 10, que deveria mostrar 0,10 e não só 10.

Preciso digitar um número com 3 caracteres para aparecer a máscara.

Seria interessante se fosse implementados parecido ou igual ao plugin "jquery-maskmoney"
http://plentz.github.io/jquery-maskmoney/

**Comment by pyetrosafe** [comment]
Jsfiddle atualizado - Anterior estava incorreto!!!
http://jsfiddle.net/0emtgr84/

@wanderleihuttel  Infelizmente esse plugin como já mencionado pelo igor, é pra ser leve e pequeno, não foi feito pensando em funcionalidades específicas de moeda... Por isso essas especificações ficam para um plugin específico para isso!

**Comment by igorescobar** [comment]
Este assunto ja foi amplamente discutido e inclusive há um link sobre o assunto no README (home do repositório:
https://github.com/igorescobar/jQuery-Mask-Plugin#problems-or-questions

**Comment by igorescobar** [comment]
Fechei a issue pois não há muito o que eu possa acrescentar sobre o assunto. Se vocês quiserem debater entre vocês, fiquem a vontade.

**Comment by wanderleihuttel** [comment]
Olá @igorescobar. Obrigado pelo esclarecimento.
O teu plugin pode ser utilizado ao invés deste aqui https://github.com/digitalBush/jquery.maskedinput  ?

**Comment by igorescobar** [comment]
@wanderleihuttel quem decide é você :)

**Comment by pyetrosafe** [comment]
@igorescobar Apesar de, não ter sido projetado para, ser um plugin específico para moedas...
Eu fiz alterações no código que permitem o plugin ter algumas funcionalidades como números negativos e prefixo monetário....

Tudo está nessa issue: https://github.com/igorescobar/jQuery-Mask-Plugin/issues/670#issuecomment-406699760
Tem um JS Fiddle com exemplo prático, e todo código alterado lá...
Se puder dar uma olhada, e comentar aqui ou na outra issue que achou...
Poderíamos implentar no projeto...
Hoje eu uso essa alteração no projeto da empresa, mas sempre que tem atualização oficial do plugin, preciso readaptar minhas alterações ao novo código, se fosse implementado oficinalmente seria muito melhor...
Dá uma olhada e diz o que acha... Obrigado!

**Comment by pyetrosafe** [comment]
Fiz uma atualização no código anterior, acredito que ficou bem melhor!!!

Uma das melhorias está em uma chamada facilitada para ter funções monetárias sendo por exemplo:

    $('.money').maskMoney( { negativeNumber: <false(default)|true>, prefixMoney: <empty(default)|'R$'>});

Por  favor façam o teste!!! >>> http://jsfiddle.net/aLmyj4df/48/

**Comment by igorescobar** [comment]
Olá @pyetrosafe obrigado por ajudar nesta questão.

Não sei se é só aqui mas o cursor volta sempre para o fim se você editar qualquer caractere no meio do numero. (Não acontece com o "Normal Mask").

O "Prefix and Negative Mask Money (Type Minus "-" or Plus "+")" não funcionou pra mim.

Com relação a contribuição, eu recomendo que você tenha um fork seu com as suas alterações e referenciar ele aqui também.

**Comment by pyetrosafe** [comment]
Boa tarde @igorescobar ...

> Não sei se é só aqui mas o cursor volta sempre para o fim se você editar qualquer caractere no meio do numero. (Não acontece com o "Normal Mask").

Realmente, não havia percebido, acredito que ocorre devido ao código do evento onKeyPress, provavelmente necessito verificar e talvez corregir o "caret position" !!! Vou analisar como corrigir...

> O "Prefix and Negative Mask Money (Type Minus "-" or Plus "+")" não funcionou pra mim.

Ah, tem razão, mas não foi erro de código exatamente, havia removido a opção negativeNumber desse input para teste, esqueci de voltar antes de finalizar...

> Com relação a contribuição, eu recomendo que você tenha um fork seu com as suas alterações e referenciar ele aqui também.

Ok, farei o Fork, e atualizo aqui depois... Vou primeiro tentar corrigir o problema da posição do caracter indo pro final...

Obrigado pelo feedback!

**Comment by dhyogo** [comment]
Boa tarde @pyetrosafe.
Estou com um problema exatamente igual ao seu. Você conseguiu mandar o PR e foi aceito?
