### ISSUE TITLE
Accentuation

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [igorescobar/jQuery-Mask-Plugin#683]
### Have you take a look into our docs?
Yes

#### Device
Macbook Pro 13 2017

#### Browser (and version)?
Chrome latest

#### Describe de problem depth:
The plugin ignores especial characters that contains accentuation like á à é ç and etc, and i wanna to keep then without the accentuation like if the user input "á" I want to hold "a" and so on

**Comment by igorescobar** [comment]
@diego-lipinski-de-castro Although this doesn't have much to do with the concerns of this plugin you can easily do it yourself using the callbacks the plugin provides to you. 

http://igorescobar.github.io/jQuery-Mask-Plugin/docs.html#callback-examples
