### ISSUE TITLE
Minimized version?

### ISSUE THREAD

**Issue by AlBundyLoves69** [igorescobar/jQuery-Mask-Plugin#684]
Apparently I am blind but I don't find the minimized version. I created one by myself but I would prefer to download it directly from here. Thx

**Comment by igorescobar** [comment]
https://github.com/igorescobar/jQuery-Mask-Plugin/blob/master/dist/jquery.mask.min.js

**Comment by AlBundyLoves69** [comment]
Sorry igorescobar. I was really blind! I apologize for the circumstances.
