### ISSUE TITLE
Aplicar mascara em elementos criados dinamicamente.

### ISSUE THREAD

**Issue by daniellopes81** [igorescobar/jQuery-Mask-Plugin#696]
Como aplico a mascara em um elemento após o dom ?

É possível aplicar a mascara em uma variável (sem uso de um elemento) ?

**Comment by projohnz** [comment]
Estou tentando isso faz tempo, parece que não tem como... Já li essa documentação e tentei 300x fazer as máscaras serem aplicadas após o carregamento completo da página... Em páginas trazidas com Ajax parece que sempre vem bugado

**Comment by projohnz** [comment]
Aparentemente a única maneira funciona é você adicionando no inicio do seu arquivo (após o ready), o código: $.jMaskGlobals.watchDataMask = true;

E colocar manualmente em cada input o " data-mask='expressão regular' "... Porque via javascript ele não atualiza

**Comment by eduardovncs** [comment]
Sempre que o input receber foco ele aplica a mascara 
```
$(document).on( "focus", "#id" , function() {
		$(this).mask('0.000.000.000,00', {reverse: true} );
	});
```

**Comment by fabiohpeixotos** [comment]
eduardovncs, funcionou perfeitamente!! VALEUUU!
