### ISSUE TITLE
Numero de Celular com o 9 FIXADO

### ISSUE THREAD

**Issue by sigmagf** [igorescobar/jQuery-Mask-Plugin#706]
Opa eae amigo, estou em um projeto, que o usuário vai alimentar o formulário, e um dos campos é o numero de celular, e agora desde 2016 se não me engano o 9 é padrão em todos os estados, depois do DDD (00) 90000-00000, ja vi que números de 1-8 são fixos porem o 0 e o 9 não, existe alguma forma de fixa-los? isso ajudaria e muito no meu projeto.

**Comment by gabriel-lima96** [comment]
O que tu tá procurando é um fallback (se for inválido, insere o valor definido como fallback no lugar).
Vê se isso resolve teu problema:
```javascript
$(selector).mask("DDD (00) 90000.0000", {translation: {9:{pattern: /9/, fallback:9}}});
```
