### ISSUE TITLE
Mask not applied to dynamically loaded input field

### ISSUE THREAD

**Issue by jolyon2000** [igorescobar/jQuery-Mask-Plugin#72]
I have a page which loads the jquery mask plugin. Then, when clicking a button, the page dynamically loads a new input=text field. However, this new input field does not have the mask applied to it - I have tried with both the $.mask and data-mask attribute.

**Comment by bordallorafael** [comment]
Mesmo fazendo um tempo o tópico.. minha solução para mascaras em inputs dinâmicos foi:

$('body').on('focus', 'input[data-mask="hour"]', function(){
        $(this).mask("99:99");
    });


Espero ajudar!

**Comment by shayckspear** [comment]
Revivendo o tópico, estou com o mesmo problema, mas no meu caso eu uso JS com .mask.

Até consegui uma solução razoável para aplicar a máscara a campos clonados, basta nesse caso remover a mascara antes de clonar o campo e adicioná-la novamente, o problema está em um caso específico (pelo menos até agora), no caso de moeda onde eu uso a mascara:

$('.real').mask('#.##0,00', {reverse: true});

a máscara é aplicada, mas não fica REVERSE true, alguma solução ?
