### ISSUE TITLE
Somente números e somente letras

### ISSUE THREAD

**Issue by tuliodemelo** [igorescobar/jQuery-Mask-Plugin#73]
Olá, gostaria de saber como criar duas máscaras sem limite de número de caracteres que aceite somente números ou somente letras.

 $('.teste').mask('#9'); não funciona pois fica o limite de 1 caracter

**Comment by annemacena** [comment]
```
$(".soletras").mask("#", {
    maxlength: false,
    translation: {
        '#': {pattern: /[A-zÀ-ÿ]/, recursive: true}
    }
});
```

**Comment by caioagiani** [comment]
> ```
> $(".soletras").mask("#", {
>     maxlength: false,
>     translation: {
>         '#': {pattern: /[A-zÀ-ÿ]/, recursive: true}
>     }
> });
> ```

Caso queiram aceitar espaços também, basta adicionar "`s" ao pattern: 

```js
$(".credit-name").mask("#", {
  maxlength: false,
  translation: {
    "#": { pattern: /[A-zÀ-ÿ\s]/, recursive: true },
  },
});
 ```

**Comment by edivaldo23** [comment]
tem como aceitar letras e numeros , ex:  4AF7473

**Comment by caioagiani** [comment]
> tem como aceitar letras e numeros , ex: 4AF7473

Sim, você apenas precisa adicionar 0-9 ao pattern regex:

```javascript
$(".credit-name").mask("#", {
  maxlength: false,
  translation: {
    "#": { pattern: /[A-Za-z0-9À-ÿ\s]/, recursive: true },
  },
});
```
