### ISSUE TITLE
"On-the-fly Mask Change" behaviour

### ISSUE THREAD

**Issue by fernandosantucci** [igorescobar/jQuery-Mask-Plugin#74]
Oi Igor,

Primeiro eu gostaria de parabenizar você e todos os colaboradores do Mask Plugin. Vocês realmente fizeram um trabalho espetacular e me quebraram um galhão. Dá orgulho de ser brasileiro.

Eu tô usando o jQuery Mask Plugin no Oracle Apex v4.2.3 e a cada dia que passa eu fico surpreso e ao mesmo tempo decepcionado com o Apex por não ter recursos básicos, mas ser muito produtivo em outros aspectos.

Bem... eu queria relatar um problema com o comportamento da feature "On-the-fly Mask Change". Eu tô usando o seguinte código:

$(function() {
  $('.cnpj').mask('00.000.000/0000-00', {reverse: true});
  $('.cpf').mask('000.000.000-00', {reverse: true});
  $('.cpfcnpj').mask('000.000.000-009', {
    onKeyPress: function(cpfcnpj) {
      var masks = ['000.000.000-009', '00.000.000/0000-00'];
      mask = (cpfcnpj.length<15) ? masks[0] : masks[1];
      $('.cpfcnpj').mask(mask, this);
    }
  });
});

Ao usar um campo comum para pessoas físicas e jurídicas, eu criei uma máscara de CPF maior que o necessário (o 9 opcional no final da máscara) para poder identificar que estou digitando um CNPJ e o plugin trocar de máscara. Com esse "truque", está funcionando as mil maravilhas em forms de inclusão, porém quando carrego o valor do banco de dados em forms de alteração, o plugin está truncando o CNPJ sem considerar o atributo 'length' do campo. Acredito que o plugin deva monitorar o evento 'onload' do campo e ler o seu 'length' antes de aplicar a máscara.

Claro, uma solução simples seria separar o CPF do CNPJ na tabela do database, mas as vezes lidamos com legado e nem sempre é possível uma refatoração.

Um forte abraço a todos.

Fernando Santucci

**Comment by MarcoMoraes** [comment]
Olá,
Consegui de outra maneira, utilizando a lógica do telefone de SP:

	var DocMaskBehavior = function (val) {
	  return val.replace(/\D/g, '').length < 12 ? '000.000.000-009' : '00.000.000/0000-00';
	},
	spOptions = {
	  onKeyPress: function(val, e, field, options) {
		  field.mask(DocMaskBehavior.apply({}, arguments), options);
		},clearIfNotMatch: true
		
	};
	$(".cpfcnpj").mask(DocMaskBehavior, spOptions);

**Comment by ruanltbg** [comment]
@MarcoMoraes sua solução fez meu input simplesmente desaparecer o.O

**Comment by edusantosstudio** [comment]
Fazem assim?

$(document).ready(function() {
var DocMaskBehavior = function (val) {
  return val.replace(/\D/g, '').length < 12 ? '000.000.000-009' : '00.000.000/0000-00';
},
spOptions = {
  onKeyPress: function(val, e, field, options) {
      field.mask(DocMaskBehavior.apply({}, arguments), options);
    },clearIfNotMatch: true

};
$(".cpfcnpj").mask(DocMaskBehavior, spOptions);
});
