### ISSUE TITLE
Special Characters in the pattern?

### ISSUE THREAD

**Issue by samyouel** [igorescobar/jQuery-Mask-Plugin#775]
Hey.

Is there a way to trigger a pattern, that allows all characters recursively, also special characters?
`'R': {pattern: /[a-zA-Z0-9]/, recursive: true},`

got this now. but this doesn't allow special characters. is there a way to do that?

thanks!

I basically want to achieve the input of a social page link, that starts per definition with _https://somesocialmedianetwork.com/_ and then finishes with as many characters recursively as the user wants, i.e. their profile

**Comment by nachotisnes** [comment]
Have you tried /./ as your pattern?
