### ISSUE TITLE
AVAST is understanding that it is a virus!

### ISSUE THREAD

**Issue by desenvolvimento-webthomaz** [igorescobar/jQuery-Mask-Plugin#801]
I had a lot of reports in less than 5 hours about this error on websites like:
https://www.daum2brasil.com.br/

![avast](https://github.com/igorescobar/jQuery-Mask-Plugin/assets/73912293/38aa53c7-0d9c-441e-9270-21889c8bd24b)

**Comment by joaolucascoutinho** [comment]
up

**Comment by joaopedroraldi** [comment]
same here

**Comment by igorescobar** [comment]
Hi,

You shouldn't be referencing this url on your sites.

I think you would be safer using the CDN:

<script src="
***@***.***/dist/jquery.mask.min.js
"></script>


- Igor

**Comment by igorescobar** [comment]
https://www.jsdelivr.com/package/npm/jquery-mask-plugin


- Igor

**Comment by desenvolvimento-webthomaz** [comment]
Well, the code is exactly the same. I don't know why AVAST and AVG is behaving like this.

That's legacy code on lots of projects.
Thank you for you tips.
And we are really thankfull for your creation. You're the best!

**Comment by igorescobar** [comment]
No worries,

It's really outside of my control. I do not manage the URL you are using
the reference the library on your code so I cannot garantee that it would
work forever. You either need to use the CDN url or bundle the library
within your project.



- Igor

**Comment by desenvolvimento-webthomaz** [comment]
Well, on reporting to AVAST and AVG that this was a false-positive, they fixed it on the other day.
