### ISSUE TITLE
data-mask not working

### ISSUE THREAD

**Issue by felixjet** [igorescobar/jQuery-Mask-Plugin#90]
Hi, is data-mask working or im doing something wrong?

Here is a jsfiddle: http://jsfiddle.net/tmEHm/

And as a second question, how i can use data-mask with options? Something like:

```
$('input[data-mask]').mask(null, {
    reverse: true,
    byPassKeys: [9, 37, 38, 39, 40]
});
```

null doesnt work, and if i use for example '0', all the masks are applied to that.

Thanks!

**Comment by pedroskakum** [comment]
Igor, estou com o mesmo problema, adaptei a mask '.sp_celphones' de:
http://igorescobar.github.io/jQuery-Mask-Plugin/
ficando assim:
<source>

		 var SPMaskBehavior = function (val) {
			
		  if( val.replace(/\D/g, '').length == 11){
			  return '(00) 00000-0000';
		  }
		  if( val.replace(/\D/g, '').length == 10){
			  return '(00) 0000-00009';
		  }
		  if( val.replace(/\D/g, '').length == 9){
			  return '00000-00009';
		  }
		  if( val.replace(/\D/g, '').length == 8){
			  return '0000-00009';
		  }

		},
		spOptions = {
			onKeyPress: function(val, e, field, options) {
			field.mask(SPMaskBehavior.apply({}, arguments), options);
		}
		};	
		$('.sp_celphones').mask(SPMaskBehavior, spOptions);

</source>

só que agora um erro:
Uncaught TypeError: Cannot read property 'length' of undefined
assombra meu código, se souber o que é e puder me ajudar, estou precisando muito, 

obrigado desde já
