### ISSUE TITLE
onComplete bug

### ISSUE THREAD

**Issue by ghost** [igorescobar/jQuery-Mask-Plugin#91]
Hello!
onComplete fires 3 times immediately if i paste correct mask with ctrl+v

**Comment by rodrigosantiag** [comment]
@igorescobar conseguiu consertar isso? Pelos jsfiddle aqui e pelo meu código também continua executando duas vezes.

Veja meu jsfiddle https://jsfiddle.net/rrsantiago/tcpxjL7x/1/

**Comment by Charliiee** [comment]
Same problem here.
